spring:
  devtools:
    restart:
      additional-paths: '/src/main/jte'

  application:
    name: Tayyib Backend
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/tayyib
    username: tayyib
    password: tayyib_local
    type: com.zaxxer.hikari.HikariDataSource

  liquibase:
    enabled: true

server:
  port: 9443
  shutdown: graceful

dgs:
  graphql:
    virtualthreads:
      enabled: true

gg:
  jte:
    development-mode: true

logging:
  level:
    root: info
