--liquibase formatted sql
--changeset id:00002 author:edwgiz@gmail.com

create table i18n_bundles
(
    locale varchar(10)  not null,
    code   varchar(255) not null,
    value  text         not null,
    constraint i18n_bundles_pk primary key (locale, code)
);

insert into i18n_bundles (locale, code, value)
values ('en', 'hadith-referencing.collections.bukhari', 'Sahih al-Bukhari'),
       ('en', 'hadith-referencing.collections.muslim', 'Sahih Muslim'),
       ('en', 'hadith-referencing.collections.ibnmajah', 'Sunan Ibn Majah'),
       ('en', 'hadith-referencing.collections.tirmidhi', 'Jamiʻ at-Tirmidhi'),
       ('en', 'hadith-referencing.collections.nasai', 'Sunan an-Nasaʻi'),
       ('en', 'hadith-referencing.collections.abudawud', 'Sunan Abi Dawud'),
       ('en', 'hadith-referencing.collections.riyadussalihin', 'Riyad as-Salihin'),

       ('en', 'fasting.head.title', 'Islamic Fasting Calendar'),
       ('en', 'fasting.head.description', 'Islamic fasting dates and times for Ramadan, White Days, Mondays & Thursdays, Ashura, and Arafah based on your location.'),
       ('en', 'fasting.meta.keywords', 'Hijri calendar, Islamic calendar, Ramadan fasting times, Ramadan calendar, Suhoor time, Iftar time, White Days fasting, Monday Thursday fasting, Sunnah fasting, Ashura fasting, Arafah fasting, Ramadan timings, lunar calendar, Muslim fasting'),
       ('en', 'fasting.reason-groups.generic.reasons[0].cites[0].id', 'fasting-reason-generic-0'),
       ('en', 'fasting.reason-groups.generic.reasons[0].cites[0].quote', 'Every deed of the son of Adam is for him except fasting; it is for Me, and I shall reward for it.'),
       ('en', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].collection', 'bukhari'),
       ('en', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].hadith', '1904'),

       ('en', 'settings.location', 'Location'),
       ('en', 'settings.change', 'Change'),
       ('en', 'settings.time-zone', 'Time zone'),
       ('en', 'settings.change-location-window-title', 'Change Location'),
       ('en', 'settings.ok', 'Ok'),
       ('en', 'settings.default', 'Default'),

       ('en', 'calendar.current-month', 'Current Month'),
       ('en', 'calendar.sunrise', 'Sunrise'),
       ('en', 'calendar.sunset', 'Sunset'),

       ('en', 'calendar.monthNames[0]', ''),
       ('en', 'calendar.monthNames[1]', 'Muharram'),
       ('en', 'calendar.monthNames[2]', 'Safar'),
       ('en', 'calendar.monthNames[3]', 'Rabiʻ I'),
       ('en', 'calendar.monthNames[4]', 'Rabiʻ II'),
       ('en', 'calendar.monthNames[5]', 'Jumada I'),
       ('en', 'calendar.monthNames[6]', 'Jumada II'),
       ('en', 'calendar.monthNames[7]', 'Rajab'),
       ('en', 'calendar.monthNames[8]', 'Shaʻban'),
       ('en', 'calendar.monthNames[9]', 'Ramadan'),
       ('en', 'calendar.monthNames[10]', 'Shawwal'),
       ('en', 'calendar.monthNames[11]', 'Dhuʻl-Qiʻdah'),
       ('en', 'calendar.monthNames[12]', 'Dhuʻl-Hijjah'),

       ('en', 'fasting.reason-groups.obligatory.title', 'Obligatory'),
       ('en', 'fasting.reason-groups.obligatory.reasons[0].id', 'fasting-reason-ramadan'),
       ('en', 'fasting.reason-groups.obligatory.reasons[0].title', 'Ramadan'),
       ('en', 'fasting.reason-groups.obligatory.reasons[0].cites[0].quote', 'Islam is built upon five: the testimony that none has the right to be worshipped but Allah and that Muhammad is the Messenger of Allah, establishing prayer, giving zakat, performing Hajj, and fasting Ramadan.'),
       ('en', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].collection', 'bukhari'),
       ('en', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].hadith', '8'),
       ('en', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].collection', 'muslim'),
       ('en', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].hadith', '16'),

       ('en', 'fasting.reason-groups.obligatory.reasons[0].cites[1].quote', 'Whoever fasts Ramadan out of faith and in the hope of reward, his previous sins will be forgiven.'),
       ('en', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].collection', 'bukhari'),
       ('en', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].hadith', '38'),
       ('en', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].collection', 'muslim'),
       ('en', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].hadith', '760'),

       ('en', 'fasting.reason-groups.voluntary.title', 'Voluntary'),
       ('en', 'fasting.reason-groups.voluntary.reasons[0].id', 'fasting-reason-shawwal'),
       ('en', 'fasting.reason-groups.voluntary.reasons[0].title', 'Six Days of Shawwal'),
       ('en', 'fasting.reason-groups.voluntary.reasons[0].cites[0].quote', 'Whoever fasts six days after the Fitr will have completed the year, for whoever does a good deed will have the reward of ten like it.'),
       ('en', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].collection', 'ibnmajah'),
       ('en', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].hadith', '1715'),

       ('en', 'fasting.reason-groups.voluntary.reasons[0].cites[1].quote', 'Whoever fasts Ramadan then follows it with six days of Shawwal, it is as if he fasted for a lifetime.'),
       ('en', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].collection', 'ibnmajah'),
       ('en', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].hadith', '1716'),

       ('en', 'fasting.reason-groups.voluntary.reasons[0].cites[2].quote', 'Whoever fasts the month of Ramadan and then follows it with six days of fasting in the month of Shawwal, it will be as if he has fasted for the entire year.'),
       ('en', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].collection', 'muslim'),
       ('en', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].hadith', '1164'),

       ('en', 'fasting.reason-groups.voluntary.reasons[1].id', 'fasting-reason-arafah-or-ashura'),
       ('en', 'fasting.reason-groups.voluntary.reasons[1].title', 'Days of Arafah and Ashura'),
       ('en', 'fasting.reason-groups.voluntary.reasons[1].cites[0].intro', 'Abu Qatada (ra) reported the Messenger Muhammad (pbuh) said:'),
       ('en', 'fasting.reason-groups.voluntary.reasons[1].cites[0].quote', 'I seek from Allah that fasting on the day of Arafah may atone for the sins of the preceding and the coming years, and I seek from Allah that fasting on the day of Ashura may atone for the sins of the preceding year.'),
       ('en', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].collection', 'muslim'),
       ('en', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].hadith', '1162'),
       ('en', 'fasting.reason-groups.voluntary.reasons[1].tooltips.arafah', 'Day of Arafah'),
       ('en', 'fasting.reason-groups.voluntary.reasons[1].tooltips.ashura', 'Day of Ashura'),
       ('en', 'fasting.reason-groups.voluntary.reasons[2].id', 'fasting-reason-first-9-dhu-al-hijjah'),
       ('en', 'fasting.reason-groups.voluntary.reasons[2].title', 'First nine days of Dhu al-Hijjah'),
       ('en', 'fasting.reason-groups.voluntary.reasons[2].cites[0].intro', 'One of the wives (ra) of the Prophet Muhammad (pbuh) said:'),
       ('en', 'fasting.reason-groups.voluntary.reasons[2].cites[0].quote', 'The Messenger of Allah Muhammad used to fast the first nine days of Dhu al-Hijjah, the day of Ashura, and three days of every month…'),
       ('en', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].collection', 'abudawud'),
       ('en', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].hadith', '2437'),
       ('en', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].collection', 'nasai'),
       ('en', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].hadith', '2417'),

       ('en', 'fasting.reason-groups.voluntary.reasons[3].id', 'fasting-reason-white-days'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].title', 'White Days'),

       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[0].intro',
        'The Prophet Muhammad (pbuh) advised Abu Dharr (ra):'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[0].quote',
        'If you fast any part of the month, then fast the thirteenth, fourteenth and fifteenth.'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].collection', 'tirmidhi'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].hadith', '761'),

       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[1].intro',
        'Narrated `Abdullah bin `Amr bin Al-`As:'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[1].quote',
        'It is sufficient for you to fast three days in a month, as the reward of a good deed is multiplied ten times, so it will be like fasting throughout the year.'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].collection', 'bukhari'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].hadith', '1975'),

       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[2].intro', 'Abu Qatada (ra) reported that the Messenger of Allah (pbuh) said:'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[2].quote', 'Fasting three days every month and that of Ramadan every year is a perpetual fasting.'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].collection', 'muslim'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].hadith', '1162'),

       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[3].intro', 'The Messenger of Allah said to Abu Dharr:'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[3].quote', 'Fasting three days of every month is like fasting for a lifetime.'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].collection', 'ibnmajah'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].hadith', '1708'),

       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[4].intro', 'It was narrated from Jarir bin ʻAbdullah that the Prophet (pbuh) said:'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[4].quote', 'Fasting three days of each month is fasting for a lifetime, and the shining days of Al-Bid, the thirteenth, fourteenth and fifteenth.'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].collection', 'nasai'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].hadith', '2420'),

       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[5].intro', 'Narrated Abu Huraira (ra):'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[5].quote', 'My close friend (the Prophet Muhammad) advised me to do three things: to fast three days of every month, pray two rak‘at of Duha, and pray Witr before sleeping.'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].collection', 'bukhari'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].hadith', '1981'),

       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[6].intro', 'Abu Al-Dardaʻ (ra) reported:'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[6].quote', 'My friend (the Prophet) instructed me to observe three practices which I never leave: he instructed me to fast three days every month'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].collection', 'abudawud'),
       ('en', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].hadith', '1433'),

       ('en', 'fasting.reason-groups.voluntary.reasons[4].id','fasting-reason-monday-thursday'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].title','Monday and Thursday'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].tooltips.monday','Monday'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].tooltips.thursday','Thursday'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[0].intro','This specific statement is narrated by Abu Hurairah (ra):'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[0].quote','Deeds are presented on Mondays and Thursdays, and I love that my deeds be presented while I am fasting.'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].collection','tirmidhi'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].hadith','747'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].collection','riyadussalihin'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].hadith','1256'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[1].intro','Usamah bin Zaid (ra) reported the Messenger (pbuh) said:'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[1].quote','Those are two days in which deeds are shown to the Lord of the worlds, and I like my deeds to be shown when I am fasting.'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].collection','nasai'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].hadith','2358'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[2].intro','The Prophet (pbuh) was asked by Abu Qatada al-Ansari (ra) about fasting on Monday, and he said:'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[2].quote','It was the day on which I was born. on which I was commissioned with prophethood or revelation was sent to me,'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].collection','muslim'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].hadith','1162b'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[3].intro','Aishah (ra) narrated:'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[3].quote','The Prophet used to be keen to fast on Mondays and Thursdays.'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].collection','tirmidhi'),
       ('en', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].hadith','745'),

       ('en', 'fasting.reason-groups.prohibiting.title', 'Prohibiting'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].id', 'fasting-reason-eid-days'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].tooltips.eid-al-fitr', 'Eid al-Fitr'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].tooltips.eid-al-adha', 'Eid al-Adha'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].title', 'Eid al-Fitr and Eid al-Adha'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].intro', 'Narrated Abu Huraira (ra)'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].quote', 'Two fasts are forbidden: fasting on the day of `Id ul Fitr and `Id-ul-Adha'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].collection', 'bukhari'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].hadith', '1993'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].collection', 'muslim'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].hadith', '1138'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].intro', 'Narrated Abu ʻUbaid (ra)'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].quote', 'I attended the ʻId (prayer) along with ʻUmar. He offered prayer before the sermon. He then said: The Messenger of Allah (ﷺ) prohibited fasting on these two days. As regards Id al-Adha, you eat the meat of your sacrificial animals. As for ʻId al-Fitr, you break (i.e. end) your fast.'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].collection', 'abudawud'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].hadith', '2416'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].collection', 'ibnmajah'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].hadith', '1722'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[1].id', 'fasting-reason-tashriq'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[1].title', 'Days of Tashriq'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].quote', 'The days of Tashriq are days of eating and drinking.'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].collection', 'muslim'),
       ('en', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].hadith', '1141a'),

       ('en', 'footer.contacts.label', 'Contacts'),
       ('en', 'footer.contacts.github-ref-description',
        'Please visit GitHub for issues, feature requests, or contributions'),
       ('en', 'footer.attributions.label', 'Attributions'),

       ('en', 'errors.location-access', 'Error getting location:');