--liquibase formatted sql
--changeset id:00016 author:edwgiz@zohomail.eu

insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.current-month', 'الشَّهْرُ الْحَالِيُّ');
insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.event.fajr', 'صَلَاةُ الْفَجْرِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.event.sunset', 'الْغُرُوبُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.monthNames[1]', 'مُحَرَّم');
insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.monthNames[2]', 'صَفَر');
insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.monthNames[3]', 'رَبِيعٌ الْأَوَّلُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.monthNames[4]', 'رَبِيعٌ الْآخِرُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.monthNames[5]', 'جُمَادَى الْأُولَى');
insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.monthNames[6]', 'جُمَادَى الْآخِرَةُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.monthNames[7]', 'رَجَبٌ');
insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.monthNames[8]', 'شَعْبَانُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.monthNames[9]', 'رَمَضَانُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.monthNames[10]', 'شَوَّالٌ');
insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.monthNames[11]', 'ذُو الْقَعْدَةِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.monthNames[12]', 'ذُو الْحِجَّةِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'calendar.monthNames[0]', '');
insert into i18n_bundles (locale, code, value) values ('ar', 'commons.cancel', 'إِلْغَاءٌ');
insert into i18n_bundles (locale, code, value) values ('ar', 'commons.change', 'تَغْيِيرٌ');
insert into i18n_bundles (locale, code, value) values ('ar', 'commons.forget-custom-location', 'نِسْيَانُ الْمَوْقِعِ الْمُخْتَارِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'commons.ok', 'مُوَافَقَةٌ');
insert into i18n_bundles (locale, code, value) values ('ar', 'commons.or', 'أَوْ');
insert into i18n_bundles (locale, code, value) values ('ar', 'errors.location-access', 'خَطَأٌ فِي الْحُصُولِ عَلَى الْمَوْقِعِ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.head.description', 'رَزْنَامَةُ الصِّيَامِ الطَّيِّب: جَدَاوِلُ صِيَامٍ إِسْلَامِيَّةٌ أَصِيلَةٌ تَتَوَافَقُ مَعَ سُنَّةِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ وَتَوَارِيخَ هِجْرِيَّةً مُعْتَمَدَةً.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.head.title', 'رَزْنَامَةُ الصِّيَامِ الْإِسْلَامِيَّةُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.ics.calendar.event.hijri-date-label', 'هِجْرِيٌّ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.ics.calendar.event.summary', 'صِيَامٌ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.ics.calendar.name', 'الصِّيَامُ الْإِسْلَامِيُّ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.ics.copy-link-label', 'نَسْخُ رَابِطِ الِاشْتِرَاكِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.ics.event-summary', 'صِيَامٌ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.ics.hijri-date-label', 'هِجْرِيٌّ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.ics.label', 'إِضَافَةُ الْجَدْوَلِ إِلَى رَزْنَامَتِكَ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.ics.link-label', 'تَنْزِيلُ مِلَفِّ ICS');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.mcp.copy-link-label', 'نَسْخُ رَابِطِ MCP');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.mcp.label', 'تَمْكِينُ أَدَوَاتِ الذَّكَاءِ الِاصْطِنَاعِيِّ لَدَيْكَ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.generic.ics-title', 'سَبَبُ الصِّيَامِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.generic.reasons[0].cites[0].id', 'fasting-reason-generic-0');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.generic.reasons[0].cites[0].quote', 'قَالَ اللَّهُ: كُلُّ عَمَلِ ابْنِ آدَمَ لَهُ إِلَّا الصِّيَامَ، فَإِنَّهُ لِي، وَأَنَا أَجْزِي بِهِ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].hadith', '1904');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.obligatory.ics-title', 'سَبَبُ الصِّيَامِ الْوَاجِبِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.obligatory.reasons[0].cites[1].quote', 'مَنْ صَامَ رَمَضَانَ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].hadith', '760');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].hadith', '38');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.obligatory.reasons[0].cites[0].quote', 'بُنِيَ الْإِسْلَامُ عَلَى خَمْسٍ: شَهَادَةِ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ، وَإِقَامِ الصَّلَاةِ، وَإِيتَاءِ الزَّكَاةِ، وَالْحَجِّ، وَصَوْمِ رَمَضَانَ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].hadith', '16');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].hadith', '8');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.obligatory.reasons[0].id', 'fasting-reason-ramadan');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.obligatory.reasons[0].title', 'رَمَضَانُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.obligatory.title', 'الْوَاجِبُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.ics-title', 'سَبَبُ تَحْرِيمِ الصِّيَامِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].quote', 'أَيَّامُ التَّشْرِيقِ أَيَّامُ أَكْلٍ وَشُرْبٍ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].hadith', '1141a');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[1].id', 'fasting-reason-tashriq');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[1].title', 'أَيَّامُ التَّشْرِيقِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].intro', 'عَنْ أَبِي عُبَيْدٍ، قَالَ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].quote', 'شَهِدْتُ الْعِيدَ مَعَ عُمَرَ فَبَدَأَ بِالصَّلَاةِ قَبْلَ الْخُطْبَةِ ثُمَّ قَالَ: إِنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَهَى عَنْ صِيَامِ هَذَيْنِ الْيَوْمَيْنِ، أَمَّا يَوْمُ الْأَضْحَى فَتَأْكُلُونَ مِنْ لَحْمِ نُسُكِكُمْ، وَأَمَّا يَوْمُ الْفِطْرِ فَفِطْرُكُمْ مِنْ صِيَامِكُمْ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].hadith', '1722');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].hadith', '2416');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].intro', 'عَنْ أَبِي هُرَيْرَةَ، أَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].quote', 'نَهَى عَنْ صِيَامِ يَوْمَيْنِ: يَوْمِ الْأَضْحَى وَيَوْمِ الْفِطْرِ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].hadith', '1138');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].hadith', '1993');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-adha', 'عِيدُ الْأَضْحَى');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-fitr', 'عِيدُ الْفِطْرِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].id', 'fasting-reason-eid-days');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.reasons[0].title', 'عِيدُ الْفِطْرِ وَعِيدُ الْأَضْحَى');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.prohibiting.title', 'الْمُحَرَّمُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.ics-title', 'سَبَبُ الصِّيَامِ التَّطَوُّعِيِّ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[1].cites[0].intro', 'عَنْ أَبِي قَتَادَةَ، أَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[1].cites[0].quote', 'صِيَامُ يَوْمِ عَرَفَةَ أَحْتَسِبُ عَلَى اللَّهِ أَنْ يُكَفِّرَ السَّنَةَ الَّتِي قَبْلَهُ وَالسَّنَةَ الَّتِي بَعْدَهُ، وَصِيَامُ يَوْمِ عَاشُورَاءَ أَحْتَسِبُ عَلَى اللَّهِ أَنْ يُكَفِّرَ السَّنَةَ الَّتِي قَبْلَهُ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[1].headlines.arafah', 'يَوْمُ عَرَفَةَ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[1].headlines.ashura', 'يَوْمُ عَاشُورَاءَ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[1].id', 'fasting-reason-arafah-or-ashura');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[1].title', 'يَوْمُ عَرَفَةَ وَيَوْمُ عَاشُورَاءَ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[2].cites[0].intro', 'عَنْ بَعْضِ أَزْوَاجِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ، قَالَتْ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[2].cites[0].quote', 'كَانَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ يَصُومُ تِسْعَ ذِي الْحِجَّةِ، وَيَوْمَ عَاشُورَاءَ، وَثَلَاثَةَ أَيَّامٍ مِنْ كُلِّ شَهْرٍ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].hadith', '2417');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].hadith', '2437');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[2].id', 'fasting-reason-first-9-dhu-al-hijjah');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[2].title', 'أَوَائِلُ تِسْعِ ذِي الْحِجَّةِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[1].intro', 'عَنْ عَبْدِ اللَّهِ بْنِ عَمْرِو بْنِ الْعَاصِ، قَالَ لِي رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[1].quote', 'إِنَّ بِحَسْبِكَ أَنْ تَصُومَ كُلَّ شَهْرٍ ثَلَاثَةَ أَيَّامٍ، فَإِنَّ لَكَ بِكُلِّ حَسَنَةٍ عَشْرَ أَمْثَالِهَا، فَإِنَّ ذَلِكَ صِيَامُ الدَّهْرِ كُلِّهِ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].hadith', '1975');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[2].intro', 'عَنْ أَبِي قَتَادَةَ، أَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[2].quote', 'ثَلَاثٌ مِنْ كُلِّ شَهْرٍ، وَرَمَضَانُ إِلَى رَمَضَانَ، فَهَذَا صِيَامُ الدَّهْرِ كُلِّهِ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[3].intro', 'عَنْ أَبِي ذَرٍّ، قَالَ: قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[3].quote', 'مَنْ صَامَ ثَلَاثَةَ أَيَّامٍ مِنْ كُلِّ شَهْرٍ فَذَلِكَ صَوْمُ الدَّهْرِ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].hadith', '1708');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[4].intro', 'عَنْ جَرِيرِ بْنِ عَبْدِ اللَّهِ، عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[4].quote', 'صِيَامُ ثَلَاثَةِ أَيَّامٍ مِنْ كُلِّ شَهْرٍ صِيَامُ الدَّهْرِ، وَأَيَّامُ الْبِيضِ صَبِيحَةَ ثَلَاثَ عَشْرَةَ، وَأَرْبَعَ عَشْرَةَ، وَخَمْسَ عَشْرَةَ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].hadith', '2420');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[5].intro', 'عَنْ أَبِي هُرَيْرَةَ، قَالَ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[5].quote', 'أَوْصَانِي خَلِيلِي صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ بِثَلَاثٍ: صِيَامِ ثَلَاثَةِ أَيَّامٍ مِنْ كُلِّ شَهْرٍ، وَرَكْعَتَيِ الضُّحَى، وَأَنْ أُوتِرَ قَبْلَ أَنْ أَنَامَ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].hadith', '1981');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[6].intro', 'عَنْ أَبِي الدَّرْدَاءِ، قَالَ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[6].quote', 'أَوْصَانِي خَلِيلِي صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ بِثَلَاثٍ لَا أَدَعُهُنَّ لِشَيْءٍ: أَوْصَانِي بِصِيَامِ ثَلَاثَةِ أَيَّامٍ مِنْ كُلِّ شَهْرٍ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].hadith', '1433');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[0].intro', 'عَنْ أَبِي ذَرٍّ، يَقُولُ قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[0].quote', 'يَا أَبَا ذَرٍّ، إِذَا صُمْتَ مِنَ الشَّهْرِ ثَلَاثَةَ أَيَّامٍ فَصُمْ ثَلَاثَ عَشْرَةَ، وَأَرْبَعَ عَشْرَةَ، وَخَمْسَ عَشْرَةَ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].hadith', '761');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].id', 'fasting-reason-white-days');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[3].title', 'أَيَّامُ الْبِيضِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[1].intro', 'عَنْ أُسَامَةَ بْنِ زَيْدٍ، قَالَ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[1].quote', 'ذَانِكَ يَوْمَانِ تُعْرَضُ فِيهِمَا الْأَعْمَالُ عَلَى رَبِّ الْعَالَمِينَ، فَأُحِبُّ أَنْ يُعْرَضَ عَمَلِي وَأَنَا صَائِمٌ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].hadith', '2358');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[2].intro', 'عَنْ أَبِي قَتَادَةَ الْأَنْصَارِيِّ، أَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ سُئِلَ عَنْ صَوْمِ يَوْمِ الِاثْنَيْنِ فَقَالَ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[2].quote', 'ذَاكَ يَوْمٌ وُلِدْتُ فِيهِ، وَيَوْمٌ بُعِثْتُ، أَوْ أُنْزِلَ عَلَىَّ فِيهِ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].hadith', '1162b');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[3].intro', 'عَنْ عَائِشَةَ، قَالَتْ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[3].quote', 'كَانَ النَّبِيُّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ يَتَحَرَّى صَوْمَ الِاثْنَيْنِ وَالْخَمِيسِ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].hadith', '745');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[0].intro', 'عَنْ أَبِي هُرَيْرَةَ، أَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ:');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[0].quote', 'تُعْرَضُ الْأَعْمَالُ يَوْمَ الِاثْنَيْنِ وَالْخَمِيسِ، فَأُحِبُّ أَنْ يُعْرَضَ عَمَلِي وَأَنَا صَائِمٌ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].collection', 'riyadussalihin');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].hadith', '1256');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].hadith', '747');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].headlines.monday', 'يَوْمُ الِاثْنَيْنِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].headlines.thursday', 'يَوْمُ الْخَمِيسِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].id', 'fasting-reason-monday-thursday');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[4].title', 'يَوْمُ الِاثْنَيْنِ وَيَوْمُ الْخَمِيسِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[0].cites[1].quote', 'مَنْ صَامَ رَمَضَانَ ثُمَّ أَتْبَعَهُ بِسِتٍّ مِنْ شَوَّالٍ، كَانَ كَصَوْمِ الدَّهْرِ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].hadith', '1716');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[0].cites[2].quote', 'مَنْ صَامَ رَمَضَانَ ثُمَّ أَتْبَعَهُ سِتًّا مِنْ شَوَّالٍ كَانَ كَصِيَامِ الدَّهْرِ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].hadith', '1164');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[0].cites[0].quote', 'مَنْ صَامَ سِتَّةَ أَيَّامٍ بَعْدَ الْفِطْرِ كَانَ تَمَامَ السَّنَةِ، مَنْ جَاءَ بِالْحَسَنَةِ فَلَهُ عَشْرُ أَمْثَالِهَا.');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].hadith', '1715');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[0].id', 'fasting-reason-shawwal');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.reasons[0].title', 'سِتَّةُ أَيَّامٍ مِنْ شَوَّالٍ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reason-groups.voluntary.title', 'التَّطَوُّعُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'fasting.reasons-title', 'أَسْبَابُ الصِّيَامِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'footer.attributions.label', 'الِاعْتِرَافُ بِالْفَضْلِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'footer.contacts.github-ref-description', 'يُرْجَى زِيَارَةُ جِيتْ هَبْ (GitHub) لِلْإِبْلَاغِ عَنْ الْأَخْطَاءِ، أَوْ طَلَبِ الْمِيزَاتِ، أَوْ الْمُسَاهَمَةِ.');
insert into i18n_bundles (locale, code, value) values ('ar', 'footer.contacts.label', 'مَعْلُومَاتُ الِاتِّصَالِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'hadith-referencing.collections.abudawud', 'سُنَنُ أَبِي دَاوُدَ');
insert into i18n_bundles (locale, code, value) values ('ar', 'hadith-referencing.collections.bukhari', 'صَحِيحُ الْبُخَارِيِّ');
insert into i18n_bundles (locale, code, value) values ('ar', 'hadith-referencing.collections.ibnmajah', 'سُنَنُ ابْنِ مَاجَهْ');
insert into i18n_bundles (locale, code, value) values ('ar', 'hadith-referencing.collections.muslim', 'صَحِيحُ مُسْلِمٍ');
insert into i18n_bundles (locale, code, value) values ('ar', 'hadith-referencing.collections.nasai', 'سُنَنُ النَّسَائِيِّ');
insert into i18n_bundles (locale, code, value) values ('ar', 'hadith-referencing.collections.riyadussalihin', 'رِيَاضُ الصَّالِحِينَ');
insert into i18n_bundles (locale, code, value) values ('ar', 'hadith-referencing.collections.tirmidhi', 'جَامِعُ التِّرْمِذِيِّ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.AUTOMATIC.methodNames.AUTO_BY_LOCATION', 'تِلْقَائِيٌّ بِحَسَبِ الْمَوْقِعِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.AUTOMATIC.name', 'تِلْقَائِيٌّ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.ALGERIA', 'الْجَزَائِرُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.CIL', 'الْمُجْتَمَعُ الْإِسْلَامِيُّ فِي لِشْبُونَةَ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.DIYANET', 'دِيَانَت (تُرْكِيَا)');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.DUBAI', 'دُبَيُّ، الْإِمَارَاتُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.EGAS', 'الْهَيْئَةُ الْعَامَّةُ لِلْمِسَاحَةِ الْمِصْرِيَّةُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.GULF', 'مِنْطَقَةُ الْخَلِيجِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.ISNA', 'الْجَمْعِيَّةُ الْإِسْلَامِيَّةُ لِأَمْرِيكَا الشَّمَالِيَّةِ (ISNA)');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.JAKIM', 'جَاكِيم، مَالِيزِيَا');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.KARACHI', 'جَامِعَةُ الْعُلُومِ الْإِسْلَامِيَّةِ، كَرَاتْشِي');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.KEMENAG', 'وِزَارَةُ الشُّؤُونِ الدِّينِيَّةِ، إِنْدُونِيسِيَا');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.KUWAIT', 'الْكُوَيْتُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.MOROCCO', 'الْمَغْرِبُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.MSC', 'لَجْنَةُ رُؤْيَةِ الْهِلَالِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.MUIS', 'مَجْلِسُ الشُّؤُونِ الدِّينِيَّةِ الْإِسْلَامِيَّةِ فِي سِنْغَافُورَةَ (MUIS)');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.MWL', 'رَابِطَةُ الْعَالَمِ الْإِسْلَامِيِّ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.QATAR', 'قَطَرُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.SAMR', 'الْإِدَارَةُ الرُّوحِيَّةُ لِلْمُسْلِمِينَ، رُوسِيَا');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.SHIA_QUM', 'الشِّيعَةُ الِاثْنَا عَشَرِيَّةُ، قُمْ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.TEHRAN', 'مَعْهَدُ الْجِيُوفِيزِيَاءِ، جَامِعَةُ طِهْرَانَ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.TUNISIA', 'تُونِسُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.UMM_AL_QURA', 'جَامِعَةُ أُمِّ الْقُرَى، مَكَّةُ الْمُكَرَّمَةُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.methodNames.UOIF', 'اتِّحَادُ الْمُنَظَّمَاتِ الْإِسْلَامِيَّةِ فِي فَرَنْسَا (UOIF)');
insert into i18n_bundles (locale, code, value) values ('ar', 'prayer-time-method-groups.STANDARD.name', 'قِيَاسِيٌّ');
insert into i18n_bundles (locale, code, value) values ('ar', 'settings.location.forget-custom-location', 'نِسْيَانُ الْمَوْقِعِ الْمُخْتَارِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'settings.location.label', 'الْمَوْقِعُ');
insert into i18n_bundles (locale, code, value) values ('ar', 'settings.location.permission.change-in-browser', 'اسْتِخْدَامُ الْمَوْقِعِ الْحَالِيِّ');
insert into i18n_bundles (locale, code, value) values ('ar', 'settings.location.permission.grant-reason', 'لِمَعْرِفَةِ أَوْقَاتِ الْفَجْرِ وَالْغُرُوبِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'settings.location.permission.revoke-blocking', 'يُرْجَى إِلْغَاءُ الْحَظْرِ فِي إِعْدَادَاتِ الْمَوْقِعِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'settings.location.pick-on-map', 'اخْتَرِ الْمَوْقِعَ عَلَى الْخَرِيطَةِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'settings.prayer-time-method', 'طَرِيقَةُ حِسَابِ أَوْقَاتِ الصَّلَاةِ');
insert into i18n_bundles (locale, code, value) values ('ar', 'settings.time-zone', 'الْمِنْطَقَةُ الزَّمَنِيَّةُ');