--liquibase formatted sql
--changeset id:00019 author:edwgiz@zohomail.eu

insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.current-month', 'Watan yanzu');
insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.event.fajr', 'Fajr');
insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.event.sunset', 'Faɗuwar rana');
insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.monthNames[1]', 'Muharram');
insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.monthNames[2]', 'Safar');
insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.monthNames[3]', 'Rabiʼu I');
insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.monthNames[4]', 'Rabiʼu II');
insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.monthNames[5]', 'Jumada I');
insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.monthNames[6]', 'Jumada II');
insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.monthNames[7]', 'Rajab');
insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.monthNames[8]', 'Shaʼban');
insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.monthNames[9]', 'Ramadan');
insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.monthNames[10]', 'Shawwal');
insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.monthNames[11]', 'Zulƙiɗa');
insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.monthNames[12]', 'Zulhijja');
insert into i18n_bundles (locale, code, value) values ('ha', 'calendar.monthNames[0]', '');
insert into i18n_bundles (locale, code, value) values ('ha', 'commons.cancel', 'Soke');
insert into i18n_bundles (locale, code, value) values ('ha', 'commons.change', 'Sauya');
insert into i18n_bundles (locale, code, value) values ('ha', 'commons.forget-custom-location', 'Manta da wurin da aka zaɓa');
insert into i18n_bundles (locale, code, value) values ('ha', 'commons.ok', 'OK');
insert into i18n_bundles (locale, code, value) values ('ha', 'commons.or', 'ko');
insert into i18n_bundles (locale, code, value) values ('ha', 'errors.location-access', 'Kuskure wajen samun wuri:');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.head.description', 'Kalandar Azumi ta Tayyib: jadawalin azumin Musulmi na sahihi, bisa Sunna da kwanakin Hijira da aka tabbatar.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.head.title', 'Kalandar Azumi ta Musulunci');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.ics.calendar.event.hijri-date-label', 'Hijira');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.ics.calendar.event.summary', 'Azumi');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.ics.calendar.name', 'Azumin Musulunci');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.ics.copy-link-label', 'Kwafi mahadar karɓar jadawali');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.ics.event-summary', 'Azumi');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.ics.hijri-date-label', 'Hijira');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.ics.label', 'Ƙara jadawali a kalandarku');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.ics.link-label', 'Sauke fayil ɗin ICS');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.mcp.copy-link-label', 'Kwafi mahadar MCP');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.mcp.label', 'Ƙarfafa kayan aikin AI ɗinku');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.generic.ics-title', 'Dalilin azumi');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.generic.reasons[0].cites[0].id', 'fasting-reason-generic-0');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.generic.reasons[0].cites[0].quote', 'Dukkan ayyukan ɗan Adam nasa ne sai azumi; shi kuwa nawa ne, Ina kuma zan saka da shi.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].hadith', '1904');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.obligatory.ics-title', 'Dalilin azumi na wajibi');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.obligatory.reasons[0].cites[1].quote', 'Wanda ya yi azumin Ramadan bisa imani da fatan lada, za a yi masa gafarar zunubansa na baya.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].hadith', '760');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].hadith', '38');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.obligatory.reasons[0].cites[0].quote', 'An gina Musulunci a kan abubuwa biyar: shahada cewa babu abin bautar da ya cancanta sai Allah, kuma Muhammad Manzon Allah ne, kafa salla, bayar da zakka, yin Hajji, da azumin Ramadan.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].hadith', '16');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].hadith', '8');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.obligatory.reasons[0].id', 'fasting-reason-ramadan');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.obligatory.reasons[0].title', 'Ramadan');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.obligatory.title', 'Wajibi');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.ics-title', 'Dalilin haramta azumi');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].quote', 'Kwanakin Tashriq kwanakin ci da sha ne.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].hadith', '1141a');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[1].id', 'fasting-reason-tashriq');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[1].title', 'Kwanakin Tashriq');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].intro', 'Abu Ubaid (ra) ya ruwaito:');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].quote', 'Na halarci Idin tare da Umar, sai ya fara da salla kafin hutba, saʼan nan ya ce: Manzon Allah (SAW) ya hana azumi a waɗannan kwanaki biyu; game da Idin Adha, kuna cin naman hadin ku, kuma game da Idin Fitr, shi ne karyewar azuminku.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].hadith', '1722');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].hadith', '2416');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].intro', 'Abu Huraira (ra) ya ruwaito:');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].quote', 'An hana azumi biyu: azumi ranar Idin Fitr da azumi ranar Idin Adha.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].hadith', '1138');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].hadith', '1993');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-adha', 'Idin Adha');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-fitr', 'Idin Fitr');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].id', 'fasting-reason-eid-days');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.reasons[0].title', 'Idin Fitr da Idin Adha');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.prohibiting.title', 'Haramta');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.ics-title', 'Dalilin azumi na son rai');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[1].cites[0].intro', 'Abu Qatada (ra) ya ruwaito cewa Manzon Allah Muhammad (SAW) ya ce:');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[1].cites[0].quote', 'Ina fatan daga Allah cewa azumi a Ranar Arafah zai rufe zunubobin shekara da ta gabata da na shekara da ke zuwa, kuma azumi a Ranar Ashura zai rufe zunubobin shekara da ta gabata.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[1].headlines.arafah', 'Ranar Arafah');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[1].headlines.ashura', 'Ranar Ashura');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[1].id', 'fasting-reason-arafah-or-ashura');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[1].title', 'Ranakun Arafah da Ashura');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[2].cites[0].intro', 'Daya daga cikin matan Annabi Muhammad (SAW) ta ce:');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[2].cites[0].quote', 'Manzon Allah Muhammad (SAW) ya kasance yana yin azumi a kwanaki tara na farko na Zulhijja, da Ranar Ashura, da kwanaki uku na kowane wata.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].hadith', '2417');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].hadith', '2437');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[2].id', 'fasting-reason-first-9-dhu-al-hijjah');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[2].title', 'Kwanaki tara na farko na Zulhijja');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[1].intro', 'Abdullah bin Amr bin Al-As (ra) ya ruwaito:');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[1].quote', 'Ya isa ka yi azumi kwanaki uku a kowane wata, domin lada mai kyau tana ninka sau goma, don haka zai zama kamar azumin shekara gaba ɗaya.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].hadith', '1975');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[2].intro', 'Abu Qatada (ra) ya ruwaito cewa Manzon Allah (SAW) ya ce:');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[2].quote', 'Azumi kwanaki uku a kowane wata, da azumin Ramadan a kowane shekara, shi ne azumi na dindindin.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[3].intro', 'Manzon Allah (SAW) ya ce wa Abu Dharr (ra):');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[3].quote', 'Azumi kwanaki uku a kowane wata kamar azumi ne na rayuwa gaba ɗaya.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].hadith', '1708');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[4].intro', 'An ruwaito daga Jarir bin Abdullah (ra) cewa Manzon Allah (SAW) ya ce:');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[4].quote', 'Azumi kwanaki uku a kowane wata azumi ne na rayuwa gaba ɗaya, kuma kwanakin Al-Bid masu haske su ne na sha uku, sha huɗu da sha biyar.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].hadith', '2420');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[5].intro', 'Abu Huraira (ra) ya ruwaito:');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[5].quote', 'Abina na kusa (Manzon Allah Muhammad (SAW)) ya ba ni shawara kan abubuwa uku: in yi azumi kwanaki uku a kowane wata, in yi salla rakaʼa biyu na Duha, in kuma yi salla Witir kafin in barci.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].hadith', '1981');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[6].intro', 'Abu Al-Darda (ra) ya ruwaito:');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[6].quote', 'Abina (Manzon Allah (SAW)) ya umarce ni da in riƙe ayyuka uku da ba na barin su: ya umarce ni da azumi kwanaki uku a kowane wata.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].hadith', '1433');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[0].intro', 'Annabi Muhammad (SAW) ya ba Abu Dharr (ra) shawara:');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[0].quote', 'Idan ka yi azumi a wani bangare na wata, to ka yi azumi kwanaki na sha uku, sha huɗu da sha biyar.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].hadith', '761');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].id', 'fasting-reason-white-days');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[3].title', 'Kwanakin Fari');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[1].intro', 'Usamah bin Zaid (ra) ya ruwaito cewa Manzon Allah (SAW) ya ce:');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[1].quote', 'Waɗannan kwanaki biyu ne da ake gabatar da ayyuka ga Ubangijin talikai, ina kuma ina son a gabatar da aikina ina cikin azumi.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].hadith', '2358');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[2].intro', 'Abu Qatada Al-Ansari (ra) ya ruwaito cewa an tambayi Manzon Allah (SAW) game da azumi a Litinin, sai ya ce:');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[2].quote', 'Ita ce ranar da aka haife ni, kuma ita ce ranar da aka naɗa ni Annabi ko aka sauko mini da wahayi.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].hadith', '1162b');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[3].intro', 'Aisha (ra) ta ruwaito:');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[3].quote', 'Annabi (SAW) ya kasance yana neman yin azumi a Litinin da Alhamis.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].hadith', '745');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[0].intro', 'Abu Huraira (ra) ya ruwaito cewa Manzon Allah (SAW) ya ce:');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[0].quote', 'Ana gabatar da ayyuka a Litinin da Alhamis, ina kuma ina son a gabatar da aikina ina cikin azumi.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].collection', 'riyadussalihin');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].hadith', '1256');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].hadith', '747');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].headlines.monday', 'Litinin');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].headlines.thursday', 'Alhamis');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].id', 'fasting-reason-monday-thursday');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[4].title', 'Litinin da Alhamis');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[0].cites[1].quote', 'Wanda ya yi azumin Ramadan, saʼan nan ya bi da kwanaki shida na Shawwal, kamar ya yi azumi ne na rayuwa gaba ɗaya.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].hadith', '1716');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[0].cites[2].quote', 'Wanda ya yi azumin watan Ramadan, saʼan nan ya bi da azumi kwanaki shida a watan Shawwal, zai zama kamar ya yi azumi ne na shekara gaba ɗaya.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].hadith', '1164');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[0].cites[0].quote', 'Wanda ya yi azumi kwanaki shida bayan Idin Fitr, ya cika shekara; domin wanda ya yi aiki mai kyau, zai sami lada kamar goma irinsa.');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].hadith', '1715');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[0].id', 'fasting-reason-shawwal');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.reasons[0].title', 'Kwanaki Shida na Shawwal');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reason-groups.voluntary.title', 'Na son rai');
insert into i18n_bundles (locale, code, value) values ('ha', 'fasting.reasons-title', 'Dalilan azumi');
insert into i18n_bundles (locale, code, value) values ('ha', 'footer.attributions.label', 'Ambaton tushe');
insert into i18n_bundles (locale, code, value) values ('ha', 'footer.contacts.github-ref-description', 'Ku ziyarci GitHub don matsaloli, buƙatun fasali, ko gudummawa.');
insert into i18n_bundles (locale, code, value) values ('ha', 'footer.contacts.label', 'Hulɗa');
insert into i18n_bundles (locale, code, value) values ('ha', 'hadith-referencing.collections.abudawud', 'Sunan Abu Dawud');
insert into i18n_bundles (locale, code, value) values ('ha', 'hadith-referencing.collections.bukhari', 'Sahih Al-Bukhari');
insert into i18n_bundles (locale, code, value) values ('ha', 'hadith-referencing.collections.ibnmajah', 'Sunan Ibn Majah');
insert into i18n_bundles (locale, code, value) values ('ha', 'hadith-referencing.collections.muslim', 'Sahih Muslim');
insert into i18n_bundles (locale, code, value) values ('ha', 'hadith-referencing.collections.nasai', 'Sunan An-Nasaʼi');
insert into i18n_bundles (locale, code, value) values ('ha', 'hadith-referencing.collections.riyadussalihin', 'Riyad As-Salihin');
insert into i18n_bundles (locale, code, value) values ('ha', 'hadith-referencing.collections.tirmidhi', 'Jamiʼ At-Tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.AUTOMATIC.methodNames.AUTO_BY_LOCATION', 'Otomatik bisa wuri');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.AUTOMATIC.name', 'Otomatik');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.ALGERIA', 'Aljeriya');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.CIL', 'Jamaʼar Musulmi ta Lisbon');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.DIYANET', 'Diyanet (Turkiyya)');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.DUBAI', 'Dubai, Hadaddiyar Daular Larabawa');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.EGAS', 'Babbar Hukumar Bincike ta Masar');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.GULF', 'Yankin Khaleej');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.ISNA', 'Jamaʼar Musulmi ta Arewacin Amurka (ISNA)');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.JAKIM', 'JAKIM, Maleziya');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.KARACHI', 'Jamiʼar Kimiyyar Musulunci, Karachi');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.KEMENAG', 'Maʼaikatatar Harkokin Addini, Indonesiya');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.KUWAIT', 'Kuwit');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.MOROCCO', 'Maroko');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.MSC', 'Kwamitin Duba Hilal');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.MUIS', 'Majlis Ugama Islam Singapura (MUIS)');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.MWL', 'Rabita ta Musulmin Duniya');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.QATAR', 'Qatar');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.SAMR', 'Hukumar Harkokin Musulmi, Rasha');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.SHIA_QUM', 'Shiʼa Ithna Ashari, Qum');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.TEHRAN', 'Cibiyar Geophysics, Jamiʼar Tehran');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.TUNISIA', 'Tunisiya');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.UMM_AL_QURA', 'Jamiʼar Umm Al-Qura, Makka');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.methodNames.UOIF', 'Ƙungiyar Ƙungiyoyin Musulmi ta Faransa (UOIF)');
insert into i18n_bundles (locale, code, value) values ('ha', 'prayer-time-method-groups.STANDARD.name', 'Daidaitacce');
insert into i18n_bundles (locale, code, value) values ('ha', 'settings.location.forget-custom-location', 'Manta da wurin da aka zaɓa');
insert into i18n_bundles (locale, code, value) values ('ha', 'settings.location.label', 'Wuri');
insert into i18n_bundles (locale, code, value) values ('ha', 'settings.location.permission.change-in-browser', 'Yi amfani da wurin yanzu');
insert into i18n_bundles (locale, code, value) values ('ha', 'settings.location.permission.grant-reason', 'Don lokutan Fajr da faɗuwar rana');
insert into i18n_bundles (locale, code, value) values ('ha', 'settings.location.permission.revoke-blocking', 'Don Allah ku cire hana shiga a saitunan shafin');
insert into i18n_bundles (locale, code, value) values ('ha', 'settings.location.pick-on-map', 'Zaɓi wuri a taswira');
insert into i18n_bundles (locale, code, value) values ('ha', 'settings.prayer-time-method', 'Hanyar lissafin lokutan salla');
insert into i18n_bundles (locale, code, value) values ('ha', 'settings.time-zone', 'Yankin lokaci');
