--liquibase formatted sql
--changeset id:00018 author:edwgiz@zohomail.eu

insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.current-month', 'ماه جاری');
insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.event.fajr', 'اذان صبح');
insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.event.sunset', 'غروب آفتاب');
insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.monthNames[1]', 'محرم');
insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.monthNames[2]', 'صفر');
insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.monthNames[3]', 'ربیع‌الاول');
insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.monthNames[4]', 'ربیع‌الثانی');
insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.monthNames[5]', 'جمادی‌الاول');
insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.monthNames[6]', 'جمادی‌الثانی');
insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.monthNames[7]', 'رجب');
insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.monthNames[8]', 'شعبان');
insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.monthNames[9]', 'رمضان');
insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.monthNames[10]', 'شوال');
insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.monthNames[11]', 'ذی‌القعده');
insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.monthNames[12]', 'ذی‌الحجه');
insert into i18n_bundles (locale, code, value) values ('fa', 'calendar.monthNames[0]', '');
insert into i18n_bundles (locale, code, value) values ('fa', 'commons.cancel', 'لغو');
insert into i18n_bundles (locale, code, value) values ('fa', 'commons.change', 'تغییر');
insert into i18n_bundles (locale, code, value) values ('fa', 'commons.forget-custom-location', 'حذف مکان انتخابی');
insert into i18n_bundles (locale, code, value) values ('fa', 'commons.ok', 'تأیید');
insert into i18n_bundles (locale, code, value) values ('fa', 'commons.or', 'یا');
insert into i18n_bundles (locale, code, value) values ('fa', 'errors.location-access', 'خطا در دریافت موقعیت مکانی:');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.head.description', 'تقویم روزه طیب: برنامه‌های روزه‌داری اسلامی اصیل، هماهنگ با سنت پیامبر اکرم (ص) و تاریخ‌های هجری تأییدشده.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.head.title', 'تقویم روزه‌داری اسلامی');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.ics.calendar.event.hijri-date-label', 'هجری');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.ics.calendar.event.summary', 'روزه');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.ics.calendar.name', 'روزه‌داری اسلامی');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.ics.copy-link-label', 'کپی پیوند اشتراک');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.ics.event-summary', 'روزه');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.ics.hijri-date-label', 'هجری');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.ics.label', 'افزودن برنامه به تقویم شما');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.ics.link-label', 'دانلود فایل ICS');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.mcp.copy-link-label', 'کپی پیوند MCP');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.mcp.label', 'توانمندسازی ابزارهای هوش مصنوعی شما');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.generic.ics-title', 'دلیل روزه');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.generic.reasons[0].cites[0].id', 'fasting-reason-generic-0');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.generic.reasons[0].cites[0].quote', 'هر عمل فرزند آدم برای خودش است، مگر روزه؛ زیرا آن برای من است و خودم پاداش آن را می‌دهم.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].hadith', '1904');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.obligatory.ics-title', 'دلیل روزه واجب');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.obligatory.reasons[0].cites[1].quote', 'هر کس ماه رمضان را از روی ایمان و امید به پاداش روزه بدارد، گناهان گذشته‌اش آمرزیده می‌شود.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].hadith', '760');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].hadith', '38');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.obligatory.reasons[0].cites[0].quote', 'اسلام بر پنج چیز بنا شده است: گواهی دادن به اینکه معبودی جز الله نیست و محمد فرستاده خداست، برپایی نماز، ادای زکات، حج و روزه رمضان.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].hadith', '16');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].hadith', '8');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.obligatory.reasons[0].id', 'fasting-reason-ramadan');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.obligatory.reasons[0].title', 'رمضان');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.obligatory.title', 'واجب');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.ics-title', 'دلیل حرمت روزه');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].quote', 'ایام تشریق، روزهای خوردن و نوشیدن است.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].hadith', '1141a');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[1].id', 'fasting-reason-tashriq');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[1].title', 'ایام تشریق');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].intro', 'ابوعبید (رضی‌الله‌عنه) روایت کرده است:');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].quote', 'همراه عمر در عید حاضر شدم؛ او نماز را پیش از خطبه خواند، سپس گفت: رسول خدا (ص) از روزه گرفتن در این دو روز نهی فرمودند: روز عید قربان که از گوشت قربانی‌هایتان می‌خورید و روز عید فطر که پایان روزه شماست.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].hadith', '1722');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].hadith', '2416');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].intro', 'ابوهریره (رضی‌الله‌عنه) روایت کرده است که رسول خدا (ص):');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].quote', 'از روزه گرفتن در دو روز نهی فرمودند: روز عید قربان و روز عید فطر.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].hadith', '1138');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].hadith', '1993');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-adha', 'عید قربان');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-fitr', 'عید فطر');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].id', 'fasting-reason-eid-days');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.reasons[0].title', 'عید فطر و عید قربان');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.prohibiting.title', 'حرام');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.ics-title', 'دلیل روزه مستحبی');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[1].cites[0].intro', 'ابوقتاده (رضی‌الله‌عنه) روایت کرده است که رسول خدا (ص) فرمودند:');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[1].cites[0].quote', 'از خدا امید دارم که روزه روز عرفه کفاره گناهان سال پیش و سال پس از آن باشد، و روزه روز عاشورا کفاره گناهان سال پیش باشد.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[1].headlines.arafah', 'روز عرفه');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[1].headlines.ashura', 'روز عاشورا');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[1].id', 'fasting-reason-arafah-or-ashura');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[1].title', 'روز عرفه و روز عاشورا');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[2].cites[0].intro', 'یکی از همسران پیامبر اکرم (ص) روایت کرده است:');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[2].cites[0].quote', 'پیامبر اکرم (ص) نه روز نخست ذی‌الحجه، روز عاشورا و سه روز از هر ماه را روزه می‌داشتند.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].hadith', '2417');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].hadith', '2437');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[2].id', 'fasting-reason-first-9-dhu-al-hijjah');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[2].title', 'نه روز نخست ذی‌الحجه');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[1].intro', 'عبدالله بن عمرو بن عاص (رضی‌الله‌عنه) گفت: رسول خدا (ص) به من فرمود:');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[1].quote', 'تو را بس است که در هر ماه سه روز روزه بگیری؛ زیرا هر نیکی ده برابر پاداش دارد؛ پس این روزه تمام سال است.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].hadith', '1975');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[2].intro', 'ابوقتاده (رضی‌الله‌عنه) روایت کرده است که رسول خدا (ص) فرمودند:');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[2].quote', 'سه روز از هر ماه و روزه رمضان تا رمضان، روزه همیشگی است.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[3].intro', 'رسول خدا (ص) به ابوذر (رضی‌الله‌عنه) فرمودند:');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[3].quote', 'هر کس سه روز از هر ماه را روزه بدارد، این روزه تمام عمر است.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].hadith', '1708');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[4].intro', 'جریر بن عبدالله (رضی‌الله‌عنه) از پیامبر اکرم (ص) روایت کرده است که فرمودند:');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[4].quote', 'روزه سه روز از هر ماه، روزه تمام عمر است؛ و روزهای روشن، سیزدهم، چهاردهم و پانزدهم است.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].hadith', '2420');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[5].intro', 'ابوهریره (رضی‌الله‌عنه) روایت کرده است:');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[5].quote', 'دوست صمیمی‌ام، پیامبر اکرم (ص)، مرا به سه چیز سفارش کرد: روزه سه روز از هر ماه، دو رکعت نماز ضحی و خواندن نماز وتر پیش از خواب.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].hadith', '1981');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[6].intro', 'ابودرداء (رضی‌الله‌عنه) روایت کرده است:');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[6].quote', 'دوست صمیمی‌ام، پیامبر اکرم (ص)، مرا به سه چیز سفارش کرد که هرگز ترکشان نمی‌کنم؛ از آن جمله روزه سه روز از هر ماه است.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].hadith', '1433');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[0].intro', 'پیامبر اکرم (ص) به ابوذر (رضی‌الله‌عنه) فرمودند:');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[0].quote', 'ای ابوذر، اگر از ماهی سه روز روزه می‌داری، سیزدهم، چهاردهم و پانزدهم را روزه بدار.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].hadith', '761');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].id', 'fasting-reason-white-days');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[3].title', 'ایام بیض (روزهای روشن)');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[1].intro', 'اسامه بن زید (رضی‌الله‌عنه) روایت کرده است که رسول خدا (ص) فرمودند:');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[1].quote', 'آن دو روز، روزهایی هستند که اعمال در آن‌ها به پروردگار جهانیان عرضه می‌شود؛ و من دوست دارم عملم در حالی عرضه شود که روزه‌ام.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].hadith', '2358');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[2].intro', 'ابوقتاده انصاری (رضی‌الله‌عنه) از پیامبر اکرم (ص) درباره روزه دوشنبه پرسید و ایشان فرمودند:');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[2].quote', 'آن روزی است که من در آن زاده شدم و روزی است که مبعوث شدم یا وحی بر من نازل گردید.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].hadith', '1162b');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[3].intro', 'عایشه (رضی‌الله‌عنها) روایت کرده است:');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[3].quote', 'پیامبر اکرم (ص) به روزه گرفتن دوشنبه و پنجشنبه اهتمام می‌ورزیدند.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].hadith', '745');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[0].intro', 'ابوهریره (رضی‌الله‌عنه) روایت کرده است که رسول خدا (ص) فرمودند:');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[0].quote', 'اعمال در روز دوشنبه و پنجشنبه عرضه می‌شوند؛ و من دوست دارم عملم در حالی عرضه شود که روزه‌ام.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].collection', 'riyadussalihin');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].hadith', '1256');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].hadith', '747');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].headlines.monday', 'دوشنبه');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].headlines.thursday', 'پنجشنبه');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].id', 'fasting-reason-monday-thursday');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[4].title', 'دوشنبه و پنجشنبه');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[0].cites[1].quote', 'هر کس رمضان را روزه بدارد و سپس شش روز از شوال را به آن بیفزاید، مانند روزه تمام سال است.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].hadith', '1716');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[0].cites[2].quote', 'هر کس ماه رمضان را روزه بدارد و سپس شش روز از شوال را روزه بگیرد، مانند این است که تمام سال را روزه داشته است.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].hadith', '1164');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[0].cites[0].quote', 'هر کس شش روز پس از فطر را روزه بدارد، گویا سال را کامل کرده است؛ هر کس نیکی کند، ده برابر آن پاداش دارد.');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].hadith', '1715');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[0].id', 'fasting-reason-shawwal');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.reasons[0].title', 'شش روز از شوال');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reason-groups.voluntary.title', 'مستحبی');
insert into i18n_bundles (locale, code, value) values ('fa', 'fasting.reasons-title', 'دلایل روزه‌داری');
insert into i18n_bundles (locale, code, value) values ('fa', 'footer.attributions.label', 'اسناد و قدردانی');
insert into i18n_bundles (locale, code, value) values ('fa', 'footer.contacts.github-ref-description', 'لطفاً برای گزارش خطاها، درخواست قابلیت‌های جدید یا مشارکت، به گیت‌هاب مراجعه کنید.');
insert into i18n_bundles (locale, code, value) values ('fa', 'footer.contacts.label', 'اطلاعات تماس');
insert into i18n_bundles (locale, code, value) values ('fa', 'hadith-referencing.collections.abudawud', 'سنن ابی‌داوود');
insert into i18n_bundles (locale, code, value) values ('fa', 'hadith-referencing.collections.bukhari', 'صحیح بخاری');
insert into i18n_bundles (locale, code, value) values ('fa', 'hadith-referencing.collections.ibnmajah', 'سنن ابن‌ماجه');
insert into i18n_bundles (locale, code, value) values ('fa', 'hadith-referencing.collections.muslim', 'صحیح مسلم');
insert into i18n_bundles (locale, code, value) values ('fa', 'hadith-referencing.collections.nasai', 'سنن نسائی');
insert into i18n_bundles (locale, code, value) values ('fa', 'hadith-referencing.collections.riyadussalihin', 'ریاض الصالحین');
insert into i18n_bundles (locale, code, value) values ('fa', 'hadith-referencing.collections.tirmidhi', 'جامع ترمذی');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.AUTOMATIC.methodNames.AUTO_BY_LOCATION', 'خودکار بر اساس موقعیت مکانی');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.AUTOMATIC.name', 'خودکار');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.ALGERIA', 'الجزایر');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.CIL', 'جامعه اسلامی لیسبون');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.DIYANET', 'دیانت (ترکیه)');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.DUBAI', 'دبی، امارات متحده عربی');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.EGAS', 'هیئت عمومی نقشه‌برداری مصر');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.GULF', 'منطقه خلیج');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.ISNA', 'انجمن اسلامی آمریکای شمالی (ISNA)');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.JAKIM', 'اداره توسعه اسلامی مالزی (JAKIM)');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.KARACHI', 'دانشگاه علوم اسلامی، کراچی');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.KEMENAG', 'وزارت امور دینی، اندونزی');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.KUWAIT', 'کویت');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.MOROCCO', 'مراکش');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.MSC', 'کمیته رؤیت هلال ماه');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.MUIS', 'شورای امور دینی اسلامی سنگاپور (MUIS)');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.MWL', 'اتحادیه جهانی اسلام');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.QATAR', 'قطر');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.SAMR', 'اداره معنوی مسلمانان، روسیه');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.SHIA_QUM', 'شیعه دوازده‌امامی، قم');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.TEHRAN', 'مؤسسه ژئوفیزیک، دانشگاه تهران');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.TUNISIA', 'تونس');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.UMM_AL_QURA', 'دانشگاه ام‌القری، مکه مکرمه');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.methodNames.UOIF', 'اتحادیه سازمان‌های اسلامی فرانسه (UOIF)');
insert into i18n_bundles (locale, code, value) values ('fa', 'prayer-time-method-groups.STANDARD.name', 'استاندارد');
insert into i18n_bundles (locale, code, value) values ('fa', 'settings.location.forget-custom-location', 'حذف مکان انتخابی');
insert into i18n_bundles (locale, code, value) values ('fa', 'settings.location.label', 'موقعیت مکانی');
insert into i18n_bundles (locale, code, value) values ('fa', 'settings.location.permission.change-in-browser', 'استفاده از موقعیت مکانی فعلی');
insert into i18n_bundles (locale, code, value) values ('fa', 'settings.location.permission.grant-reason', 'برای تعیین وقت اذان صبح و غروب');
insert into i18n_bundles (locale, code, value) values ('fa', 'settings.location.permission.revoke-blocking', 'لطفاً مسدودسازی را در تنظیمات سایت رفع کنید');
insert into i18n_bundles (locale, code, value) values ('fa', 'settings.location.pick-on-map', 'انتخاب موقعیت روی نقشه');
insert into i18n_bundles (locale, code, value) values ('fa', 'settings.prayer-time-method', 'روش محاسبه اوقات نماز');
insert into i18n_bundles (locale, code, value) values ('fa', 'settings.time-zone', 'منطقه زمانی');
