--liquibase formatted sql
--changeset id:00017 author:edwgiz@zohomail.eu

insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.current-month', 'বর্তমান মাস');
insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.event.fajr', 'ফজর');
insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.event.sunset', 'সূর্যাস্ত');
insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.monthNames[1]', 'মুহাররাম');
insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.monthNames[2]', 'সাফার');
insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.monthNames[3]', 'রবিউল আউয়াল');
insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.monthNames[4]', 'রবিউস সানি');
insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.monthNames[5]', 'জামাদিউল আউয়াল');
insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.monthNames[6]', 'জামাদিউস সানি');
insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.monthNames[7]', 'রজব');
insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.monthNames[8]', 'শাবান');
insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.monthNames[9]', 'রমজান');
insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.monthNames[10]', 'শাওয়াল');
insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.monthNames[11]', 'জিলকদ');
insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.monthNames[12]', 'জিলহজ');
insert into i18n_bundles (locale, code, value) values ('bn', 'calendar.monthNames[0]', '');
insert into i18n_bundles (locale, code, value) values ('bn', 'commons.cancel', 'বাতিল');
insert into i18n_bundles (locale, code, value) values ('bn', 'commons.change', 'পরিবর্তন');
insert into i18n_bundles (locale, code, value) values ('bn', 'commons.forget-custom-location', 'নির্বাচিত অবস্থানটি মুছুন');
insert into i18n_bundles (locale, code, value) values ('bn', 'commons.ok', 'ঠিক আছে');
insert into i18n_bundles (locale, code, value) values ('bn', 'commons.or', 'অথবা');
insert into i18n_bundles (locale, code, value) values ('bn', 'errors.location-access', 'অবস্থান পেতে ত্রুটি:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.head.description', 'তাইয়্যিব সিয়াম ক্যালেন্ডার: সুন্নাহর নির্দেশনা ও প্রমাণিত হিজরি তারিখের আলোকে প্রস্তুতকৃত প্রামাণিক ইসলামিক সিয়ামসূচি।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.head.title', 'ইসলামিক সিয়াম ক্যালেন্ডার');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.ics.calendar.event.hijri-date-label', 'হিজরি');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.ics.calendar.event.summary', 'সিয়াম');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.ics.calendar.name', 'ইসলামিক সিয়াম');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.ics.copy-link-label', 'সাবস্ক্রিপশন লিঙ্ক কপি করুন');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.ics.event-summary', 'সিয়াম');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.ics.hijri-date-label', 'হিজরি');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.ics.label', 'সূচিটি আপনার ক্যালেন্ডারে যোগ করুন');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.ics.link-label', 'ICS ডাউনলোড করুন');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.mcp.copy-link-label', 'MCP লিঙ্ক কপি করুন');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.mcp.label', 'আপনার এআই টুলগুলো সক্ষম করুন');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.generic.ics-title', 'সিয়ামের কারণ');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.generic.reasons[0].cites[0].id', 'fasting-reason-generic-0');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.generic.reasons[0].cites[0].quote', 'আদম সন্তানের প্রতিটি আমল তার নিজের জন্য, কিন্তু সিয়াম আমার জন্য, আর আমিই এর প্রতিদান দেব।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].hadith', '1904');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.obligatory.ics-title', 'ফরজ (আবশ্যিক) সিয়ামের কারণ');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.obligatory.reasons[0].cites[1].quote', 'যে ব্যক্তি ঈমান ও প্রতিদানের আশায় রমজানের সিয়াম পালন করবে, তার পূর্বের গুনাহ ক্ষমা করে দেওয়া হবে।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].hadith', '760');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].hadith', '38');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.obligatory.reasons[0].cites[0].quote', 'ইসলাম পাঁচটি ভিত্তির ওপর প্রতিষ্ঠিত: এই মর্মে সাক্ষ্য দেওয়া যে আল্লাহ ছাড়া কোনো উপাস্য নেই এবং মুহাম্মাদ আল্লাহর রাসূল, নামাজ কায়েম করা, যাকাত আদায় করা, হজ করা এবং রমজানের সিয়াম পালন করা।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].hadith', '16');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].hadith', '8');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.obligatory.reasons[0].id', 'fasting-reason-ramadan');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.obligatory.reasons[0].title', 'রমজান');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.obligatory.title', 'ফরজ');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.ics-title', 'নিষিদ্ধ (হারাম) সিয়ামের কারণ');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].quote', 'তাসরীকের দিনগুলো হলো খাওয়া-দাওয়ার দিন।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].hadith', '1141a');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[1].id', 'fasting-reason-tashriq');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[1].title', 'তাসরীকের দিনগুলো');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].intro', 'আবু উবাইদ (রা.) থেকে বর্ণিত, তিনি বলেন:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].quote', 'আমি উমর (রা.)-এর সাথে ঈদের নামাজে উপস্থিত ছিলাম। তিনি খুতবার আগে নামাজ আদায় করলেন, অতঃপর বললেন: রাসূলুল্লাহ (সা.) এই দুই দিনের সিয়াম থেকে নিষেধ করেছেন। ঈদুল আযহার দিন তোমরা তোমাদের কুরবানির গোশত খাও, আর ঈদুল ফিতরের দিন তোমাদের সিয়াম ভঙ্গের দিন।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].hadith', '1722');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].hadith', '2416');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].intro', 'আবু হুরাইরা (রা.) থেকে বর্ণিত, রাসূলুল্লাহ (সা.) বলেছেন:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].quote', 'দুই দিনের সিয়াম নিষিদ্ধ: ঈদুল ফিতর ও ঈদুল আযহার দিন।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].hadith', '1138');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].hadith', '1993');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-adha', 'ঈদুল আযহা');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-fitr', 'ঈদুল ফিতর');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].id', 'fasting-reason-eid-days');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.reasons[0].title', 'ঈদুল ফিতর ও ঈদুল আযহা');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.prohibiting.title', 'নিষিদ্ধ');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.ics-title', 'নফল (তাতাউওয়া) সিয়ামের কারণ');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[1].cites[0].intro', 'আবু কাতাদা (রা.) থেকে বর্ণিত, রাসূলুল্লাহ (সা.) বলেছেন:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[1].cites[0].quote', 'আমি আল্লাহর কাছে আশা করি যে, আরাফার দিনের সিয়াম পূর্ববর্তী ও পরবর্তী এক বছরের গুনাহ মোচন করবে, এবং আশুরার দিনের সিয়াম পূর্ববর্তী এক বছরের গুনাহ মোচন করবে।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[1].headlines.arafah', 'আরাফার দিন');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[1].headlines.ashura', 'আশুরার দিন');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[1].id', 'fasting-reason-arafah-or-ashura');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[1].title', 'আরাফা ও আশুরার দিন');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[2].cites[0].intro', 'নবী (সা.)-এর কোনো এক সহধর্মিণী (রা.) থেকে বর্ণিত, তিনি বলেন:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[2].cites[0].quote', 'রাসূলুল্লাহ (সা.) জিলহজ মাসের প্রথম নয় দিন, আশুরার দিন এবং প্রতি মাসে তিন দিন সিয়াম পালন করতেন।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].hadith', '2417');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].hadith', '2437');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[2].id', 'fasting-reason-first-9-dhu-al-hijjah');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[2].title', 'জিলহজের প্রথম নয় দিন');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[1].intro', 'আবদুল্লাহ ইবনু আমর ইবনুল আস (রা.) থেকে বর্ণিত, তিনি বলেন: রাসূলুল্লাহ (সা.) আমাকে বলেছেন:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[1].quote', 'তোমার জন্য প্রতি মাসে তিন দিন সিয়াম পালনই যথেষ্ট; কারণ প্রতিটি নেক আমলের দশগুণ প্রতিদান রয়েছে। এভাবে তা পূর্ণ বছরের সিয়ামের সমতুল্য।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].hadith', '1975');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[2].intro', 'আবু কাতাদা (রা.) থেকে বর্ণিত, রাসূলুল্লাহ (সা.) বলেছেন:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[2].quote', 'প্রতি মাসে তিন দিন সিয়াম এবং প্রতি বছর রমজানের সিয়াম—এটিই চিরকালের সিয়াম।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[3].intro', 'রাসূলুল্লাহ (সা.) আবু যার (রা.)-কে বলেছেন:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[3].quote', 'যে ব্যক্তি প্রতি মাসে তিন দিন সিয়াম পালন করবে, তা চিরকালের সিয়ামের সমতুল্য।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].hadith', '1708');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[4].intro', 'জারীর ইবনু আবদুল্লাহ (রা.) থেকে বর্ণিত, নবী (সা.) বলেছেন:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[4].quote', 'প্রতি মাসে তিন দিন সিয়াম পালন করা চিরকালের সিয়ামের সমতুল্য; আর সাদা দিনগুলো (আয়্যামুল বীদ) হলো তেরো, চৌদ্দ ও পনেরো তারিখ।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].hadith', '2420');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[5].intro', 'আবু হুরাইরা (রা.) থেকে বর্ণিত, তিনি বলেন:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[5].quote', 'আমার প্রিয় বন্ধু রাসূলুল্লাহ (সা.) আমাকে তিনটি বিষয়ের অসিয়ত করেছেন: প্রতি মাসে তিন দিন সিয়াম, দুই রাকআত চাশতের নামাজ এবং ঘুমানোর আগে বিতর নামাজ।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].hadith', '1981');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[6].intro', 'আবুদ দারদা (রা.) থেকে বর্ণিত, তিনি বলেন:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[6].quote', 'আমার প্রিয় বন্ধু রাসূলুল্লাহ (সা.) আমাকে তিনটি বিষয়ের অসিয়ত করেছেন, যেগুলো আমি কোনো অবস্থাতেই ছাড়ি না; তিনি আমাকে প্রতি মাসে তিন দিন সিয়ামের অসিয়ত করেছেন।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].hadith', '1433');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[0].intro', 'রাসূলুল্লাহ (সা.) আবু যার (রা.)-কে উপদেশ দিয়েছেন:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[0].quote', 'হে আবু যার! যদি তুমি মাসের কোনো দিন সিয়াম পালন করো, তবে তেরো, চৌদ্দ ও পনেরো তারিখে সিয়াম পালন করো।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].hadith', '761');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].id', 'fasting-reason-white-days');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[3].title', 'সাদা দিনগুলো (আয়্যামুল বীদ)');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[1].intro', 'উসামা ইবনু যায়েদ (রা.) থেকে বর্ণিত, রাসূলুল্লাহ (সা.) বলেছেন:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[1].quote', 'এই দুটি দিনে সমস্ত আমল বিশ্বজগতের রবের সামনে পেশ করা হয়; আমি চাই আমার আমল সিয়ামরত অবস্থায় পেশ করা হোক।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].hadith', '2358');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[2].intro', 'আবু কাতাদা আনসারী (রা.) থেকে বর্ণিত, রাসূলুল্লাহ (সা.)-এর কাছে সোমবারের সিয়াম সম্পর্কে জিজ্ঞাসা করা হলে তিনি বলেন:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[2].quote', 'এটি সেই দিন, যেদিন আমি জন্মগ্রহণ করেছি, এবং যেদিন আমার প্রতি নবুওয়াত দেওয়া হয়েছে বা ওহী নাযিল করা হয়েছে।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].hadith', '1162b');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[3].intro', 'আয়েশা (রা.) থেকে বর্ণিত, তিনি বলেন:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[3].quote', 'নবী (সা.) সোম ও বৃহস্পতিবার সিয়াম পালনের প্রতি যত্নবান ছিলেন।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].hadith', '745');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[0].intro', 'আবু হুরাইরা (রা.) থেকে বর্ণিত, রাসূলুল্লাহ (সা.) বলেছেন:');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[0].quote', 'সোম ও বৃহস্পতিবার আমলগুলো পেশ করা হয়; আমি চাই আমার আমল সিয়ামরত অবস্থায় পেশ করা হোক।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].collection', 'riyadussalihin');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].hadith', '1256');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].hadith', '747');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].headlines.monday', 'সোমবার');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].headlines.thursday', 'বৃহস্পতিবার');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].id', 'fasting-reason-monday-thursday');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[4].title', 'সোম ও বৃহস্পতিবার');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[0].cites[1].quote', 'যে ব্যক্তি রমজানের সিয়াম পালন করবে, অতঃপর শাওয়াল মাসে আরও ছয় দিন সিয়াম পালন করবে, সে যেন চিরকাল সিয়াম পালন করল।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].hadith', '1716');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[0].cites[2].quote', 'যে ব্যক্তি রমজান মাসের সিয়াম পালন করবে এবং এরপর শাওয়াল মাসে ছয় দিন সিয়াম পালন করবে, তা পূর্ণ বছরের সিয়ামের সমতুল্য হবে।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].hadith', '1164');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[0].cites[0].quote', 'যে ব্যক্তি ঈদুল ফিতরের পর ছয় দিন সিয়াম পালন করবে, সে পূর্ণ বছরের সিয়াম সম্পন্ন করল; কারণ যে ব্যক্তি একটি নেক আমল করবে, তার জন্য অনুরূপ দশটি নেক আমলের প্রতিদান রয়েছে।');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].hadith', '1715');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[0].id', 'fasting-reason-shawwal');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.reasons[0].title', 'শাওয়ালের ছয় দিন');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reason-groups.voluntary.title', 'নফল');
insert into i18n_bundles (locale, code, value) values ('bn', 'fasting.reasons-title', 'সিয়ামের কারণসমূহ');
insert into i18n_bundles (locale, code, value) values ('bn', 'footer.attributions.label', 'স্বীকৃতি');
insert into i18n_bundles (locale, code, value) values ('bn', 'footer.contacts.github-ref-description', 'সমস্যা জানানো, নতুন ফিচারের অনুরোধ বা অবদান রাখতে অনুগ্রহ করে GitHub পরিদর্শন করুন।');
insert into i18n_bundles (locale, code, value) values ('bn', 'footer.contacts.label', 'যোগাযোগ');
insert into i18n_bundles (locale, code, value) values ('bn', 'hadith-referencing.collections.abudawud', 'সুনান আবু দাউদ');
insert into i18n_bundles (locale, code, value) values ('bn', 'hadith-referencing.collections.bukhari', 'সহীহ আল-বুখারী');
insert into i18n_bundles (locale, code, value) values ('bn', 'hadith-referencing.collections.ibnmajah', 'সুনান ইবনু মাজাহ');
insert into i18n_bundles (locale, code, value) values ('bn', 'hadith-referencing.collections.muslim', 'সহীহ মুসলিম');
insert into i18n_bundles (locale, code, value) values ('bn', 'hadith-referencing.collections.nasai', 'সুনান আন-নাসাঈ');
insert into i18n_bundles (locale, code, value) values ('bn', 'hadith-referencing.collections.riyadussalihin', 'রিয়াযুস সালিহীন');
insert into i18n_bundles (locale, code, value) values ('bn', 'hadith-referencing.collections.tirmidhi', 'জামি আত-তিরমিযী');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.AUTOMATIC.methodNames.AUTO_BY_LOCATION', 'অবস্থান অনুযায়ী স্বয়ংক্রিয়');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.AUTOMATIC.name', 'স্বয়ংক্রিয়');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.ALGERIA', 'আলজেরিয়া');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.CIL', 'লিসবন ইসলামিক কমিউনিটি');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.DIYANET', 'দিয়ানেত (তুরস্ক)');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.DUBAI', 'দুবাই, সংযুক্ত আরব আমিরাত');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.EGAS', 'মিশরীয় জরিপ কর্তৃপক্ষ');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.GULF', 'উপসাগরীয় অঞ্চল');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.ISNA', 'উত্তর আমেরিকার ইসলামিক সোসাইটি (ISNA)');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.JAKIM', 'জাকিম, মালয়েশিয়া');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.KARACHI', 'ইসলামিক সাইন্সেস বিশ্ববিদ্যালয়, করাচি');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.KEMENAG', 'ধর্ম বিষয়ক মন্ত্রণালয়, ইন্দোনেশিয়া');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.KUWAIT', 'কুয়েত');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.MOROCCO', 'মরক্কো');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.MSC', 'চাঁদ দেখা কমিটি');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.MUIS', 'মাজলিস উগামা ইসলাম সিঙ্গাপুরা (MUIS)');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.MWL', 'মুসলিম ওয়ার্ল্ড লীগ');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.QATAR', 'কাতার');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.SAMR', 'রাশিয়ার মুসলিমদের আধ্যাত্মিক প্রশাসন');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.SHIA_QUM', 'শিয়া ইসনা আশারিয়া, কুম');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.TEHRAN', 'ভূপদার্থবিজ্ঞান ইনস্টিটিউট, তেহরান বিশ্ববিদ্যালয়');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.TUNISIA', 'তিউনিসিয়া');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.UMM_AL_QURA', 'উম্মুল কুরা বিশ্ববিদ্যালয়, মক্কা মুকাররমা');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.methodNames.UOIF', 'ফ্রান্সের ইসলামিক সংগঠনসমূহের ইউনিয়ন (UOIF)');
insert into i18n_bundles (locale, code, value) values ('bn', 'prayer-time-method-groups.STANDARD.name', 'প্রমিত');
insert into i18n_bundles (locale, code, value) values ('bn', 'settings.location.forget-custom-location', 'নির্বাচিত অবস্থানটি মুছুন');
insert into i18n_bundles (locale, code, value) values ('bn', 'settings.location.label', 'অবস্থান');
insert into i18n_bundles (locale, code, value) values ('bn', 'settings.location.permission.change-in-browser', 'বর্তমান অবস্থান ব্যবহার করুন');
insert into i18n_bundles (locale, code, value) values ('bn', 'settings.location.permission.grant-reason', 'ফজর ও সূর্যাস্তের সময় জানার জন্য');
insert into i18n_bundles (locale, code, value) values ('bn', 'settings.location.permission.revoke-blocking', 'অনুগ্রহ করে সাইট সেটিংসে অবরোধ প্রত্যাহার করুন');
insert into i18n_bundles (locale, code, value) values ('bn', 'settings.location.pick-on-map', 'মানচিত্রে অবস্থান নির্বাচন করুন');
insert into i18n_bundles (locale, code, value) values ('bn', 'settings.prayer-time-method', 'নামাজের সময় গণনার পদ্ধতি');
insert into i18n_bundles (locale, code, value) values ('bn', 'settings.time-zone', 'টাইম জোন');
