--liquibase formatted sql
--changeset id:00025 author:edwgiz@zohomail.eu

insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.current-month', 'Текущий месяц');
insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.event.fajr', 'фаджр');
insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.event.sunset', 'закат');
insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.monthNames[1]', 'Мухаррам');
insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.monthNames[2]', 'Сафар');
insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.monthNames[3]', 'Раби аль-авваль');
insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.monthNames[4]', 'Раби ас-сани');
insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.monthNames[5]', 'Джумада аль-уля');
insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.monthNames[6]', 'Джумада ас-сания');
insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.monthNames[7]', 'Раджаб');
insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.monthNames[8]', 'Шаабан');
insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.monthNames[9]', 'Рамадан');
insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.monthNames[10]', 'Шавваль');
insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.monthNames[11]', 'Зуль-каада');
insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.monthNames[12]', 'Зуль-хиджа');
insert into i18n_bundles (locale, code, value) values ('ru', 'calendar.monthNames[0]', '');
insert into i18n_bundles (locale, code, value) values ('ru', 'commons.cancel', 'Отмена');
insert into i18n_bundles (locale, code, value) values ('ru', 'commons.change', 'Изменить');
insert into i18n_bundles (locale, code, value) values ('ru', 'commons.forget-custom-location', 'Забыть выбранное место');
insert into i18n_bundles (locale, code, value) values ('ru', 'commons.ok', 'ОК');
insert into i18n_bundles (locale, code, value) values ('ru', 'commons.or', 'или');
insert into i18n_bundles (locale, code, value) values ('ru', 'errors.location-access', 'Ошибка при получении местоположения:');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.head.description', 'Календарь поста «Таййиб»: достоверные исламские расписания поста, соответствующие Сунне и проверенным датам по хиджре.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.head.title', 'Исламский календарь поста');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.ics.calendar.event.hijri-date-label', 'Хиджра');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.ics.calendar.event.summary', 'Пост');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.ics.calendar.name', 'Исламский пост');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.ics.copy-link-label', 'Скопировать ссылку на подписку');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.ics.event-summary', 'Пост');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.ics.hijri-date-label', 'Хиджра');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.ics.label', 'Добавить расписание в календарь');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.ics.link-label', 'Скачать ICS');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.mcp.copy-link-label', 'Скопировать ссылку MCP');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.mcp.label', 'Расширьте возможности ваших ИИ-инструментов');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.generic.ics-title', 'Категория поста');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.generic.reasons[0].cites[0].id', 'fasting-reason-generic-0');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.generic.reasons[0].cites[0].quote', 'Аллах сказал: «Любое деяние сына Адама — для него, кроме поста. Поистине, он — для Меня, и Я воздам за него».');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].hadith', '1904');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.obligatory.ics-title', 'Обязательный (ваджиб) пост');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.obligatory.reasons[0].cites[1].quote', 'Тому, кто постился в рамадане с верой и надеждой на награду, простятся его прежние грехи.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].hadith', '760');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].hadith', '38');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.obligatory.reasons[0].cites[0].quote', 'Ислам утверждается на пяти [столпах]: свидетельстве о том, что нет божества, достойного поклонения, кроме Аллаха, и что Мухаммад — Посланник Аллаха; совершении молитвы; выплате закята; совершении хаджа и посте в рамадане.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].hadith', '16');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].hadith', '8');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.obligatory.reasons[0].id', 'fasting-reason-ramadan');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.obligatory.reasons[0].title', 'Рамадан');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.obligatory.title', 'Обязательный');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.ics-title', 'Запрещённый (харам) пост');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].quote', 'Дни ташрика — дни еды и питья.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].hadith', '1141a');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[1].id', 'fasting-reason-tashriq');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[1].title', 'Дни ташрика');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].intro', 'Абу Убайд (да будет доволен им Аллах) передал:');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].quote', 'Я присутствовал на праздничной молитве вместе с Умаром. Он начал с молитвы перед проповедью, а затем сказал: «Посланник Аллаха, да благословит его Аллах и приветствует, запретил пост в эти два дня. Что касается дня жертвоприношения, то вы едите мясо ваших жертвенных животных, а что касается дня разговения, то вы прекращаете ваш пост».');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].hadith', '1722');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].hadith', '2416');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].intro', 'Абу Хурайра (да будет доволен им Аллах) передал:');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].quote', 'Посланник Аллаха, да благословит его Аллах и приветствует, запретил пост в два дня: в день жертвоприношения и в день разговения.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].hadith', '1138');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].hadith', '1993');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-adha', 'Ид аль-Адха');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-fitr', 'Ид аль-Фитр');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].id', 'fasting-reason-eid-days');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.reasons[0].title', 'Ид аль-Фитр и Ид аль-Адха');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.prohibiting.title', 'Запрещённый');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.ics-title', 'Добровольный (татавву) пост');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[1].cites[0].intro', 'Абу Катада (да будет доволен им Аллах) передал, что Посланник Аллаха, да благословит его Аллах и приветствует, сказал:');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[1].cites[0].quote', 'Пост в день Арафа — я надеюсь, что Аллах сделает его искуплением грехов за прошедший и будущий год, а пост в день Ашура — искуплением грехов за прошедший год.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[1].headlines.arafah', 'День Арафа');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[1].headlines.ashura', 'День Ашура');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[1].id', 'fasting-reason-arafah-or-ashura');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[1].title', 'День Арафа и день Ашура');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[2].cites[0].intro', 'Одна из жён Пророка (да будет доволен ею Аллах) сказала:');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[2].cites[0].quote', 'Посланник Аллаха, да благословит его Аллах и приветствует, обычно постился в первые девять дней зуль-хиджи, в день Ашура и три дня каждого месяца.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].hadith', '2417');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].hadith', '2437');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[2].id', 'fasting-reason-first-9-dhu-al-hijjah');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[2].title', 'Первые девять дней зуль-хиджи');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[1].intro', 'Абдуллах ибн Амр ибн аль-Ас (да будет доволен им Аллах) передал:');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[1].quote', 'Достаточно тебе поститься три дня каждый месяц, ибо за доброе дело воздаётся десятикратно, и это будет подобно посту в течение всего года.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].hadith', '1975');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[2].intro', 'Абу Катада (да будет доволен им Аллах) передал, что Посланник Аллаха, да благословит его Аллах и приветствует, сказал:');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[2].quote', 'Пост трёх дней каждого месяца и пост в рамадане каждый год — это постоянный пост.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[3].intro', 'Посланник Аллаха, да благословит его Аллах и приветствует, сказал Абу Зарру:');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[3].quote', 'Тот, кто постится три дня каждый месяц, подобен постящемуся всю жизнь.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].hadith', '1708');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[4].intro', 'Джарир ибн Абдуллах (да будет доволен им Аллах) передал, что Пророк, да благословит его Аллах и приветствует, сказал:');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[4].quote', 'Пост трёх дней каждого месяца — пост длиной в жизнь; это белые дни: утро тринадцатого, четырнадцатого и пятнадцатого.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].hadith', '2420');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[5].intro', 'Абу Хурайра (да будет доволен им Аллах) сказал:');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[5].quote', 'Мой близкий друг [Пророк], да благословит его Аллах и приветствует, завещал мне три вещи: поститься три дня каждый месяц, совершать два ракаата молитвы ад-духа и совершать витр перед сном.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].hadith', '1981');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[6].intro', 'Абу ад-Дарда (да будет доволен им Аллах) сказал:');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[6].quote', 'Мой близкий друг [Пророк], да благословит его Аллах и приветствует, наказал мне три вещи, которые я никогда не оставлю: он наказал мне поститься три дня каждый месяц.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].hadith', '1433');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[0].intro', 'Пророк Мухаммад, да благословит его Аллах и приветствует, сказал Абу Зарру (да будет доволен им Аллах):');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[0].quote', 'Если ты постишься [хотя бы] три дня в месяц, то постись тринадцатого, четырнадцатого и пятнадцатого.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].hadith', '761');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].id', 'fasting-reason-white-days');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[3].title', 'Белые дни');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[1].intro', 'Усама ибн Зайд (да будет доволен им Аллах) передал, что Посланник Аллаха, да благословит его Аллах и приветствует, сказал:');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[1].quote', 'Это два дня, в которые деяния представляются Господу миров, и я люблю, чтобы мои деяния представлялись, когда я пощусь.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].hadith', '2358');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[2].intro', 'Абу Катада аль-Ансари (да будет доволен им Аллах) спросил Пророка, да благословит его Аллах и приветствует, о посте в понедельник, и он сказал:');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[2].quote', 'Это день, в который я родился и в который я был послан [пророком] — или мне было ниспослано [Откровение].');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].hadith', '1162b');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[3].intro', 'Аиша (да будет доволен ею Аллах) сказала:');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[3].quote', 'Пророк, да благословит его Аллах и приветствует, старался поститься по понедельникам и четвергам.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].hadith', '745');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[0].intro', 'Абу Хурайра (да будет доволен им Аллах) передал:');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[0].quote', 'Деяния представляются [Аллаху] по понедельникам и четвергам, и я люблю, чтобы мои деяния представлялись, когда я пощусь.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].collection', 'riyadussalihin');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].hadith', '1256');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].hadith', '747');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].headlines.monday', 'Понедельник');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].headlines.thursday', 'Четверг');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].id', 'fasting-reason-monday-thursday');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[4].title', 'Понедельник и четверг');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[0].cites[1].quote', 'Кто постился в рамадане, а затем добавил к нему шесть дней шавваля, тот словно постился всю жизнь.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].hadith', '1716');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[0].cites[2].quote', 'Кто постился в месяце рамадане, а затем постился шесть дней в месяце шавваль, тот словно постился весь год.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].hadith', '1164');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[0].cites[0].quote', 'Кто постился шесть дней после Ид аль-Фитра, тот завершил год, ибо тот, кто совершит доброе дело, получит десять подобных ему.');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].hadith', '1715');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[0].id', 'fasting-reason-shawwal');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.reasons[0].title', 'Шесть дней шавваля');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reason-groups.voluntary.title', 'Добровольный');
insert into i18n_bundles (locale, code, value) values ('ru', 'fasting.reasons-title', 'Категории поста');
insert into i18n_bundles (locale, code, value) values ('ru', 'footer.attributions.label', 'Благодарности');
insert into i18n_bundles (locale, code, value) values ('ru', 'footer.contacts.github-ref-description', 'Посетите GitHub, чтобы сообщить об ошибке, предложить новую функцию или внести вклад.');
insert into i18n_bundles (locale, code, value) values ('ru', 'footer.contacts.label', 'Контакты');
insert into i18n_bundles (locale, code, value) values ('ru', 'hadith-referencing.collections.abudawud', 'Сунан Абу Дауда');
insert into i18n_bundles (locale, code, value) values ('ru', 'hadith-referencing.collections.bukhari', 'Сахих аль-Бухари');
insert into i18n_bundles (locale, code, value) values ('ru', 'hadith-referencing.collections.ibnmajah', 'Сунан Ибн Маджаха');
insert into i18n_bundles (locale, code, value) values ('ru', 'hadith-referencing.collections.muslim', 'Сахих Муслим');
insert into i18n_bundles (locale, code, value) values ('ru', 'hadith-referencing.collections.nasai', 'Сунан ан-Насаи');
insert into i18n_bundles (locale, code, value) values ('ru', 'hadith-referencing.collections.riyadussalihin', 'Рияд ас-салихин');
insert into i18n_bundles (locale, code, value) values ('ru', 'hadith-referencing.collections.tirmidhi', 'Джами ат-Тирмизи');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.AUTOMATIC.methodNames.AUTO_BY_LOCATION', 'Автоматически по местоположению');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.AUTOMATIC.name', 'Автоматически');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.ALGERIA', 'Алжир');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.CIL', 'Исламская община Лиссабона');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.DIYANET', 'Дианет (Турция)');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.DUBAI', 'Дубай, ОАЭ');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.EGAS', 'Главное управление геодезии Египта');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.GULF', 'Регион Персидского залива');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.ISNA', 'Исламское общество Северной Америки (ISNA)');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.JAKIM', 'ДЖАКИМ, Малайзия');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.KARACHI', 'Университет исламских наук, Карачи');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.KEMENAG', 'Министерство по делам религий, Индонезия');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.KUWAIT', 'Кувейт');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.MOROCCO', 'Марокко');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.MSC', 'Комитет наблюдения за новолунием');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.MUIS', 'Совет по исламским делам Сингапура (MUIS)');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.MWL', 'Всемирная мусульманская лига');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.QATAR', 'Катар');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.SAMR', 'Духовное управление мусульман России');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.SHIA_QUM', 'Шииты-двунадесятники (Исна Ашария), Кум');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.TEHRAN', 'Институт геофизики Тегеранского университета');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.TUNISIA', 'Тунис');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.UMM_AL_QURA', 'Университет Умм аль-Кура, Мекка');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.methodNames.UOIF', 'Союз исламских организаций Франции (UOIF)');
insert into i18n_bundles (locale, code, value) values ('ru', 'prayer-time-method-groups.STANDARD.name', 'Стандартные');
insert into i18n_bundles (locale, code, value) values ('ru', 'settings.location.forget-custom-location', 'Забыть выбранное место');
insert into i18n_bundles (locale, code, value) values ('ru', 'settings.location.label', 'Местоположение');
insert into i18n_bundles (locale, code, value) values ('ru', 'settings.location.permission.change-in-browser', 'Использовать текущее местоположение');
insert into i18n_bundles (locale, code, value) values ('ru', 'settings.location.permission.grant-reason', 'Для времени фаджра и заката');
insert into i18n_bundles (locale, code, value) values ('ru', 'settings.location.permission.revoke-blocking', 'Разрешите доступ в настройках сайта');
insert into i18n_bundles (locale, code, value) values ('ru', 'settings.location.pick-on-map', 'Выбрать местоположение на карте');
insert into i18n_bundles (locale, code, value) values ('ru', 'settings.prayer-time-method', 'Метод расчёта времени молитвы');
insert into i18n_bundles (locale, code, value) values ('ru', 'settings.time-zone', 'Часовой пояс');
