--liquibase formatted sql
--changeset id:00028 author:edwgiz@zohomail.eu

insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.current-month', 'Joriy oy');
insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.event.fajr', 'Bomdod');
insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.event.sunset', 'Quyosh botishi');
insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.monthNames[1]', 'Muharram');
insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.monthNames[2]', 'Safar');
insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.monthNames[3]', 'Rabiʼul-avval');
insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.monthNames[4]', 'Rabiʼul-oxir');
insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.monthNames[5]', 'Jumodil-ulo');
insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.monthNames[6]', 'Jumodil-oxira');
insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.monthNames[7]', 'Rajab');
insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.monthNames[8]', 'Shaʼbon');
insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.monthNames[9]', 'Ramazon');
insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.monthNames[10]', 'Shavvol');
insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.monthNames[11]', 'Zul-qaʼda');
insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.monthNames[12]', 'Zul-hijja');
insert into i18n_bundles (locale, code, value) values ('uz', 'calendar.monthNames[0]', '');
insert into i18n_bundles (locale, code, value) values ('uz', 'commons.cancel', 'Bekor qilish');
insert into i18n_bundles (locale, code, value) values ('uz', 'commons.change', 'Oʻzgartirish');
insert into i18n_bundles (locale, code, value) values ('uz', 'commons.forget-custom-location', 'Tanlangan joydan voz kechish');
insert into i18n_bundles (locale, code, value) values ('uz', 'commons.ok', 'OK');
insert into i18n_bundles (locale, code, value) values ('uz', 'commons.or', 'yoki');
insert into i18n_bundles (locale, code, value) values ('uz', 'errors.location-access', 'Joylashuvni olishda xato:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.head.description', 'Tayyib roʻza kalendari: Sunna amallariga va tasdiqlangan hijriy sanalarga asoslangan ishonchli islomiy roʻza jadvallari.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.head.title', 'Islomiy roʻza kalendari');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.ics.calendar.event.hijri-date-label', 'Hijriy');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.ics.calendar.event.summary', 'Roʻza');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.ics.calendar.name', 'Islomiy roʻza');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.ics.copy-link-label', 'obuna havolasini nusxalash');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.ics.event-summary', 'Roʻza');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.ics.hijri-date-label', 'Hijriy');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.ics.label', 'Jadvalni kalendaringizga qoʻshing');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.ics.link-label', 'ICS yuklab olish');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.mcp.copy-link-label', 'MCP havolasini nusxalash');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.mcp.label', 'Sunʼiy intellekt vositalaringizni kuchaytiring');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.generic.ics-title', 'Roʻza sababi');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.generic.reasons[0].cites[0].id', 'fasting-reason-generic-0');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.generic.reasons[0].cites[0].quote', 'Odam farzandining barcha amallari oʻzi uchundir, roʻza bundan mustasno; u Men uchundir, unga mukofotni Men beraman.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].hadith', '1904');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.obligatory.ics-title', 'Farz (vojib) roʻza sababi');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.obligatory.reasons[0].cites[1].quote', 'Kim iymon bilan va savab umidida Ramazon roʻzasini tutsa, uning oʻtgan gunohlari kechiriladi.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].hadith', '760');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].hadith', '38');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.obligatory.reasons[0].cites[0].quote', 'Islom besh ustun ustiga qurilgan: Allohdan oʻzga ibodatga loyiq iloh yoʻqligiga va Muhammad Allohning Rasuli ekanligiga shohadat berish, namozni toʻkis ado etish, zakot berish, Haj qilish va Ramazon roʻzasini tutish.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].hadith', '16');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].hadith', '8');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.obligatory.reasons[0].id', 'fasting-reason-ramadan');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.obligatory.reasons[0].title', 'Ramazon');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.obligatory.title', 'Farz');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.ics-title', 'Harom (taqiqlangan) roʻza sababi');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].quote', 'Tashriq kunlari yeyish va ichish kunlaridir.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].hadith', '1141a');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[1].id', 'fasting-reason-tashriq');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[1].title', 'Tashriq kunlari');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].intro', 'Abu Ubayd (r.a.) rivoyat qiladi:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].quote', 'Men Umar (r.a.) bilan hayit namozida ishtirok etdim. U xutbadan oldin namoz oʻqidi, soʻngra dedi: Allohning Rasuli (s.a.v.) bu ikki kunda roʻza tutishni taqiqlaganlar. Qurbon hayiti kuni qurbonlik hayvonlaringizning goʻshtini yeysizlar, Fitriy hayit kuni esa roʻzangizni ochasizlar.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].hadith', '1722');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].hadith', '2416');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].intro', 'Abu Hurayra (r.a.) rivoyat qiladi:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].quote', 'Ikki kunda roʻza tutish taqiqlangan: Fitriy hayit kuni va Qurbon hayiti kuni.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].hadith', '1138');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].hadith', '1993');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-adha', 'Qurbon hayiti');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-fitr', 'Fitriy hayit');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].id', 'fasting-reason-eid-days');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.reasons[0].title', 'Fitriy hayit va Qurbon hayiti');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.prohibiting.title', 'Taqiqlangan');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.ics-title', 'Nafl (tatavvuʼ) roʻza sababi');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[1].cites[0].intro', 'Abu Qatoda (r.a.) Allohning Rasuli Muhammad (s.a.v.) shunday deganlarini rivoyat qiladi:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[1].cites[0].quote', 'Men Allohdan umid qilamanki, Arafah kunidagi roʻza oʻtgan va kelgusi yil gunohlariga kafforat boʻladi; Ashuro kunidagi roʻza esa oʻtgan yil gunohlariga kafforat boʻladi.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[1].headlines.arafah', 'Arafah kuni');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[1].headlines.ashura', 'Ashuro kuni');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[1].id', 'fasting-reason-arafah-or-ashura');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[1].title', 'Arafah va Ashuro kunlari');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[2].cites[0].intro', 'Paygʻambar Muhammad (s.a.v.)ning ayollaridan biri (r.a.) shunday deganlar:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[2].cites[0].quote', 'Allohning Rasuli Muhammad (s.a.v.) Zul-hijja oyining dastlabki toʻqqiz kunida, Ashuro kunida va har oyda uch kun roʻza tutar edilar…');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].hadith', '2417');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].hadith', '2437');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[2].id', 'fasting-reason-first-9-dhu-al-hijjah');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[2].title', 'Zul-hijja oyining dastlabki toʻqqiz kuni');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[1].intro', 'Abdulloh ibn Amr ibn al-Os (r.a.) rivoyat qiladi:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[1].quote', 'Oyiga uch kun roʻza tutish kifoya qiladi; chunki yaxshilik uchun oʻn barobar savob beriladi, shu sababli bu butun yil roʻzasiga oʻxshaydi.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].hadith', '1975');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[2].intro', 'Abu Qatoda (r.a.) Allohning Rasuli (s.a.v.) shunday deganlarini rivoyat qiladi:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[2].quote', 'Har oyda uch kun roʻza tutish va har yili Ramazon roʻzasi tutish — doimiy roʻzadir.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[3].intro', 'Allohning Rasuli Abu Zarr (r.a.)ga shunday deganlar:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[3].quote', 'Har oyda uch kun roʻza tutish butun umr roʻza tutgandekdir.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].hadith', '1708');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[4].intro', 'Jarir ibn Abdulloh (r.a.)dan rivoyat qilinganki, Paygʻambar (s.a.v.) shunday deganlar:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[4].quote', 'Har oyda uch kun roʻza tutish butun umr roʻza tutgandekdir; bu yorqin kunlar — oyning oʻn uchinchi, oʻn toʻrtinchi va oʻn beshinchi kunlaridir.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].hadith', '2420');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[5].intro', 'Abu Hurayra (r.a.) rivoyat qiladi:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[5].quote', 'Mening yaqin doʻstim (Paygʻambar Muhammad (s.a.v.)) menga uch amalni vasayat qildilar: har oyda uch kun roʻza tutishni, Duha namozidan ikki rakʼat oʻqishni va uxlashdan oldin Vitir namozini oʻqishni.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].hadith', '1981');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[6].intro', 'Abu Dardo (r.a.) rivoyat qiladi:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[6].quote', 'Mening doʻstim (Paygʻambar (s.a.v.)) menga uch amalni vasayat qildilar, men ularni hech qachon tark etmayman; menga har oyda uch kun roʻza tutishni buyurdilar.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].hadith', '1433');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[0].intro', 'Paygʻambar Muhammad (s.a.v.) Abu Zarr (r.a.)ga shunday nasihat qilganlar:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[0].quote', 'Agar oyning bir qismida roʻza tutsangiz, oʻn uchinchi, oʻn toʻrtinchi va oʻn beshinchi kunlarni tuting.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].hadith', '761');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].id', 'fasting-reason-white-days');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[3].title', 'Oq kunlar');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[1].intro', 'Usoma ibn Zayd (r.a.) Allohning Rasuli (s.a.v.) shunday deganlarini rivoyat qiladi:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[1].quote', 'Bu ikki kun — amallar Olamlar Rabbiga arz qilinadigan kunlardir; men amallarim roʻza holatimda arz qilinishini yaxshi koʻraman.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].hadith', '2358');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[2].intro', 'Abu Qatoda al-Ansoriy (r.a.) Paygʻambardan (s.a.v.) dushanba kuni roʻza tutish haqida soʻradi, U zot shunday dedilar:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[2].quote', 'Bu men tugʻilgan kun, menga paygʻambarlik berilgan yoki vahiy nozil qilingan kundir.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].hadith', '1162b');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[3].intro', 'Oisha (r.a.) rivoyat qiladi:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[3].quote', 'Paygʻambar (s.a.v.) dushanba va payshanba kunlari roʻza tutishga alohida eʼtibor berar edilar.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].hadith', '745');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[0].intro', 'Bu soʻz Abu Hurayra (r.a.) tomonidan rivoyat qilingan:');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[0].quote', 'Amallar dushanba va payshanba kunlari arz qilinadi; men amallarim roʻza holatimda arz qilinishini yaxshi koʻraman.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].collection', 'riyadussalihin');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].hadith', '1256');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].hadith', '747');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].headlines.monday', 'Dushanba');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].headlines.thursday', 'Payshanba');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].id', 'fasting-reason-monday-thursday');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[4].title', 'Dushanba va payshanba');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[0].cites[1].quote', 'Kim Ramazon roʻzasini tutib, unga Shavval oyidan olti kun qoʻshsa, butun umr roʻza tutgandek boʻladi.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].hadith', '1716');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[0].cites[2].quote', 'Kim Ramazon oyini roʻza tutib, unga Shavval oyida olti kun roʻza qoʻshsa, butun yil roʻza tutgandek boʻladi.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].hadith', '1164');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[0].cites[0].quote', 'Kim Fitriy hayitdan keyin olti kun roʻza tutsa, yilni tamomlagan boʻladi; chunki kim yaxshilik qilsa, unga oʻn barobar savob beriladi.');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].hadith', '1715');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[0].id', 'fasting-reason-shawwal');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.reasons[0].title', 'Shavval oyining olti kuni');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reason-groups.voluntary.title', 'Nafl');
insert into i18n_bundles (locale, code, value) values ('uz', 'fasting.reasons-title', 'Roʻza sabablari');
insert into i18n_bundles (locale, code, value) values ('uz', 'footer.attributions.label', 'Mualliflar');
insert into i18n_bundles (locale, code, value) values ('uz', 'footer.contacts.github-ref-description', 'Xatolar, funksional soʻrovlar yoki hissa qoʻshish uchun GitHubga tashrif buyuring.');
insert into i18n_bundles (locale, code, value) values ('uz', 'footer.contacts.label', 'Aloqa');
insert into i18n_bundles (locale, code, value) values ('uz', 'hadith-referencing.collections.abudawud', 'Sunan Abu Dovud');
insert into i18n_bundles (locale, code, value) values ('uz', 'hadith-referencing.collections.bukhari', 'Sahih al-Buxoriy');
insert into i18n_bundles (locale, code, value) values ('uz', 'hadith-referencing.collections.ibnmajah', 'Sunan Ibn Moja');
insert into i18n_bundles (locale, code, value) values ('uz', 'hadith-referencing.collections.muslim', 'Sahih Muslim');
insert into i18n_bundles (locale, code, value) values ('uz', 'hadith-referencing.collections.nasai', 'Sunan an-Nasoiy');
insert into i18n_bundles (locale, code, value) values ('uz', 'hadith-referencing.collections.riyadussalihin', 'Riyoz as-Solihin');
insert into i18n_bundles (locale, code, value) values ('uz', 'hadith-referencing.collections.tirmidhi', 'Jomiʼ at-Termiziy');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.AUTOMATIC.methodNames.AUTO_BY_LOCATION', 'Joylashuvga qarab avtomatik');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.AUTOMATIC.name', 'Avtomatik');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.ALGERIA', 'Jazoir');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.CIL', 'Lissabon islom jamiyati');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.DIYANET', 'Diyanet (Turkiya)');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.DUBAI', 'Dubay, BAA');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.EGAS', 'Misr Umumiy geodeziya boshqarmasi');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.GULF', 'Koʻrfaz mintaqasi');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.ISNA', 'Shimoliy Amerika islom jamiyati (ISNA)');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.JAKIM', 'JAKIM, Malayziya');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.KARACHI', 'Islom fanlari universiteti, Karachi');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.KEMENAG', 'Diniy ishlar vazirligi, Indoneziya');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.KUWAIT', 'Quvayt');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.MOROCCO', 'Marokash');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.MSC', 'Hilol koʻrish qoʻmitasi');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.MUIS', 'Singapur islom kengashi (MUIS)');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.MWL', 'Islom olami ligasi');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.QATAR', 'Qatar');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.SAMR', 'Musulmonlar diniy boshqarmasi, Rossiya');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.SHIA_QUM', 'Shia (oʻn ikki imom), Qum');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.TEHRAN', 'Geofizika instituti, Tehron universiteti');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.TUNISIA', 'Tunis');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.UMM_AL_QURA', 'Umm al-Qura universiteti, Makka');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.methodNames.UOIF', 'Fransiya islom tashkilotlari uyushmasi (UOIF)');
insert into i18n_bundles (locale, code, value) values ('uz', 'prayer-time-method-groups.STANDARD.name', 'Standart');
insert into i18n_bundles (locale, code, value) values ('uz', 'settings.location.forget-custom-location', 'Tanlangan joydan voz kechish');
insert into i18n_bundles (locale, code, value) values ('uz', 'settings.location.label', 'Joylashuv');
insert into i18n_bundles (locale, code, value) values ('uz', 'settings.location.permission.change-in-browser', 'Joriy joylashuvdan foydalanish');
insert into i18n_bundles (locale, code, value) values ('uz', 'settings.location.permission.grant-reason', 'Bomdod va quyosh botishi vaqtlari uchun');
insert into i18n_bundles (locale, code, value) values ('uz', 'settings.location.permission.revoke-blocking', 'sayt sozlamalarida bloklashni bekor qiling');
insert into i18n_bundles (locale, code, value) values ('uz', 'settings.location.pick-on-map', 'Xaritadan joylashuvni tanlang');
insert into i18n_bundles (locale, code, value) values ('uz', 'settings.prayer-time-method', 'Namoz vaqtlarini hisoblash usuli');
insert into i18n_bundles (locale, code, value) values ('uz', 'settings.time-zone', 'Vaqt mintaqasi');
