--liquibase formatted sql
--changeset id:00027 author:edwgiz@zohomail.eu

insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.current-month', 'موجودہ مہینہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.event.fajr', 'نمازِ فجر');
insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.event.sunset', 'غروبِ آفتاب');
insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.monthNames[1]', 'محرم');
insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.monthNames[2]', 'صفر');
insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.monthNames[3]', 'ربیع الاول');
insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.monthNames[4]', 'ربیع الثانی');
insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.monthNames[5]', 'جمادی الاول');
insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.monthNames[6]', 'جمادی الثانی');
insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.monthNames[7]', 'رجب');
insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.monthNames[8]', 'شعبان');
insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.monthNames[9]', 'رمضان');
insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.monthNames[10]', 'شوال');
insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.monthNames[11]', 'ذوالقعدہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.monthNames[12]', 'ذوالحجہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'calendar.monthNames[0]', '');
insert into i18n_bundles (locale, code, value) values ('ur', 'commons.cancel', 'منسوخ کریں');
insert into i18n_bundles (locale, code, value) values ('ur', 'commons.change', 'تبدیل کریں');
insert into i18n_bundles (locale, code, value) values ('ur', 'commons.forget-custom-location', 'منتخب مقام ہٹائیں');
insert into i18n_bundles (locale, code, value) values ('ur', 'commons.ok', 'ٹھیک ہے');
insert into i18n_bundles (locale, code, value) values ('ur', 'commons.or', 'یا');
insert into i18n_bundles (locale, code, value) values ('ur', 'errors.location-access', 'مقام حاصل کرنے میں خرابی:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.head.description', 'طیب روزہ کیلنڈر: سنتِ نبوی ﷺ اور تصدیق شدہ ہجری تاریخوں کے مطابق مستند اسلامی روزوں کے شیڈول۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.head.title', 'اسلامی روزہ کیلنڈر');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.ics.calendar.event.hijri-date-label', 'ہجری');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.ics.calendar.event.summary', 'روزہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.ics.calendar.name', 'اسلامی روزے');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.ics.copy-link-label', 'سبسکرپشن لنک کاپی کریں');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.ics.event-summary', 'روزہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.ics.hijri-date-label', 'ہجری');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.ics.label', 'شیڈول اپنے کیلنڈر میں شامل کریں');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.ics.link-label', 'ICS ڈاؤن لوڈ کریں');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.mcp.copy-link-label', 'MCP لنک کاپی کریں');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.mcp.label', 'اپنے AI ٹولز کو فعال کریں');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.generic.ics-title', 'روزے کی وجہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.generic.reasons[0].cites[0].id', 'fasting-reason-generic-0');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.generic.reasons[0].cites[0].quote', 'اللہ تعالیٰ فرماتے ہیں: ابنِ آدم کا ہر عمل اس کے لیے ہے، سوائے روزے کے؛ کیونکہ وہ میرے لیے ہے، اور اس کا اجر میں خود دوں گا۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].hadith', '1904');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.obligatory.ics-title', 'فرض (واجب) روزے کی وجہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.obligatory.reasons[0].cites[1].quote', 'جس نے رمضان کے روزے ایمان اور ثواب کی امید سے رکھے، اس کے پچھلے گناہ معاف کر دیے جائیں گے۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].hadith', '760');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].hadith', '38');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.obligatory.reasons[0].cites[0].quote', 'اسلام کی بنیاد پانچ چیزوں پر ہے: اس بات کی گواہی کہ اللہ کے سوا کوئی معبود نہیں اور محمد ﷺ اللہ کے رسول ہیں، نماز قائم کرنا، زکوٰۃ ادا کرنا، حج کرنا اور رمضان کے روزے رکھنا۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].hadith', '16');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].hadith', '8');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.obligatory.reasons[0].id', 'fasting-reason-ramadan');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.obligatory.reasons[0].title', 'رمضان');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.obligatory.title', 'فرض');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.ics-title', 'ممنوع (حرام) روزے کی وجہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].quote', 'ایامِ تشریق کھانے پینے کے دن ہیں۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].hadith', '1141a');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[1].id', 'fasting-reason-tashriq');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[1].title', 'ایامِ تشریق');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].intro', 'ابو عبید رضی اللہ عنہ بیان کرتے ہیں:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].quote', 'میں عمر رضی اللہ عنہ کے ساتھ عید کے دن حاضر ہوا؛ انہوں نے خطبے سے پہلے نماز پڑھی، پھر فرمایا: رسول اللہ ﷺ نے ان دو دنوں کے روزے سے منع فرمایا ہے۔ عید الاضحی کے دن تم اپنی قربانیوں کے گوشت کھاتے ہو، اور عید الفطر کے دن تم اپنے روزے افطار کرتے ہو۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].hadith', '1722');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].hadith', '2416');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].intro', 'ابو ہریرہ رضی اللہ عنہ روایت کرتے ہیں:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].quote', 'دو دنوں کے روزے ممنوع ہیں: عید الفطر اور عید الاضحی کے دن کا روزہ۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].hadith', '1138');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].hadith', '1993');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-adha', 'عید الاضحی');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-fitr', 'عید الفطر');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].id', 'fasting-reason-eid-days');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.reasons[0].title', 'عید الفطر اور عید الاضحی');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.prohibiting.title', 'ممنوع');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.ics-title', 'نفل روزے کی وجہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[1].cites[0].intro', 'ابو قتادہ رضی اللہ عنہ روایت کرتے ہیں کہ رسول اللہ ﷺ نے فرمایا:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[1].cites[0].quote', 'میں اللہ تعالیٰ سے امید رکھتا ہوں کہ یومِ عرفہ کا روزہ گزشتہ اور آئندہ سال کے گناہوں کا کفارہ بن جائے گا، اور یومِ عاشوراء کا روزہ گزشتہ سال کے گناہوں کا کفارہ بن جائے گا۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[1].headlines.arafah', 'یومِ عرفہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[1].headlines.ashura', 'یومِ عاشوراء');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[1].id', 'fasting-reason-arafah-or-ashura');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[1].title', 'یومِ عرفہ اور یومِ عاشوراء');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[2].cites[0].intro', 'نبی کریم ﷺ کی ایک زوجہ رضی اللہ عنہا فرماتی ہیں:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[2].cites[0].quote', 'رسول اللہ ﷺ ذی الحجہ کے پہلے نو دن، یومِ عاشوراء اور ہر مہینے کے تین دنوں کے روزے رکھتے تھے…');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].hadith', '2417');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].hadith', '2437');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[2].id', 'fasting-reason-first-9-dhu-al-hijjah');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[2].title', 'ذی الحجہ کے پہلے نو دن');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[1].intro', 'عبد اللہ بن عمرو بن العاص رضی اللہ عنہما بیان کرتے ہیں:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[1].quote', 'آپ کے لیے بس اتنا کافی ہے کہ ہر مہینے میں تین دن روزے رکھیں، کیونکہ نیکی کا بدلہ دس گنا ہے؛ پس یہ سارے سال کے روزوں کی مانند ہے۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].hadith', '1975');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[2].intro', 'ابو قتادہ رضی اللہ عنہ روایت کرتے ہیں کہ رسول اللہ ﷺ نے فرمایا:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[2].quote', 'ہر مہینے کے تین دن کے روزے اور ہر سال رمضان کے روزے، یہ سدا کا روزہ ہے۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[3].intro', 'رسول اللہ ﷺ نے ابو ذر رضی اللہ عنہ سے فرمایا:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[3].quote', 'جو ہر مہینے میں تین دن روزے رکھے، تو یہ ہمیشہ کے روزے کی مانند ہے۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].hadith', '1708');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[4].intro', 'جریر بن عبد اللہ رضی اللہ عنہ روایت کرتے ہیں کہ نبی اکرم ﷺ نے فرمایا:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[4].quote', 'ہر مہینے کے تین دن کے روزے ہمیشہ کے روزے کی مانند ہیں، اور ایامِ بیض تیرہ، چودہ اور پندرہ تاریخ ہیں۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].hadith', '2420');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[5].intro', 'ابو ہریرہ رضی اللہ عنہ بیان کرتے ہیں:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[5].quote', 'میرے خلیل ﷺ نے مجھے تین چیزوں کی وصیت فرمائی: ہر مہینے میں تین دن روزے رکھنے، چاشت کی دو رکعتیں پڑھنے اور سونے سے پہلے وتر پڑھنے کی۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].hadith', '1981');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[6].intro', 'ابو الدرداء رضی اللہ عنہ بیان کرتے ہیں:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[6].quote', 'میرے خلیل ﷺ نے مجھے تین چیزوں کی ہدایت فرمائی، جنہیں میں کبھی نہیں چھوڑتا؛ انہوں نے مجھے ہر مہینے میں تین دن روزے رکھنے کی ہدایت فرمائی۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].hadith', '1433');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[0].intro', 'نبی اکرم ﷺ نے ابو ذر رضی اللہ عنہ کو نصیحت فرمائی:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[0].quote', 'اگر تم کسی مہینے میں روزے رکھو، تو تیرہ، چودہ اور پندرہ تاریخ کے روزے رکھو۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].hadith', '761');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].id', 'fasting-reason-white-days');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[3].title', 'ایامِ بیض');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[1].intro', 'اسامہ بن زید رضی اللہ عنہما روایت کرتے ہیں کہ رسول اللہ ﷺ نے فرمایا:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[1].quote', 'یہ دو دن ہیں جن میں اعمال رب العالمین کے سامنے پیش کیے جاتے ہیں، اور میں پسند کرتا ہوں کہ میرے اعمال اس وقت پیش کیے جائیں جب میں روزے سے ہوں۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].hadith', '2358');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[2].intro', 'ابو قتادہ انصاری رضی اللہ عنہ روایت کرتے ہیں کہ رسول اللہ ﷺ سے پیر کے دن کے روزے کے بارے میں پوچھا گیا، تو آپ ﷺ نے فرمایا:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[2].quote', 'یہ وہ دن ہے جس میں میں پیدا ہوا، اور اسی دن مجھے نبوت عطا کی گئی یا میری طرف وحی نازل کی گئی۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].hadith', '1162b');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[3].intro', 'عائشہ رضی اللہ عنہا بیان کرتی ہیں:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[3].quote', 'نبی اکرم ﷺ پیر اور جمعرات کے روزوں کا خاص اہتمام فرماتے تھے۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].hadith', '745');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[0].intro', 'یہ روایت ابو ہریرہ رضی اللہ عنہ سے منقول ہے:');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[0].quote', 'پیر اور جمعرات کے دن اعمال پیش کیے جاتے ہیں، اور میں چاہتا ہوں کہ میرے اعمال اس حال میں پیش کیے جائیں کہ میں روزے سے ہوں۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].collection', 'riyadussalihin');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].hadith', '1256');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].hadith', '747');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].headlines.monday', 'پیر');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].headlines.thursday', 'جمعرات');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].id', 'fasting-reason-monday-thursday');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[4].title', 'پیر اور جمعرات');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[0].cites[1].quote', 'جس نے رمضان کے روزے رکھے، پھر اس کے بعد شوال کے چھ دن روزے رکھے، تو یہ سارے سال کے روزوں کی مانند ہے۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].hadith', '1716');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[0].cites[2].quote', 'جس نے رمضان کے روزے رکھے، پھر شوال کے چھ دن روزے رکھے، تو اس نے پورا سال روزے رکھے۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].hadith', '1164');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[0].cites[0].quote', 'جس نے عید الفطر کے بعد چھ دن روزے رکھے، اس نے سال مکمل کر لیا؛ کیونکہ جو نیکی کرے گا، اسے اس جیسی دس نیکیاں ملیں گی۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].hadith', '1715');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[0].id', 'fasting-reason-shawwal');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.reasons[0].title', 'شوال کے چھ دن');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reason-groups.voluntary.title', 'نفل');
insert into i18n_bundles (locale, code, value) values ('ur', 'fasting.reasons-title', 'روزوں کی وجوہات');
insert into i18n_bundles (locale, code, value) values ('ur', 'footer.attributions.label', 'انتسابات');
insert into i18n_bundles (locale, code, value) values ('ur', 'footer.contacts.github-ref-description', 'مسائل، نئی خصوصیات کی درخواستوں یا تعاون کے لیے براہِ کرم GitHub دیکھیں۔');
insert into i18n_bundles (locale, code, value) values ('ur', 'footer.contacts.label', 'رابطہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'hadith-referencing.collections.abudawud', 'سنن ابی داؤد');
insert into i18n_bundles (locale, code, value) values ('ur', 'hadith-referencing.collections.bukhari', 'صحیح البخاری');
insert into i18n_bundles (locale, code, value) values ('ur', 'hadith-referencing.collections.ibnmajah', 'سنن ابن ماجہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'hadith-referencing.collections.muslim', 'صحیح مسلم');
insert into i18n_bundles (locale, code, value) values ('ur', 'hadith-referencing.collections.nasai', 'سنن النسائی');
insert into i18n_bundles (locale, code, value) values ('ur', 'hadith-referencing.collections.riyadussalihin', 'ریاض الصالحین');
insert into i18n_bundles (locale, code, value) values ('ur', 'hadith-referencing.collections.tirmidhi', 'جامع الترمذی');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.AUTOMATIC.methodNames.AUTO_BY_LOCATION', 'مقام کے مطابق خودکار');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.AUTOMATIC.name', 'خودکار');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.ALGERIA', 'الجزائر');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.CIL', 'اسلامی کمیونٹی لزبن');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.DIYANET', 'دیانت (ترکی)');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.DUBAI', 'دبئی، متحدہ عرب امارات');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.EGAS', 'مصری جنرل اتھارٹی برائے سروے');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.GULF', 'خلیجی علاقہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.ISNA', 'اسلامک سوسائٹی آف نارتھ امریکہ (ISNA)');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.JAKIM', 'جاکیم، ملائیشیا');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.KARACHI', 'جامعہ علوم اسلامیہ، کراچی');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.KEMENAG', 'وزارت مذہبی امور، انڈونیشیا');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.KUWAIT', 'کویت');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.MOROCCO', 'مراکش');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.MSC', 'ہلال دیکھنے کی کمیٹی');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.MUIS', 'مجلس اسلامی سنگاپور (MUIS)');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.MWL', 'مسلم ورلڈ لیگ');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.QATAR', 'قطر');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.SAMR', 'روس کے مسلمانوں کی روحانی انتظامیہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.SHIA_QUM', 'شیعہ اثنا عشریہ، قم');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.TEHRAN', 'ادارۂ جیوفزکس، جامعہ تہران');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.TUNISIA', 'تونس');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.UMM_AL_QURA', 'جامعہ ام القریٰ، مکہ مکرمہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.methodNames.UOIF', 'فرانس کی اسلامی تنظیموں کا اتحاد (UOIF)');
insert into i18n_bundles (locale, code, value) values ('ur', 'prayer-time-method-groups.STANDARD.name', 'معیاری');
insert into i18n_bundles (locale, code, value) values ('ur', 'settings.location.forget-custom-location', 'منتخب مقام ہٹائیں');
insert into i18n_bundles (locale, code, value) values ('ur', 'settings.location.label', 'مقام');
insert into i18n_bundles (locale, code, value) values ('ur', 'settings.location.permission.change-in-browser', 'موجودہ مقام استعمال کریں');
insert into i18n_bundles (locale, code, value) values ('ur', 'settings.location.permission.grant-reason', 'فجر اور غروب کے اوقات کے لیے');
insert into i18n_bundles (locale, code, value) values ('ur', 'settings.location.permission.revoke-blocking', 'براہِ کرم سائٹ کی ترتیبات میں اجازت کی پابندی ہٹائیں');
insert into i18n_bundles (locale, code, value) values ('ur', 'settings.location.pick-on-map', 'نقشے پر مقام منتخب کریں');
insert into i18n_bundles (locale, code, value) values ('ur', 'settings.prayer-time-method', 'نماز کے اوقات کا طریقہ');
insert into i18n_bundles (locale, code, value) values ('ur', 'settings.time-zone', 'ٹائم زون');
