--liquibase formatted sql
--changeset id:00020 author:edwgiz@zohomail.com

insert into i18n_bundles (locale, code, value) values ('in', 'calendar.current-month', 'Bulan Ini');
insert into i18n_bundles (locale, code, value) values ('in', 'calendar.event.fajr', 'Fajar');
insert into i18n_bundles (locale, code, value) values ('in', 'calendar.event.sunset', 'Terbenam Matahari');
insert into i18n_bundles (locale, code, value) values ('in', 'calendar.monthNames[1]', 'Muharram');
insert into i18n_bundles (locale, code, value) values ('in', 'calendar.monthNames[2]', 'Safar');
insert into i18n_bundles (locale, code, value) values ('in', 'calendar.monthNames[3]', 'Rabiul Awal');
insert into i18n_bundles (locale, code, value) values ('in', 'calendar.monthNames[4]', 'Rabiul Akhir');
insert into i18n_bundles (locale, code, value) values ('in', 'calendar.monthNames[5]', 'Jumadil Awal');
insert into i18n_bundles (locale, code, value) values ('in', 'calendar.monthNames[6]', 'Jumadil Akhir');
insert into i18n_bundles (locale, code, value) values ('in', 'calendar.monthNames[7]', 'Rajab');
insert into i18n_bundles (locale, code, value) values ('in', 'calendar.monthNames[8]', 'Syaban');
insert into i18n_bundles (locale, code, value) values ('in', 'calendar.monthNames[9]', 'Ramadan');
insert into i18n_bundles (locale, code, value) values ('in', 'calendar.monthNames[10]', 'Syawal');
insert into i18n_bundles (locale, code, value) values ('in', 'calendar.monthNames[11]', 'Zulkaidah');
insert into i18n_bundles (locale, code, value) values ('in', 'calendar.monthNames[12]', 'Zulhijah');
insert into i18n_bundles (locale, code, value) values ('in', 'calendar.monthNames[0]', '');
insert into i18n_bundles (locale, code, value) values ('in', 'commons.cancel', 'Batal');
insert into i18n_bundles (locale, code, value) values ('in', 'commons.change', 'Ubah');
insert into i18n_bundles (locale, code, value) values ('in', 'commons.forget-custom-location', 'Lupakan lokasi pilihan');
insert into i18n_bundles (locale, code, value) values ('in', 'commons.ok', 'OK');
insert into i18n_bundles (locale, code, value) values ('in', 'commons.or', 'atau');
insert into i18n_bundles (locale, code, value) values ('in', 'errors.location-access', 'Gagal mendapatkan lokasi:');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.head.description', 'Kalender Puasa Tayyib: Jadwal puasa Islami autentik yang selaras dengan sunah Nabi dan tanggal Hijriah yang terverifikasi.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.head.title', 'Kalender Puasa Islam');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.ics.calendar.event.hijri-date-label', 'Hijriah');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.ics.calendar.event.summary', 'Puasa');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.ics.calendar.name', 'Puasa Islam');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.ics.copy-link-label', 'Salin tautan langganan');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.ics.event-summary', 'Puasa');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.ics.hijri-date-label', 'Hijriah');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.ics.label', 'Tambahkan jadwal ke kalender Anda');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.ics.link-label', 'Unduh ICS');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.mcp.copy-link-label', 'Salin tautan MCP');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.mcp.label', 'Berdayakan alat AI Anda');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.generic.ics-title', 'Sebab Puasa');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.generic.reasons[0].cites[0].id', 'fasting-reason-generic-0');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.generic.reasons[0].cites[0].quote', 'Setiap amal anak Adam untuknya, kecuali puasa; ia adalah untuk-Ku, dan Aku sendiri yang akan memberi balasan dengannya.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].hadith', '1904');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.obligatory.ics-title', 'Sebab Puasa Wajib');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.obligatory.reasons[0].cites[1].quote', 'Barang siapa berpuasa Ramadan karena iman dan mengharap pahala, niscaya diampuni dosa-dosanya yang telah lalu.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].hadith', '760');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].hadith', '38');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.obligatory.reasons[0].cites[0].quote', 'Islam dibangun di atas lima perkara: kesaksian bahwa tidak ada tuhan selain Allah dan bahwa Muhammad adalah utusan Allah, mendirikan salat, menunaikan zakat, menunaikan haji, dan berpuasa Ramadan.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].hadith', '16');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].hadith', '8');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.obligatory.reasons[0].id', 'fasting-reason-ramadan');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.obligatory.reasons[0].title', 'Ramadan');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.obligatory.title', 'Wajib');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.ics-title', 'Sebab Larangan Puasa');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].quote', 'Hari-hari Tasyrik adalah hari makan dan minum.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].hadith', '1141a');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[1].id', 'fasting-reason-tashriq');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[1].title', 'Hari-hari Tasyrik');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].intro', 'Diriwayatkan dari Abu Ubaid (ra):');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].quote', 'Aku menghadiri salat Id bersama Umar. Beliau mengerjakan salat sebelum khotbah, lalu berkata: Sesungguhnya Rasulullah shallallahu alaihi wasallam melarang berpuasa pada dua hari ini. Adapun Iduladha, kamu makan daging kurbanmu; adapun Idulfitri, kamu berbuka dari puasamu.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].hadith', '1722');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].hadith', '2416');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].intro', 'Diriwayatkan dari Abu Hurairah (ra):');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].quote', 'Dua puasa dilarang: puasa pada hari Idulfitri dan Iduladha.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].hadith', '1138');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].hadith', '1993');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-adha', 'Iduladha');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-fitr', 'Idulfitri');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].id', 'fasting-reason-eid-days');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.reasons[0].title', 'Idulfitri dan Iduladha');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.prohibiting.title', 'Diharamkan');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.ics-title', 'Sebab Puasa Sunah');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[1].cites[0].intro', 'Diriwayatkan dari Abu Qatada (ra), bahwa Rasulullah shallallahu alaihi wasallam bersabda:');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[1].cites[0].quote', 'Puasa hari Arafah, aku berharap kepada Allah agar menghapus dosa setahun yang lalu dan setahun yang akan datang; dan puasa hari Asyura, aku berharap kepada Allah agar menghapus dosa setahun yang lalu.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[1].headlines.arafah', 'Hari Arafah');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[1].headlines.ashura', 'Hari Asyura');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[1].id', 'fasting-reason-arafah-or-ashura');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[1].title', 'Hari Arafah dan Hari Asyura');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[2].cites[0].intro', 'Salah seorang istri Nabi shallallahu alaihi wasallam berkata:');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[2].cites[0].quote', 'Rasulullah shallallahu alaihi wasallam biasa berpuasa pada sembilan hari pertama Zulhijah, hari Asyura, dan tiga hari setiap bulan.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].hadith', '2417');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].hadith', '2437');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[2].id', 'fasting-reason-first-9-dhu-al-hijjah');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[2].title', 'Sembilan Hari Pertama Zulhijah');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[1].intro', 'Diriwayatkan dari Abdullah bin Amr bin Ash (ra), ia berkata: Rasulullah shallallahu alaihi wasallam bersabda kepadaku:');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[1].quote', 'Cukuplah bagimu berpuasa tiga hari setiap bulan, karena setiap kebaikan dibalas sepuluh kali lipat; dengan demikian, itu seperti puasa sepanjang tahun.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].hadith', '1975');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[2].intro', 'Diriwayatkan dari Abu Qatada (ra), bahwa Rasulullah shallallahu alaihi wasallam bersabda:');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[2].quote', 'Puasa tiga hari setiap bulan, serta Ramadan hingga Ramadan berikutnya, adalah puasa sepanjang masa.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[3].intro', 'Rasulullah shallallahu alaihi wasallam bersabda kepada Abu Zar:');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[3].quote', 'Barang siapa berpuasa tiga hari setiap bulan, maka itu seperti puasa sepanjang masa.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].hadith', '1708');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[4].intro', 'Diriwayatkan dari Jarir bin Abdullah (ra), dari Nabi shallallahu alaihi wasallam, beliau bersabda:');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[4].quote', 'Puasa tiga hari setiap bulan adalah puasa sepanjang masa, dan hari-hari putih, yaitu tanggal tiga belas, empat belas, dan lima belas.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].hadith', '2420');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[5].intro', 'Diriwayatkan dari Abu Hurairah (ra), ia berkata:');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[5].quote', 'Kekasihku, Nabi Muhammad shallallahu alaihi wasallam, berwasiat kepadaku dengan tiga perkara: puasa tiga hari setiap bulan, salat Duha dua rakaat, dan salat Witir sebelum tidur.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].hadith', '1981');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[6].intro', 'Abu Darda (ra) berkata:');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[6].quote', 'Kekasihku, Nabi shallallahu alaihi wasallam, berpesan kepadaku tiga perkara yang tidak akan kutinggalkan karena apa pun: beliau berpesan kepadaku untuk berpuasa tiga hari setiap bulan.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].hadith', '1433');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[0].intro', 'Nabi Muhammad shallallahu alaihi wasallam menasihati Abu Zar (ra):');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[0].quote', 'Jika engkau berpuasa pada sebagian bulan, maka puasalah pada tanggal tiga belas, empat belas, dan lima belas.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].hadith', '761');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].id', 'fasting-reason-white-days');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[3].title', 'Hari-hari Putih');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[1].intro', 'Diriwayatkan dari Usamah bin Zaid (ra), bahwa Rasulullah shallallahu alaihi wasallam bersabda:');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[1].quote', 'Itulah dua hari ketika amalan dihadapkan kepada Tuhan seluruh alam, dan aku ingin amalanku dihadapkan dalam keadaan berpuasa.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].hadith', '2358');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[2].intro', 'Nabi shallallahu alaihi wasallam ditanya oleh Abu Qatada al-Anshari (ra) tentang puasa hari Senin, lalu beliau menjawab:');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[2].quote', 'Itulah hari aku dilahirkan, hari aku diutus, atau hari wahyu diturunkan kepadaku.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].hadith', '1162b');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[3].intro', 'Diriwayatkan dari Aisyah (ra), ia berkata:');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[3].quote', 'Nabi shallallahu alaihi wasallam sangat memperhatikan puasa hari Senin dan Kamis.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].hadith', '745');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[0].intro', 'Pernyataan ini diriwayatkan dari Abu Hurairah (ra), bahwa Rasulullah shallallahu alaihi wasallam bersabda:');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[0].quote', 'Amal-amal dihadapkan pada hari Senin dan Kamis, dan aku ingin amalanku dihadapkan dalam keadaan berpuasa.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].collection', 'riyadussalihin');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].hadith', '1256');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].hadith', '747');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].headlines.monday', 'Senin');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].headlines.thursday', 'Kamis');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].id', 'fasting-reason-monday-thursday');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[4].title', 'Hari Senin dan Kamis');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[0].cites[1].quote', 'Barang siapa berpuasa Ramadan kemudian melanjutkannya dengan enam hari dari Syawal, maka itu seperti puasa sepanjang masa.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].hadith', '1716');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[0].cites[2].quote', 'Barang siapa berpuasa Ramadan kemudian melanjutkannya dengan enam hari puasa pada bulan Syawal, maka seolah-olah ia berpuasa sepanjang tahun.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].hadith', '1164');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[0].cites[0].quote', 'Barang siapa berpuasa enam hari setelah Idulfitri, maka ia telah menyempurnakan setahun; barang siapa mendatangkan satu kebaikan, maka ia memperoleh sepuluh kali lipatnya.');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].hadith', '1715');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[0].id', 'fasting-reason-shawwal');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.reasons[0].title', 'Enam Hari di Bulan Syawal');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reason-groups.voluntary.title', 'Sunah');
insert into i18n_bundles (locale, code, value) values ('in', 'fasting.reasons-title', 'Sebab-sebab Puasa');
insert into i18n_bundles (locale, code, value) values ('in', 'footer.attributions.label', 'Atribusi');
insert into i18n_bundles (locale, code, value) values ('in', 'footer.contacts.github-ref-description', 'Silakan kunjungi GitHub untuk melaporkan masalah, meminta fitur, atau berkontribusi.');
insert into i18n_bundles (locale, code, value) values ('in', 'footer.contacts.label', 'Kontak');
insert into i18n_bundles (locale, code, value) values ('in', 'hadith-referencing.collections.abudawud', 'Sunan Abu Dawud');
insert into i18n_bundles (locale, code, value) values ('in', 'hadith-referencing.collections.bukhari', 'Shahih al-Bukhari');
insert into i18n_bundles (locale, code, value) values ('in', 'hadith-referencing.collections.ibnmajah', 'Sunan Ibnu Majah');
insert into i18n_bundles (locale, code, value) values ('in', 'hadith-referencing.collections.muslim', 'Shahih Muslim');
insert into i18n_bundles (locale, code, value) values ('in', 'hadith-referencing.collections.nasai', 'Sunan an-Nasa''i');
insert into i18n_bundles (locale, code, value) values ('in', 'hadith-referencing.collections.riyadussalihin', 'Riyadhus Shalihin');
insert into i18n_bundles (locale, code, value) values ('in', 'hadith-referencing.collections.tirmidhi', 'Jami'' at-Tirmidzi');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.AUTOMATIC.methodNames.AUTO_BY_LOCATION', 'Otomatis berdasarkan lokasi');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.AUTOMATIC.name', 'Otomatis');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.ALGERIA', 'Aljazair');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.CIL', 'Komunitas Islam Lisbon');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.DIYANET', 'Diyanet (Turki)');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.DUBAI', 'Dubai, Uni Emirat Arab');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.EGAS', 'Otoritas Umum Survei Mesir');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.GULF', 'Wilayah Teluk');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.ISNA', 'Masyarakat Islam Amerika Utara (ISNA)');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.JAKIM', 'JAKIM, Malaysia');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.KARACHI', 'Universitas Ilmu-ilmu Islam, Karachi');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.KEMENAG', 'Kementerian Agama, Indonesia');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.KUWAIT', 'Kuwait');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.MOROCCO', 'Maroko');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.MSC', 'Komite Rukyat Hilal');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.MUIS', 'Majelis Ugama Islam Singapura (MUIS)');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.MWL', 'Liga Muslim Dunia');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.QATAR', 'Qatar');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.SAMR', 'Administrasi Spiritual Muslim, Rusia');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.SHIA_QUM', 'Syiah Itsna Asyariyah, Qum');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.TEHRAN', 'Institut Geofisika, Universitas Teheran');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.TUNISIA', 'Tunisia');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.UMM_AL_QURA', 'Universitas Ummul Qura, Makkah');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.methodNames.UOIF', 'Persatuan Organisasi Islam Prancis (UOIF)');
insert into i18n_bundles (locale, code, value) values ('in', 'prayer-time-method-groups.STANDARD.name', 'Standar');
insert into i18n_bundles (locale, code, value) values ('in', 'settings.location.forget-custom-location', 'Lupakan lokasi pilihan');
insert into i18n_bundles (locale, code, value) values ('in', 'settings.location.label', 'Lokasi');
insert into i18n_bundles (locale, code, value) values ('in', 'settings.location.permission.change-in-browser', 'Gunakan lokasi saat ini');
insert into i18n_bundles (locale, code, value) values ('in', 'settings.location.permission.grant-reason', 'Untuk waktu fajar dan matahari terbenam');
insert into i18n_bundles (locale, code, value) values ('in', 'settings.location.permission.revoke-blocking', 'Mohon hapus pemblokiran di pengaturan situs');
insert into i18n_bundles (locale, code, value) values ('in', 'settings.location.pick-on-map', 'Pilih lokasi di peta');
insert into i18n_bundles (locale, code, value) values ('in', 'settings.prayer-time-method', 'Metode Waktu Salat');
insert into i18n_bundles (locale, code, value) values ('in', 'settings.time-zone', 'Zona Waktu');
