--liquibase formatted sql
--changeset id:00021 author:edwgiz@zohomail.com

insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.current-month', 'Sasi Saiki');
insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.event.fajr', 'Subuh');
insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.event.sunset', 'Srengenge Angslup');
insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.monthNames[1]', 'Muharram');
insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.monthNames[2]', 'Safar');
insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.monthNames[3]', 'Rabiul Awal');
insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.monthNames[4]', 'Rabiul Akhir');
insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.monthNames[5]', 'Jumadil Awal');
insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.monthNames[6]', 'Jumadil Akhir');
insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.monthNames[7]', 'Rajab');
insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.monthNames[8]', 'Sya''ban');
insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.monthNames[9]', 'Ramadan');
insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.monthNames[10]', 'Sawal');
insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.monthNames[11]', 'Dzulqaidah');
insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.monthNames[12]', 'Dzulhijah');
insert into i18n_bundles (locale, code, value) values ('jv', 'calendar.monthNames[0]', '');
insert into i18n_bundles (locale, code, value) values ('jv', 'commons.cancel', 'Batal');
insert into i18n_bundles (locale, code, value) values ('jv', 'commons.change', 'Ganti');
insert into i18n_bundles (locale, code, value) values ('jv', 'commons.forget-custom-location', 'Lali lokasi sing wis dipilih');
insert into i18n_bundles (locale, code, value) values ('jv', 'commons.ok', 'Oke');
insert into i18n_bundles (locale, code, value) values ('jv', 'commons.or', 'utawa');
insert into i18n_bundles (locale, code, value) values ('jv', 'errors.location-access', 'Ana kaluputan nalika njupuk lokasi:');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.head.description', 'Kalender Pasa Tayyib: Jadwal pasa Islam asli sing selaras karo Sunnah lan tanggal Hijriyah sing wis diverifikasi.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.head.title', 'Kalender Pasa Islam');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.ics.calendar.event.hijri-date-label', 'Hijriyah');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.ics.calendar.event.summary', 'Pasa');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.ics.calendar.name', 'Pasa Islam');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.ics.copy-link-label', 'Salin pranala langganan');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.ics.event-summary', 'Pasa');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.ics.hijri-date-label', 'Hijriyah');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.ics.label', 'Tambahake jadwal menyang kalender panjenengan');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.ics.link-label', 'Undhuh ICS');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.mcp.copy-link-label', 'Salin pranala MCP');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.mcp.label', 'Aktifake piranti AI panjenengan');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.generic.ics-title', 'Alesan Pasa');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.generic.reasons[0].cites[0].id', 'fasting-reason-generic-0');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.generic.reasons[0].cites[0].quote', 'Allah ngendika: Saben amale anak Adam iku kanggo dheweke, kajaba pasa; satemene iku kanggo Ingsun, lan Ingsun bakal menehi ganjaran.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].hadith', '1904');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.obligatory.ics-title', 'Alesan Pasa Wajib');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.obligatory.reasons[0].cites[1].quote', 'Sapa sing pasa Ramadan kanthi iman lan ngarep-arep ganjaran, dosa-dosane sing wis kepungkur bakal diampuni.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].hadith', '760');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].hadith', '38');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.obligatory.reasons[0].cites[0].quote', 'Islam iku dibangun ing lima perkara: syahadat yen ora ana sesembahan kang bener kajaba Allah lan yen Muhammad iku utusan Allah, nindakake shalat, mbayar zakat, nindakake haji, lan pasa Ramadan.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].hadith', '16');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].hadith', '8');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.obligatory.reasons[0].id', 'fasting-reason-ramadan');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.obligatory.reasons[0].title', 'Ramadan');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.obligatory.title', 'Wajib');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.ics-title', 'Alesan Pasa sing Diharamake');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].quote', 'Dina-dina Tasyrik iku dina-dina mangan lan ngombe.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].hadith', '1141a');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[1].id', 'fasting-reason-tashriq');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[1].title', 'Dina-dina Tasyrik');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].intro', 'Diriwayatake dening Abu Ubaid (ra.)');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].quote', 'Aku melu shalat Id bebarengan karo Umar (ra.). Dheweke nindakake shalat sadurunge khutbah, banjur ngendika: Rasulullah shallallahu alaihi wasallam nglarang pasa ing rong dina iki. Ing dina Idul Adha, panjenengan mangan daging kurban panjenengan; lan ing dina Idul Fitri, panjenengan mungkasi pasa panjenengan.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].hadith', '1722');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].hadith', '2416');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].intro', 'Diriwayatake dening Abu Hurairah (ra.)');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].quote', 'Rasulullah shallallahu alaihi wasallam nglarang pasa ing rong dina: dina Idul Fitri lan dina Idul Adha.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].hadith', '1138');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].hadith', '1993');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-adha', 'Idul Adha');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-fitr', 'Idul Fitri');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].id', 'fasting-reason-eid-days');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.reasons[0].title', 'Idul Fitri lan Idul Adha');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.prohibiting.title', 'Haram');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.ics-title', 'Alesan Pasa Sunnah');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[1].cites[0].intro', 'Abu Qatadah (ra.) ngriwayatake yen Rasulullah shallallahu alaihi wasallam ngendika:');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[1].cites[0].quote', 'Aku ngarep-arep marang Allah supaya pasa ing dina Arafah nglebur dosa-dosa setaun sadurunge lan setaun sawise, lan aku ngarep-arep marang Allah supaya pasa ing dina Asyura nglebur dosa-dosa setaun sadurunge.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[1].headlines.arafah', 'Dina Arafah');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[1].headlines.ashura', 'Dina Asyura');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[1].id', 'fasting-reason-arafah-or-ashura');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[1].title', 'Dina Arafah lan Asyura');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[2].cites[0].intro', 'Salah sawijining garwa Rasulullah shallallahu alaihi wasallam (radhiyallahu anha) ngendika:');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[2].cites[0].quote', 'Rasulullah shallallahu alaihi wasallam biyasa pasa ing sanga dina wiwitan sasi Dzulhijah, dina Asyura, lan telung dina saben sasi.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].hadith', '2417');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].hadith', '2437');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[2].id', 'fasting-reason-first-9-dhu-al-hijjah');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[2].title', 'Sanga dina wiwitan sasi Dzulhijah');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[1].intro', 'Diriwayatake dening Abdullah bin Amr bin Ash:');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[1].quote', 'Kanggo panjenengan cukup pasa telung dina saben sasi, amarga siji kabecikan diganjar sepuluh tikel, mula iku kaya pasa setaun kebak.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].hadith', '1975');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[2].intro', 'Abu Qatadah (ra.) ngriwayatake yen Rasulullah shallallahu alaihi wasallam ngendika:');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[2].quote', 'Pasa telung dina saben sasi, lan pasa Ramadan nganti Ramadan sabanjure, iku kaya pasa terus-terusan.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[3].intro', 'Rasulullah shallallahu alaihi wasallam ngendika marang Abu Dzar:');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[3].quote', 'Sapa sing pasa telung dina saben sasi, iku kaya pasa salawase.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].hadith', '1708');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[4].intro', 'Diriwayatake saka Jarir bin Abdullah yen Nabi shallallahu alaihi wasallam ngendika:');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[4].quote', 'Pasa telung dina saben sasi iku kaya pasa salawase, lan dina-dina putih (Ayyam al-Bidh) yaiku dina kaping telulas, patbelas, lan limolas.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].hadith', '2420');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[5].intro', 'Diriwayatake dening Abu Hurairah (ra.):');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[5].quote', 'Kinasihku (Nabi Muhammad shallallahu alaihi wasallam) menehi wasiat marang aku telung perkara: pasa telung dina saben sasi, shalat Dhuha rong rakaat, lan shalat Witir sadurunge turu.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].hadith', '1981');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[6].intro', 'Abu Darda (ra.) ngriwayatake:');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[6].quote', 'Kinasihku (Nabi Muhammad shallallahu alaihi wasallam) menehi wasiat telung amalan sing ora bakal daklalekake, lan dheweke mewasiatake marang aku supaya pasa telung dina saben sasi.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].hadith', '1433');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[0].intro', 'Nabi Muhammad shallallahu alaihi wasallam menehi wasiat marang Abu Dzar (ra.):');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[0].quote', 'Yen panjenengan pasa ing sawetara dina saben sasi, banjur pasa ing dina kaping telulas, patbelas, lan limolas.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].hadith', '761');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].id', 'fasting-reason-white-days');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[3].title', 'Dina-dina Putih');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[1].intro', 'Usamah bin Zaid (ra.) ngriwayatake yen Rasulullah shallallahu alaihi wasallam ngendika:');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[1].quote', 'Iku rong dina nalika amal-amal diaturake marang Rabbul Alamin, lan aku seneng amalku diaturake nalika aku lagi pasa.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].hadith', '2358');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[2].intro', 'Nabi shallallahu alaihi wasallam ditakoni dening Abu Qatadah al-Anshari (ra.) bab pasa ing dina Senin, banjur ngendika:');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[2].quote', 'Iku dina nalika aku dilairake, lan ing dina iku aku diutus minangka nabi, utawa wahyu diturunake marang aku.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].hadith', '1162b');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[3].intro', 'Aisyah (ra.) ngriwayatake:');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[3].quote', 'Nabi shallallahu alaihi wasallam biyasa ngutamakake pasa ing dina Senin lan Kamis.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].hadith', '745');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[0].intro', 'Kandhaan iki diriwayatake dening Abu Hurairah (ra.):');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[0].quote', 'Amal-amal diaturake ing dina Senin lan Kamis, lan aku seneng amalku diaturake nalika aku lagi pasa.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].collection', 'riyadussalihin');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].hadith', '1256');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].hadith', '747');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].headlines.monday', 'Senin');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].headlines.thursday', 'Kamis');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].id', 'fasting-reason-monday-thursday');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[4].title', 'Senin lan Kamis');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[0].cites[1].quote', 'Sapa sing pasa Ramadan banjur nyambungake karo enem dina ing sasi Sawal, iku kaya pasa salawase.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].hadith', '1716');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[0].cites[2].quote', 'Sapa sing pasa ing sasi Ramadan banjur nyambungake karo enem dina pasa ing sasi Sawal, iku kaya dheweke pasa setaun kebak.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].hadith', '1164');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[0].cites[0].quote', 'Sapa sing pasa enem dina sawise Idul Fitri, iku kaya wis nyampurnakake pasa setaun, amarga sapa sing nindakake siji kabecikan bakal diganjar sepuluh tikel.');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].hadith', '1715');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[0].id', 'fasting-reason-shawwal');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.reasons[0].title', 'Enem Dina ing Sawal');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reason-groups.voluntary.title', 'Sunnah');
insert into i18n_bundles (locale, code, value) values ('jv', 'fasting.reasons-title', 'Alesan Pasa');
insert into i18n_bundles (locale, code, value) values ('jv', 'footer.attributions.label', 'Atribusi');
insert into i18n_bundles (locale, code, value) values ('jv', 'footer.contacts.github-ref-description', 'Mangga buka GitHub kanggo masalah, panjalukan fitur, utawa kontribusi.');
insert into i18n_bundles (locale, code, value) values ('jv', 'footer.contacts.label', 'Kontak');
insert into i18n_bundles (locale, code, value) values ('jv', 'hadith-referencing.collections.abudawud', 'Sunan Abu Dawud');
insert into i18n_bundles (locale, code, value) values ('jv', 'hadith-referencing.collections.bukhari', 'Sahih al-Bukhari');
insert into i18n_bundles (locale, code, value) values ('jv', 'hadith-referencing.collections.ibnmajah', 'Sunan Ibnu Majah');
insert into i18n_bundles (locale, code, value) values ('jv', 'hadith-referencing.collections.muslim', 'Sahih Muslim');
insert into i18n_bundles (locale, code, value) values ('jv', 'hadith-referencing.collections.nasai', 'Sunan an-Nasai');
insert into i18n_bundles (locale, code, value) values ('jv', 'hadith-referencing.collections.riyadussalihin', 'Riyad as-Salihin');
insert into i18n_bundles (locale, code, value) values ('jv', 'hadith-referencing.collections.tirmidhi', 'Jami at-Tirmidhi');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.AUTOMATIC.methodNames.AUTO_BY_LOCATION', 'Otomatis adhedhasar lokasi');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.AUTOMATIC.name', 'Otomatis');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.ALGERIA', 'Aljazair');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.CIL', 'Komunitas Islam Lisbon');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.DIYANET', 'Diyanet (Turki)');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.DUBAI', 'Dubai, Uni Emirat Arab');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.EGAS', 'Otoritas Umum Survei Mesir');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.GULF', 'Wilayah Teluk');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.ISNA', 'Masyarakat Islam Amerika Lor (ISNA)');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.JAKIM', 'JAKIM, Malaysia');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.KARACHI', 'Universitas Ilmu Islam, Karachi');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.KEMENAG', 'Kementerian Agama, Indonesia');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.KUWAIT', 'Kuwait');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.MOROCCO', 'Maroko');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.MSC', 'Komite Rukyatul Hilal');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.MUIS', 'Majlis Ugama Islam Singapura (MUIS)');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.MWL', 'Liga Dunia Islam');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.QATAR', 'Qatar');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.SAMR', 'Administrasi Spiritual Muslim, Rusia');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.SHIA_QUM', 'Syiah Itsna Asyariyah, Qum');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.TEHRAN', 'Institut Geofisika, Universitas Teheran');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.TUNISIA', 'Tunisia');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.UMM_AL_QURA', 'Universitas Ummul Qura, Makkah');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.methodNames.UOIF', 'Persatuan Organisasi Islam Prancis (UOIF)');
insert into i18n_bundles (locale, code, value) values ('jv', 'prayer-time-method-groups.STANDARD.name', 'Standar');
insert into i18n_bundles (locale, code, value) values ('jv', 'settings.location.forget-custom-location', 'Lali lokasi sing wis dipilih');
insert into i18n_bundles (locale, code, value) values ('jv', 'settings.location.label', 'Lokasi');
insert into i18n_bundles (locale, code, value) values ('jv', 'settings.location.permission.change-in-browser', 'Gunakake lokasi saiki');
insert into i18n_bundles (locale, code, value) values ('jv', 'settings.location.permission.grant-reason', 'Kanggo wektu Subuh lan Srengenge Angslup');
insert into i18n_bundles (locale, code, value) values ('jv', 'settings.location.permission.revoke-blocking', 'Mangga busak pamblokiran ing setelan situs');
insert into i18n_bundles (locale, code, value) values ('jv', 'settings.location.pick-on-map', 'Pilih lokasi ing peta');
insert into i18n_bundles (locale, code, value) values ('jv', 'settings.prayer-time-method', 'Metode Wektu Shalat');
insert into i18n_bundles (locale, code, value) values ('jv', 'settings.time-zone', 'Zona wektu');
