--liquibase formatted sql
--changeset id:00022 author:edwgiz@zohomail.eu

insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.current-month', 'Bulan Ini');
insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.event.fajr', 'Subuh');
insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.event.sunset', 'Matahari Terbenam');
insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.monthNames[1]', 'Muharam');
insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.monthNames[2]', 'Safar');
insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.monthNames[3]', 'Rabiulawal');
insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.monthNames[4]', 'Rabiulakhir');
insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.monthNames[5]', 'Jamadilawal');
insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.monthNames[6]', 'Jamadilakhir');
insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.monthNames[7]', 'Rejab');
insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.monthNames[8]', 'Syaaban');
insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.monthNames[9]', 'Ramadan');
insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.monthNames[10]', 'Syawal');
insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.monthNames[11]', 'Zulkaedah');
insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.monthNames[12]', 'Zulhijjah');
insert into i18n_bundles (locale, code, value) values ('ms', 'calendar.monthNames[0]', '');
insert into i18n_bundles (locale, code, value) values ('ms', 'commons.cancel', 'Batal');
insert into i18n_bundles (locale, code, value) values ('ms', 'commons.change', 'Ubah');
insert into i18n_bundles (locale, code, value) values ('ms', 'commons.forget-custom-location', 'Lupakan lokasi pilihan');
insert into i18n_bundles (locale, code, value) values ('ms', 'commons.ok', 'OK');
insert into i18n_bundles (locale, code, value) values ('ms', 'commons.or', 'atau');
insert into i18n_bundles (locale, code, value) values ('ms', 'errors.location-access', 'Ralat mendapatkan lokasi:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.head.description', 'Kalendar Puasa Tayyib: Jadual puasa Islam yang sahih, selaras dengan amalan Sunnah dan tarikh Hijri yang disahkan.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.head.title', 'Kalendar Puasa Islam');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.ics.calendar.event.hijri-date-label', 'Hijri');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.ics.calendar.event.summary', 'Puasa');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.ics.calendar.name', 'Puasa Islam');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.ics.copy-link-label', 'Salin pautan langganan');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.ics.event-summary', 'Puasa');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.ics.hijri-date-label', 'Hijri');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.ics.label', 'Tambah jadual ke kalendar anda');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.ics.link-label', 'Muat turun ICS');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.mcp.copy-link-label', 'Salin pautan MCP');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.mcp.label', 'Perkasakan alat AI anda');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.generic.ics-title', 'Sebab puasa');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.generic.reasons[0].cites[0].id', 'fasting-reason-generic-0');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.generic.reasons[0].cites[0].quote', 'Allah SWT berfirman: Setiap amalan anak Adam adalah untuknya kecuali puasa; sesungguhnya ia untuk-Ku, dan Aku akan membalasnya.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].hadith', '1904');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.obligatory.ics-title', 'Sebab puasa wajib');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.obligatory.reasons[0].cites[1].quote', 'Sesiapa yang berpuasa Ramadan kerana iman dan mengharapkan pahala, dosa-dosanya yang telah lalu akan diampunkan.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].hadith', '760');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].hadith', '38');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.obligatory.reasons[0].cites[0].quote', 'Islam dibina atas lima perkara: bersaksi bahawa tiada tuhan yang berhak disembah melainkan Allah dan bahawa Muhammad ialah Rasul Allah, mendirikan solat, menunaikan zakat, mengerjakan haji, dan berpuasa Ramadan.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].hadith', '16');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].hadith', '8');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.obligatory.reasons[0].id', 'fasting-reason-ramadan');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.obligatory.reasons[0].title', 'Ramadan');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.obligatory.title', 'Wajib');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.ics-title', 'Sebab puasa yang dilarang');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].quote', 'Hari-hari Tasyriq adalah hari makan dan minum.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].hadith', '1141a');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[1].id', 'fasting-reason-tashriq');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[1].title', 'Hari-hari Tasyriq');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].intro', 'Diriwayatkan oleh Abu Ubaid:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].quote', 'Aku menghadiri solat Hari Raya bersama Umar, lalu dia memulakan solat sebelum khutbah, kemudian berkata: Sesungguhnya Rasulullah SAW melarang puasa pada dua hari ini. Adapun Hari Raya Aidiladha, kamu makan daging korban kamu; adapun Hari Raya Aidilfitri, ia adalah hari kamu berbuka daripada puasa kamu.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].hadith', '1722');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].hadith', '2416');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].intro', 'Diriwayatkan oleh Abu Hurairah RA:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].quote', 'Dua hari puasa diharamkan: puasa pada Hari Raya Aidilfitri dan Hari Raya Aidiladha.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].hadith', '1138');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].hadith', '1993');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-adha', 'Hari Raya Aidiladha');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-fitr', 'Hari Raya Aidilfitri');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].id', 'fasting-reason-eid-days');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.reasons[0].title', 'Hari Raya Aidilfitri dan Hari Raya Aidiladha');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.prohibiting.title', 'Dilarang');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.ics-title', 'Sebab puasa sunat');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[1].cites[0].intro', 'Abu Qatadah RA meriwayatkan bahawa Rasulullah SAW bersabda:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[1].cites[0].quote', 'Aku memohon kepada Allah agar puasa pada Hari Arafah dapat menghapuskan dosa-dosa setahun yang lalu dan setahun yang akan datang, dan aku memohon kepada Allah agar puasa pada Hari Asyura dapat menghapuskan dosa-dosa setahun yang lalu.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[1].headlines.arafah', 'Hari Arafah');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[1].headlines.ashura', 'Hari Asyura');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[1].id', 'fasting-reason-arafah-or-ashura');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[1].title', 'Hari Arafah dan Hari Asyura');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[2].cites[0].intro', 'Salah seorang isteri Nabi Muhammad SAW berkata:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[2].cites[0].quote', 'Rasulullah Muhammad SAW biasa berpuasa pada sembilan hari pertama Zulhijjah, Hari Asyura, dan tiga hari dalam setiap bulan.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].hadith', '2417');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].hadith', '2437');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[2].id', 'fasting-reason-first-9-dhu-al-hijjah');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[2].title', 'Sembilan Hari Pertama Zulhijjah');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[1].intro', 'Diriwayatkan oleh Abdullah bin Amr bin al-As RA:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[1].quote', 'Cukuplah bagi kamu berpuasa tiga hari dalam sebulan, kerana setiap kebaikan digandakan sepuluh kali, maka ia seperti puasa sepanjang tahun.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].hadith', '1975');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[2].intro', 'Abu Qatadah RA meriwayatkan bahawa Rasulullah SAW bersabda:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[2].quote', 'Puasa tiga hari setiap bulan dan puasa Ramadan setiap tahun adalah puasa sepanjang masa.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[3].intro', 'Rasulullah SAW bersabda kepada Abu Zar:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[3].quote', 'Puasa tiga hari setiap bulan adalah seperti puasa sepanjang hayat.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].hadith', '1708');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[4].intro', 'Diriwayatkan daripada Jarir bin Abdullah RA bahawa Nabi SAW bersabda:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[4].quote', 'Puasa tiga hari setiap bulan adalah puasa sepanjang hayat, dan hari-hari putih ialah hari ketiga belas, keempat belas, dan kelima belas.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].hadith', '2420');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[5].intro', 'Diriwayatkan oleh Abu Hurairah RA:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[5].quote', 'Kekasihku, Nabi Muhammad SAW, telah berwasiat kepadaku dengan tiga perkara: berpuasa tiga hari dalam setiap bulan, solat Dhuha dua rakaat, dan solat Witir sebelum tidur.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].hadith', '1981');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[6].intro', 'Abu al-Darda RA berkata:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[6].quote', 'Kekasihku, Nabi SAW, berpesan kepadaku dengan tiga amalan yang tidak akan aku tinggalkan kerana sesuatu apa pun: baginda berpesan kepadaku agar berpuasa tiga hari setiap bulan.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].hadith', '1433');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[0].intro', 'Nabi Muhammad SAW menasihati Abu Zar RA:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[0].quote', 'Jika engkau berpuasa pada mana-mana hari dalam sebulan, maka berpuasalah pada hari ketiga belas, keempat belas, dan kelima belas.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].hadith', '761');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].id', 'fasting-reason-white-days');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[3].title', 'Hari-hari Putih');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[1].intro', 'Usamah bin Zaid RA meriwayatkan bahawa Rasulullah SAW bersabda:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[1].quote', 'Itulah dua hari amalan-amalan dibentangkan kepada Tuhan sekalian alam, dan aku suka amalanku dibentangkan ketika aku berpuasa.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].hadith', '2358');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[2].intro', 'Nabi SAW ditanya oleh Abu Qatadah al-Ansari RA tentang puasa pada hari Isnin, lalu baginda bersabda:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[2].quote', 'Ia adalah hari aku dilahirkan, dan pada hari itu aku diutuskan sebagai nabi, atau wahyu diturunkan kepadaku.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].hadith', '1162b');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[3].intro', 'Aisyah RA berkata:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[3].quote', 'Nabi SAW biasa bersungguh-sungguh berpuasa pada hari Isnin dan Khamis.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].hadith', '745');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[0].intro', 'Kenyataan khusus ini diriwayatkan oleh Abu Hurairah RA:');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[0].quote', 'Amalan-amalan dibentangkan pada hari Isnin dan Khamis, maka aku suka amalanku dibentangkan ketika aku berpuasa.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].collection', 'riyadussalihin');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].hadith', '1256');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].hadith', '747');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].headlines.monday', 'Hari Isnin');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].headlines.thursday', 'Hari Khamis');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].id', 'fasting-reason-monday-thursday');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[4].title', 'Hari Isnin dan Hari Khamis');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[0].cites[1].quote', 'Sesiapa yang berpuasa Ramadan kemudian mengikutinya dengan enam hari dalam bulan Syawal, maka dia seperti berpuasa sepanjang hayat.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].hadith', '1716');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[0].cites[2].quote', 'Sesiapa yang berpuasa dalam bulan Ramadan kemudian mengikutinya dengan enam hari puasa dalam bulan Syawal, maka dia seperti berpuasa sepanjang tahun.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].hadith', '1164');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[0].cites[0].quote', 'Sesiapa yang berpuasa enam hari selepas Hari Raya Aidilfitri, maka dia telah menyempurnakan puasa setahun, kerana sesiapa yang melakukan kebaikan akan mendapat sepuluh pahala sepertinya.');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].hadith', '1715');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[0].id', 'fasting-reason-shawwal');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.reasons[0].title', 'Enam Hari dalam Bulan Syawal');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reason-groups.voluntary.title', 'Sunat');
insert into i18n_bundles (locale, code, value) values ('ms', 'fasting.reasons-title', 'Sebab-sebab puasa');
insert into i18n_bundles (locale, code, value) values ('ms', 'footer.attributions.label', 'Atribusi');
insert into i18n_bundles (locale, code, value) values ('ms', 'footer.contacts.github-ref-description', 'Sila lawati GitHub untuk isu, permintaan ciri, atau sumbangan.');
insert into i18n_bundles (locale, code, value) values ('ms', 'footer.contacts.label', 'Hubungan');
insert into i18n_bundles (locale, code, value) values ('ms', 'hadith-referencing.collections.abudawud', 'Sunan Abu Daud');
insert into i18n_bundles (locale, code, value) values ('ms', 'hadith-referencing.collections.bukhari', 'Sahih al-Bukhari');
insert into i18n_bundles (locale, code, value) values ('ms', 'hadith-referencing.collections.ibnmajah', 'Sunan Ibn Majah');
insert into i18n_bundles (locale, code, value) values ('ms', 'hadith-referencing.collections.muslim', 'Sahih Muslim');
insert into i18n_bundles (locale, code, value) values ('ms', 'hadith-referencing.collections.nasai', 'Sunan an-Nasa''i');
insert into i18n_bundles (locale, code, value) values ('ms', 'hadith-referencing.collections.riyadussalihin', 'Riyadhus Solihin');
insert into i18n_bundles (locale, code, value) values ('ms', 'hadith-referencing.collections.tirmidhi', 'Jami'' at-Tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.AUTOMATIC.methodNames.AUTO_BY_LOCATION', 'Automatik berdasarkan lokasi');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.AUTOMATIC.name', 'Automatik');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.ALGERIA', 'Algeria');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.CIL', 'Komuniti Islam Lisbon');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.DIYANET', 'Diyanet (Turki)');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.DUBAI', 'Dubai, UAE');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.EGAS', 'Penguasa Am Ukur Mesir');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.GULF', 'Kawasan Teluk');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.ISNA', 'Persatuan Islam Amerika Utara (ISNA)');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.JAKIM', 'JAKIM, Malaysia');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.KARACHI', 'Universiti Sains Islam, Karachi');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.KEMENAG', 'Kementerian Agama Indonesia');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.KUWAIT', 'Kuwait');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.MOROCCO', 'Maghribi');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.MSC', 'Jawatankuasa Rukyah Bulan');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.MUIS', 'Majlis Ugama Islam Singapura (MUIS)');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.MWL', 'Liga Dunia Islam');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.QATAR', 'Qatar');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.SAMR', 'Pentadbiran Rohani Umat Islam, Rusia');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.SHIA_QUM', 'Syiah Dua Belas Imam, Qum');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.TEHRAN', 'Institut Geofizik, Universiti Tehran');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.TUNISIA', 'Tunisia');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.UMM_AL_QURA', 'Universiti Umm al-Qura, Makkah');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.methodNames.UOIF', 'Kesatuan Pertubuhan Islam Perancis (UOIF)');
insert into i18n_bundles (locale, code, value) values ('ms', 'prayer-time-method-groups.STANDARD.name', 'Standard');
insert into i18n_bundles (locale, code, value) values ('ms', 'settings.location.forget-custom-location', 'Lupakan lokasi pilihan');
insert into i18n_bundles (locale, code, value) values ('ms', 'settings.location.label', 'Lokasi');
insert into i18n_bundles (locale, code, value) values ('ms', 'settings.location.permission.change-in-browser', 'Gunakan lokasi semasa');
insert into i18n_bundles (locale, code, value) values ('ms', 'settings.location.permission.grant-reason', 'Untuk waktu Subuh dan matahari terbenam');
insert into i18n_bundles (locale, code, value) values ('ms', 'settings.location.permission.revoke-blocking', 'sila nyahsekat dalam tetapan laman');
insert into i18n_bundles (locale, code, value) values ('ms', 'settings.location.pick-on-map', 'Pilih lokasi pada peta');
insert into i18n_bundles (locale, code, value) values ('ms', 'settings.prayer-time-method', 'Kaedah Waktu Solat');
insert into i18n_bundles (locale, code, value) values ('ms', 'settings.time-zone', 'Zon waktu');
