--liquibase formatted sql
--changeset id:00026 author:edwgiz@zohomail.eu

insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.current-month', 'İçinde Bulunulan Ay');
insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.event.fajr', 'İmsak');
insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.event.sunset', 'İftar');
insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.monthNames[1]', 'Muharrem');
insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.monthNames[2]', 'Safer');
insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.monthNames[3]', 'Rebiülevvel');
insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.monthNames[4]', 'Rebiülahir');
insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.monthNames[5]', 'Cemaziyelevvel');
insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.monthNames[6]', 'Cemaziyelahir');
insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.monthNames[7]', 'Recep');
insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.monthNames[8]', 'Şaban');
insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.monthNames[9]', 'Ramazan');
insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.monthNames[10]', 'Şevval');
insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.monthNames[11]', 'Zilkade');
insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.monthNames[12]', 'Zilhicce');
insert into i18n_bundles (locale, code, value) values ('tr', 'calendar.monthNames[0]', '');
insert into i18n_bundles (locale, code, value) values ('tr', 'commons.cancel', 'İptal');
insert into i18n_bundles (locale, code, value) values ('tr', 'commons.change', 'Değiştir');
insert into i18n_bundles (locale, code, value) values ('tr', 'commons.forget-custom-location', 'Seçili konumu unut');
insert into i18n_bundles (locale, code, value) values ('tr', 'commons.ok', 'Tamam');
insert into i18n_bundles (locale, code, value) values ('tr', 'commons.or', 'veya');
insert into i18n_bundles (locale, code, value) values ('tr', 'errors.location-access', 'Konum alınırken hata:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.head.description', 'Tayyib Oruç Takvimi: Sünnet’e uygun, doğrulanmış hicrî tarihler içeren sahih İslami oruç vakitleri.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.head.title', 'İslami Oruç Takvimi');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.ics.calendar.event.hijri-date-label', 'Hicri');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.ics.calendar.event.summary', 'Oruç');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.ics.calendar.name', 'İslami Oruç');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.ics.copy-link-label', 'Abonelik bağlantısını kopyala');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.ics.event-summary', 'Oruç');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.ics.hijri-date-label', 'Hicri');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.ics.label', 'Programı takviminize ekleyin');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.ics.link-label', 'ICS dosyasını indir');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.mcp.copy-link-label', 'MCP bağlantısını kopyala');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.mcp.label', 'Yapay zekâ araçlarınızı güçlendirin');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.generic.ics-title', 'Oruç sebebi');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.generic.reasons[0].cites[0].id', 'fasting-reason-generic-0');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.generic.reasons[0].cites[0].quote', 'Âdemoğlunun her ameli kendisi içindir; oruç hariç. Çünkü oruç benim içindir ve onun mükâfatını ben vereceğim.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].hadith', '1904');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.obligatory.ics-title', 'Farz (Vâcip) oruç sebebi');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.obligatory.reasons[0].cites[1].quote', 'Kim iman ederek ve sevabını Allah’tan umarak Ramazan orucunu tutarsa geçmiş günahları bağışlanır.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].hadith', '760');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].hadith', '38');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.obligatory.reasons[0].cites[0].quote', 'İslam beş esas üzerine bina edilmiştir: Allah’tan başka ilâh olmadığına ve Hz. Muhammed’in Allah’ın resulü olduğuna şehadet etmek, namazı dosdoğru kılmak, zekâtı vermek, haccetmek ve Ramazan orucunu tutmak.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].hadith', '16');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].hadith', '8');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.obligatory.reasons[0].id', 'fasting-reason-ramadan');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.obligatory.reasons[0].title', 'Ramazan');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.obligatory.title', 'Farz');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.ics-title', 'Yasaklanan (Haram) oruç sebebi');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].quote', 'Teşrik günleri yeme içme günleridir.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].hadith', '1141a');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[1].id', 'fasting-reason-tashriq');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[1].title', 'Teşrik Günleri');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].intro', 'Ebû Ubeyd (r.a.) şöyle demiştir:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].quote', 'Ömer (r.a.) ile birlikte bayram namazına katıldım. Namazı hutbeden önce kıldırdı. Sonra şöyle dedi: Resûlullah (s.a.v.) bu iki günde oruç tutmayı yasaklamıştır. Kurban Bayramı günü kurbanlarınızın etinden yersiniz; Ramazan Bayramı günü ise orucunuzu açarsınız.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].hadith', '1722');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].hadith', '2416');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].intro', 'Ebû Hüreyre (r.a.) şöyle demiştir:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].quote', 'İki günde oruç tutmak yasaklanmıştır: Ramazan Bayramı günü ve Kurban Bayramı günü.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].hadith', '1138');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].hadith', '1993');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-adha', 'Kurban Bayramı');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-fitr', 'Ramazan Bayramı');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].id', 'fasting-reason-eid-days');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.reasons[0].title', 'Ramazan ve Kurban Bayramları');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.prohibiting.title', 'Haram');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.ics-title', 'Nafile (Tetavvu) oruç sebebi');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[1].cites[0].intro', 'Ebû Katâde (r.a.), Resûlullah’ın (s.a.v.) şöyle buyurduğunu rivayet etmiştir:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[1].cites[0].quote', 'Arefe günü orucunun, önceki yılın ve gelecek yılın günahlarına kefaret olmasını Allah’tan ümit ederim. Âşûrâ günü orucunun da önceki yılın günahlarına kefaret olmasını Allah’tan ümit ederim.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[1].headlines.arafah', 'Arefe Günü');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[1].headlines.ashura', 'Âşûrâ Günü');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[1].id', 'fasting-reason-arafah-or-ashura');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[1].title', 'Arefe ve Âşûrâ Günleri');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[2].cites[0].intro', 'Hz. Peygamber’in (s.a.v.) eşlerinden biri şöyle demiştir:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[2].cites[0].quote', 'Resûlullah (s.a.v.) Zilhicce’nin ilk dokuz gününü, Âşûrâ gününü ve her aydan üç günü oruçlu geçirirdi.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].hadith', '2417');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].hadith', '2437');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[2].id', 'fasting-reason-first-9-dhu-al-hijjah');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[2].title', 'Zilhicce’nin İlk Dokuz Günü');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[1].intro', 'Abdullah b. Amr b. Âs (r.a.) rivayet etti:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[1].quote', 'Sana ayda üç gün oruç yeter. Çünkü her iyiliğin karşılığı on katıyla verilir; böylece bu, bütün yıl oruç tutmuş gibi olur.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].hadith', '1975');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[2].intro', 'Ebû Katâde (r.a.), Resûlullah’ın (s.a.v.) şöyle buyurduğunu rivayet etmiştir:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[2].quote', 'Her aydan üç gün oruç tutmak ve yılda bir Ramazan orucunu tutmak, sürekli oruç gibidir.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[3].intro', 'Resûlullah (s.a.v.) Ebû Zer’e (r.a.) şöyle buyurmuştur:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[3].quote', 'Her aydan üç gün oruç tutmak, bütün yıl oruç tutmak gibidir.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].hadith', '1708');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[4].intro', 'Cerîr b. Abdullah (r.a.) rivayet etti:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[4].quote', 'Her aydan üç gün oruç tutmak, bütün yıl oruç tutmak gibidir. Beyaz günler: on üçüncü, on dördüncü ve on beşinci günlerdir.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].hadith', '2420');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[5].intro', 'Ebû Hüreyre (r.a.) şöyle demiştir:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[5].quote', 'Yakın dostum (s.a.v.) bana üç şeyi tavsiye etti: Her aydan üç gün oruç tutmayı, iki rekât kuşluk namazı kılmayı ve uyumadan önce vitir namazı kılmayı.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].hadith', '1981');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[6].intro', 'Ebû Derdâ (r.a.) şöyle demiştir:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[6].quote', 'Dostum (s.a.v.) bana üç şeyi hiçbir zaman terk etmemem üzere tavsiye etti; bana her aydan üç gün oruç tutmayı tavsiye etti.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].hadith', '1433');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[0].intro', 'Hz. Peygamber (s.a.v.) Ebû Zer’e (r.a.) şöyle buyurmuştur:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[0].quote', 'Ayın herhangi bir günlerinde oruç tutacaksan on üçüncü, on dördüncü ve on beşinci günleri tut.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].hadith', '761');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].id', 'fasting-reason-white-days');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[3].title', 'Beyaz Günler');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[1].intro', 'Üsâme b. Zeyd (r.a.), Resûlullah’ın (s.a.v.) şöyle buyurduğunu rivayet etmiştir:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[1].quote', 'Onlar, amellerin Âlemlerin Rabbi’ne arz edildiği iki gündür. Ben, amelim arz edilirken oruçlu olmayı severim.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].hadith', '2358');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[2].intro', 'Ebû Katâde el-Ensârî (r.a.) Hz. Peygamber’e (s.a.v.) pazartesi günü orucundan sordu; o da şöyle buyurdu:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[2].quote', 'O, benim doğduğum gündür; peygamber olarak gönderildiğim ya da bana vahiy indirilen gündür.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].hadith', '1162b');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[3].intro', 'Hz. Âişe (r.a.) şöyle demiştir:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[3].quote', 'Hz. Peygamber (s.a.v.) pazartesi ve perşembe günleri oruç tutmaya özen gösterirdi.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].hadith', '745');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[0].intro', 'Bu ifade Ebû Hüreyre (r.a.) tarafından rivayet edilmiştir:');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[0].quote', 'Ameller pazartesi ve perşembe günleri arz edilir. Ben de amelim arz edilirken oruçlu olmayı severim.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].collection', 'riyadussalihin');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].hadith', '1256');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].hadith', '747');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].headlines.monday', 'Pazartesi');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].headlines.thursday', 'Perşembe');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].id', 'fasting-reason-monday-thursday');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[4].title', 'Pazartesi ve Perşembe');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[0].cites[1].quote', 'Kim Ramazan orucunu tutar, ardından Şevvâl’den altı gün oruç tutarsa, bütün yıl oruç tutmuş gibi olur.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].hadith', '1716');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[0].cites[2].quote', 'Kim Ramazan ayını oruçlu geçirir, ardından Şevvâl’den altı gün oruç tutarsa, bütün yıl oruç tutmuş gibi olur.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].hadith', '1164');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[0].cites[0].quote', 'Kim Ramazan Bayramı’ndan sonra altı gün oruç tutarsa yılı tamamlamış olur. Çünkü kim bir iyilik yaparsa ona on katı sevap verilir.');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].hadith', '1715');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[0].id', 'fasting-reason-shawwal');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.reasons[0].title', 'Şevvâl’den Altı Gün');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reason-groups.voluntary.title', 'Nafile');
insert into i18n_bundles (locale, code, value) values ('tr', 'fasting.reasons-title', 'Oruç sebepleri');
insert into i18n_bundles (locale, code, value) values ('tr', 'footer.attributions.label', 'Kaynaklar');
insert into i18n_bundles (locale, code, value) values ('tr', 'footer.contacts.github-ref-description', 'Hata bildirimleri, özellik istekleri veya katkılar için lütfen GitHub’ı ziyaret edin.');
insert into i18n_bundles (locale, code, value) values ('tr', 'footer.contacts.label', 'İletişim');
insert into i18n_bundles (locale, code, value) values ('tr', 'hadith-referencing.collections.abudawud', 'Sünen-i Ebû Dâvûd');
insert into i18n_bundles (locale, code, value) values ('tr', 'hadith-referencing.collections.bukhari', 'Sahîh-i Buhârî');
insert into i18n_bundles (locale, code, value) values ('tr', 'hadith-referencing.collections.ibnmajah', 'Sünen-i İbn Mâce');
insert into i18n_bundles (locale, code, value) values ('tr', 'hadith-referencing.collections.muslim', 'Sahîh-i Müslim');
insert into i18n_bundles (locale, code, value) values ('tr', 'hadith-referencing.collections.nasai', 'Sünen-i Nesâî');
insert into i18n_bundles (locale, code, value) values ('tr', 'hadith-referencing.collections.riyadussalihin', 'Riyâzü’s-Sâlihîn');
insert into i18n_bundles (locale, code, value) values ('tr', 'hadith-referencing.collections.tirmidhi', 'Câmiu’t-Tirmizî');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.AUTOMATIC.methodNames.AUTO_BY_LOCATION', 'Konuma göre otomatik');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.AUTOMATIC.name', 'Otomatik');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.ALGERIA', 'Cezayir');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.CIL', 'Lizbon İslâm Topluluğu');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.DIYANET', 'Diyanet (Türkiye)');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.DUBAI', 'Dubai, BAE');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.EGAS', 'Mısır Genel Ölçme Kurumu');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.GULF', 'Körfez Bölgesi');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.ISNA', 'Kuzey Amerika İslâm Cemiyeti (ISNA)');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.JAKIM', 'JAKIM, Malezya');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.KARACHI', 'İslâm İlimleri Üniversitesi, Karaçi');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.KEMENAG', 'Endonezya Din İşleri Bakanlığı');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.KUWAIT', 'Kuveyt');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.MOROCCO', 'Fas');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.MSC', 'Hilal Gözlem Komitesi');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.MUIS', 'Singapur İslâm Meclisi (MUIS)');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.MWL', 'Dünya İslâm Birliği');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.QATAR', 'Katar');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.SAMR', 'Rusya Müslümanları Manevi İdaresi');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.SHIA_QUM', 'Şia İsnâ Aşeriyye, Kum');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.TEHRAN', 'Tahran Üniversitesi Jeofizik Enstitüsü');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.TUNISIA', 'Tunus');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.UMM_AL_QURA', 'Ümmü’l-Kurâ Üniversitesi, Mekke');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.methodNames.UOIF', 'Fransa İslâm Kuruluşları Birliği (UOIF)');
insert into i18n_bundles (locale, code, value) values ('tr', 'prayer-time-method-groups.STANDARD.name', 'Standart');
insert into i18n_bundles (locale, code, value) values ('tr', 'settings.location.forget-custom-location', 'Seçili konumu unut');
insert into i18n_bundles (locale, code, value) values ('tr', 'settings.location.label', 'Konum');
insert into i18n_bundles (locale, code, value) values ('tr', 'settings.location.permission.change-in-browser', 'Mevcut konumu kullan');
insert into i18n_bundles (locale, code, value) values ('tr', 'settings.location.permission.grant-reason', 'İmsak ve iftar vakitleri için');
insert into i18n_bundles (locale, code, value) values ('tr', 'settings.location.permission.revoke-blocking', 'Lütfen site ayarlarından engellemeyi kaldırın');
insert into i18n_bundles (locale, code, value) values ('tr', 'settings.location.pick-on-map', 'Haritada konum seç');
insert into i18n_bundles (locale, code, value) values ('tr', 'settings.prayer-time-method', 'Namaz Vakti Hesaplama Yöntemi');
insert into i18n_bundles (locale, code, value) values ('tr', 'settings.time-zone', 'Saat dilimi');
