--liquibase formatted sql
--changeset id:00023 author:edwgiz@zohomail.eu

insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.current-month', 'موجودہ مہینا');
insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.event.fajr', 'فجر دی نماز');
insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.event.sunset', 'سورج ڈُبھن');
insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.monthNames[1]', 'محرم');
insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.monthNames[2]', 'صفر');
insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.monthNames[3]', 'ربیع الاول');
insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.monthNames[4]', 'ربیع الآخر');
insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.monthNames[5]', 'جمادی الاول');
insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.monthNames[6]', 'جمادی الآخر');
insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.monthNames[7]', 'رجب');
insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.monthNames[8]', 'شعبان');
insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.monthNames[9]', 'رمضان');
insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.monthNames[10]', 'شوال');
insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.monthNames[11]', 'ذوالقعدہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.monthNames[12]', 'ذوالحجہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'calendar.monthNames[0]', '');
insert into i18n_bundles (locale, code, value) values ('pa', 'commons.cancel', 'منسوخ کرو');
insert into i18n_bundles (locale, code, value) values ('pa', 'commons.change', 'تبدیل کرو');
insert into i18n_bundles (locale, code, value) values ('pa', 'commons.forget-custom-location', 'چُنی ہوئی لوکیشن بُھلا دیو');
insert into i18n_bundles (locale, code, value) values ('pa', 'commons.ok', 'ٹھیک اے');
insert into i18n_bundles (locale, code, value) values ('pa', 'commons.or', 'یا');
insert into i18n_bundles (locale, code, value) values ('pa', 'errors.location-access', 'لوکیشن حاصل کرن وچ غلطی:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.head.description', 'طیب روزہ کیلنڈر: سنت نبوی صلی اللہ علیہ وسلم دے مطابق تصدیق شدہ ہجری تاریخاں نال مستند اسلامی روزہ شیڈول۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.head.title', 'اسلامی روزہ کیلنڈر');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.ics.calendar.event.hijri-date-label', 'ہجری');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.ics.calendar.event.summary', 'روزہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.ics.calendar.name', 'اسلامی روزہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.ics.copy-link-label', 'سبسکرپشن لنک کاپی کرو');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.ics.event-summary', 'روزہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.ics.hijri-date-label', 'ہجری');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.ics.label', 'شیڈول اپنے کیلنڈر وچ شامل کرو');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.ics.link-label', 'ICS ڈاؤن لوڈ کرو');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.mcp.copy-link-label', 'MCP لنک کاپی کرو');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.mcp.label', 'اپنے AI ٹولز نوں طاقت دیو');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.generic.ics-title', 'روزے دی وجہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.generic.reasons[0].cites[0].id', 'fasting-reason-generic-0');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.generic.reasons[0].cites[0].quote', 'ابنِ آدم دے ہر عمل دا اجر اوہنوں ملدا اے، سوائے روزے کے؛ کیونکہ اوہ میرے واسطے اے، تے میں ای اوہدا اجر دیواں گا۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].hadith', '1904');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.obligatory.ics-title', 'فرض (واجب) روزے دی وجہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.obligatory.reasons[0].cites[1].quote', 'جس نے ایمان نال تے اجر دی امید نال رمضان دے روزے رکھے، اوہدے پچھلے گناہ معاف کر دتے جاندے نیں۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].hadith', '760');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].hadith', '38');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.obligatory.reasons[0].cites[0].quote', 'اسلام پنج ارکان اتے قائم اے: اس گل دی گواہی دینا کہ اللہ توں علاوہ کوئی عبادت دے لائق نئیں، تے محمد صلی اللہ علیہ وسلم اللہ دے رسول نیں؛ نماز قائم کرنا، زکوٰۃ دینا، حج کرنا، تے رمضان دے روزے رکھنا۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].hadith', '16');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].hadith', '8');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.obligatory.reasons[0].id', 'fasting-reason-ramadan');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.obligatory.reasons[0].title', 'رمضان');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.obligatory.title', 'فرض');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.ics-title', 'حرام (ممنوع) روزے دی وجہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].quote', 'تشریق دے دن کھان پین دے دن نیں۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].hadith', '1141a');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[1].id', 'fasting-reason-tashriq');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[1].title', 'ایامِ تشریق');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].intro', 'ابوعبید (رضی اللہ عنہ) توں روایت اے:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].quote', 'میں عمر (رضی اللہ عنہ) دے نال عید دی نماز وچ حاضر ہویا، اوہناں نے خطبے توں پہلاں نماز پڑھائی، فیر کہیا: رسول اللہ صلی اللہ علیہ وسلم نے ایہناں دو دنیں روزہ رکھن توں منع فرمایا: عید الاضحیٰ دے دن تسیں اپنی قربانی دا گوشت کھاندے او، تے عید الفطر دا دن تہاڈے روزے توڑن دا دن اے۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].hadith', '1722');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].hadith', '2416');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].intro', 'ابوہریرہ (رضی اللہ عنہ) توں روایت اے کہ رسول اللہ صلی اللہ علیہ وسلم نے:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].quote', 'دو روزے حرام نیں: عید الفطر دے دن تے عید الاضحیٰ دے دن روزہ رکھنا۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].hadith', '1138');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].hadith', '1993');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-adha', 'عید الاضحیٰ');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-fitr', 'عید الفطر');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].id', 'fasting-reason-eid-days');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.reasons[0].title', 'عید الفطر تے عید الاضحیٰ');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.prohibiting.title', 'حرام');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.ics-title', 'نفل (تطوع) روزے دی وجہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[1].cites[0].intro', 'ابوقتادہ (رضی اللہ عنہ) توں روایت اے کہ رسول اللہ صلی اللہ علیہ وسلم نے فرمایا:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[1].cites[0].quote', 'میں اللہ توں امید رکھدا ہاں کہ عرفہ دے دن دا روزہ پچھلے تے اگلے سال دے گناہاں دا کفارہ ہووے، تے عاشورہ دے دن دا روزہ پچھلے سال دے گناہاں دا کفارہ ہووے۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[1].headlines.arafah', 'یوم عرفہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[1].headlines.ashura', 'یوم عاشورہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[1].id', 'fasting-reason-arafah-or-ashura');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[1].title', 'عرفہ تے عاشورہ دے دن');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[2].cites[0].intro', 'نبی صلی اللہ علیہ وسلم دیاں ازواجِ مطہرات وچوں ہک بی بی (رضی اللہ عنہا) نے فرمایا:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[2].cites[0].quote', 'رسول اللہ صلی اللہ علیہ وسلم ذی الحجہ دے پہلے نو دن، عاشورہ دے دن، تے ہر مہینے وچ تن دن دا روزہ رکھدے سن…');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].hadith', '2417');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].hadith', '2437');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[2].id', 'fasting-reason-first-9-dhu-al-hijjah');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[2].title', 'ذی الحجہ دے پہلے نو دن');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[1].intro', 'عبداللہ بن عمرو بن العاص (رضی اللہ عنہما) توں روایت اے کہ رسول اللہ صلی اللہ علیہ وسلم نے فرمایا:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[1].quote', 'تہاڈے لئی ایہ کافی اے کہ تسیں ہر مہینے وچ تن دن روزہ رکھو، کیونکہ ہر نیکی دا بدلہ دس گنا ملدا اے، تے ایہ پورے سال دا روزہ بن جاندا اے۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].hadith', '1975');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[2].intro', 'ابوقتادہ (رضی اللہ عنہ) توں روایت اے کہ رسول اللہ صلی اللہ علیہ وسلم نے فرمایا:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[2].quote', 'ہر مہینے وچ تن دن روزہ رکھنا، تے رمضان توں رمضان تک روزہ رکھنا، ایہ سدا دا روزہ اے۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[3].intro', 'رسول اللہ صلی اللہ علیہ وسلم نے ابوذر (رضی اللہ عنہ) نوں فرمایا:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[3].quote', 'جس نے ہر مہینے وچ تن دن روزہ رکھیا، ایہ عمر بھر دا روزہ اے۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].hadith', '1708');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[4].intro', 'جریر بن عبداللہ (رضی اللہ عنہ) توں روایت اے کہ نبی صلی اللہ علیہ وسلم نے فرمایا:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[4].quote', 'ہر مہینے وچ تن دن دا روزہ عمر بھر دا روزہ اے، تے ایامِ بیض دے روزے: تیرہویں، چودہویں تے پندرہویں۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].hadith', '2420');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[5].intro', 'ابوہریرہ (رضی اللہ عنہ) توں روایت اے:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[5].quote', 'میرے پیارے دوست (نبی صلی اللہ علیہ وسلم) نے مینوں تن گلاں دی وصیت کیتی: ہر مہینے وچ تن دن روزہ رکھنا، دو رکعت چاشت دی نماز، تے سون توں پہلاں وتر پڑھنا۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].hadith', '1981');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[6].intro', 'ابوالدرداء (رضی اللہ عنہ) توں روایت اے:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[6].quote', 'میرے پیارے دوست (نبی صلی اللہ علیہ وسلم) نے مینوں تن ایسیاں گلاں دی وصیت کیتی جہڑیاں میں کدی نئیں چھڈاں گا؛ اوہناں وچوں ہر مہینے وچ تن دن دے روزے نیں۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].hadith', '1433');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[0].intro', 'نبی صلی اللہ علیہ وسلم نے ابوذر (رضی اللہ عنہ) نوں نصیحت کردے ہوئے فرمایا:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[0].quote', 'اے ابوذر! جے تسیں مہینے وچ تن دن روزہ رکھو، تاں تیرہویں، چودہویں تے پندرہویں نوں رکھو۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].hadith', '761');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].id', 'fasting-reason-white-days');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[3].title', 'ایامِ بیض');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[1].intro', 'اسامہ بن زید (رضی اللہ عنہما) توں روایت اے کہ رسول اللہ صلی اللہ علیہ وسلم نے فرمایا:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[1].quote', 'ایہ اوہ دو دن نیں جنہاں وچ جہاناں دے رب دے حضور عمل پیش کیتے جاندے نیں، تے میں پسند کریندا ہاں کہ میرا عمل پیش ہووے تے میں روزے نال ہوواں۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].hadith', '2358');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[2].intro', 'ابوقتادہ انصاری (رضی اللہ عنہ) توں روایت اے کہ نبی صلی اللہ علیہ وسلم توں سوموار دے روزے بارے پچھیا گیا، تاں آپ نے فرمایا:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[2].quote', 'ایہ اوہ دن اے جس وچ میں پیدا ہویا، تے جس وچ مینوں نبوت دتی گئی، یا میرے اتے وحی نازل ہوئی۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].hadith', '1162b');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[3].intro', 'عائشہ (رضی اللہ عنہا) توں روایت اے:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[3].quote', 'نبی صلی اللہ علیہ وسلم سوموار تے جمعرات دے روزیاں دا خاص اہتمام فرمایا کردے سن۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].hadith', '745');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[0].intro', 'ابوہریرہ (رضی اللہ عنہ) توں روایت اے کہ رسول اللہ صلی اللہ علیہ وسلم نے فرمایا:');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[0].quote', 'عمل سوموار تے جمعرات نوں پیش کیتے جاندے نیں، تے میں پسند کریندا ہاں کہ میرا عمل پیش ہووے تے میں روزے نال ہوواں۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].collection', 'riyadussalihin');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].hadith', '1256');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].hadith', '747');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].headlines.monday', 'سوموار');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].headlines.thursday', 'جمعرات');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].id', 'fasting-reason-monday-thursday');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[4].title', 'سوموار تے جمعرات');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[0].cites[1].quote', 'جس نے رمضان دے روزے رکھے، فیر اوہدے بعد شوال دے چھ دن روزہ رکھے، ایہ عمر بھر دے روزے ورگا اے۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].hadith', '1716');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[0].cites[2].quote', 'جس نے رمضان دا مہینہ روزے رکھیا، فیر اوہدے بعد شوال وچ چھ دن روزہ رکھیا، ایویں اوہنے پورا سال دا روزہ رکھیا۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].hadith', '1164');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[0].cites[0].quote', 'جس نے عید الفطر دے بعد چھ دن روزہ رکھیا، اوہنے سال بھر دا اجر پورا کر لیا؛ ہر نیکی دا بدلہ دس گنا ملدا اے۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].hadith', '1715');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[0].id', 'fasting-reason-shawwal');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.reasons[0].title', 'شوال دے چھ دن');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reason-groups.voluntary.title', 'نفل');
insert into i18n_bundles (locale, code, value) values ('pa', 'fasting.reasons-title', 'روزے دیاں وجوہات');
insert into i18n_bundles (locale, code, value) values ('pa', 'footer.attributions.label', 'حوالے');
insert into i18n_bundles (locale, code, value) values ('pa', 'footer.contacts.github-ref-description', 'مسائل، فیچر درخواستاں، یا تعاون لئی براہِ مہربانی GitHub تے جاؤ۔');
insert into i18n_bundles (locale, code, value) values ('pa', 'footer.contacts.label', 'رابطہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'hadith-referencing.collections.abudawud', 'سنن ابی داؤد');
insert into i18n_bundles (locale, code, value) values ('pa', 'hadith-referencing.collections.bukhari', 'صحیح بخاری');
insert into i18n_bundles (locale, code, value) values ('pa', 'hadith-referencing.collections.ibnmajah', 'سنن ابن ماجہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'hadith-referencing.collections.muslim', 'صحیح مسلم');
insert into i18n_bundles (locale, code, value) values ('pa', 'hadith-referencing.collections.nasai', 'سنن نسائی');
insert into i18n_bundles (locale, code, value) values ('pa', 'hadith-referencing.collections.riyadussalihin', 'ریاض الصالحین');
insert into i18n_bundles (locale, code, value) values ('pa', 'hadith-referencing.collections.tirmidhi', 'جامع ترمذی');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.AUTOMATIC.methodNames.AUTO_BY_LOCATION', 'لوکیشن دے مطابق خودکار');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.AUTOMATIC.name', 'خودکار');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.ALGERIA', 'الجیریا');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.CIL', 'اسلامی کمیونٹی لزبن');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.DIYANET', 'دیانت (ترکی)');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.DUBAI', 'دبئی، متحدہ عرب امارات');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.EGAS', 'مصری جنرل اتھارٹی آف سروے');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.GULF', 'خلیجی علاقہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.ISNA', 'اسلامک سوسائٹی آف نارتھ امریکہ (ISNA)');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.JAKIM', 'جاکیم، ملائیشیا');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.KARACHI', 'یونیورسٹی آف اسلامک سائنسز، کراچی');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.KEMENAG', 'وزارت مذہبی امور، انڈونیشیا');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.KUWAIT', 'کویت');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.MOROCCO', 'مراکش');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.MSC', 'رویتِ ہلال کمیٹی');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.MUIS', 'مجلس امور اسلامیہ سنگاپور (MUIS)');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.MWL', 'مسلم ورلڈ لیگ');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.QATAR', 'قطر');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.SAMR', 'روس دے مسلماناں دی روحانی انتظامیہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.SHIA_QUM', 'شیعہ اثنا عشریہ، قم');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.TEHRAN', 'انسٹی ٹیوٹ آف جیوفزکس، یونیورسٹی تہران');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.TUNISIA', 'تیونس');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.UMM_AL_QURA', 'جامعہ ام القریٰ، مکہ مکرمہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.methodNames.UOIF', 'فرانس دی اسلامی تنظیمات دا اتحاد (UOIF)');
insert into i18n_bundles (locale, code, value) values ('pa', 'prayer-time-method-groups.STANDARD.name', 'معیاری');
insert into i18n_bundles (locale, code, value) values ('pa', 'settings.location.forget-custom-location', 'چُنی ہوئی لوکیشن بُھلا دیو');
insert into i18n_bundles (locale, code, value) values ('pa', 'settings.location.label', 'لوکیشن');
insert into i18n_bundles (locale, code, value) values ('pa', 'settings.location.permission.change-in-browser', 'موجودہ لوکیشن ورتو');
insert into i18n_bundles (locale, code, value) values ('pa', 'settings.location.permission.grant-reason', 'فجر تے غروب دے ویلے لئی');
insert into i18n_bundles (locale, code, value) values ('pa', 'settings.location.permission.revoke-blocking', 'براہ مہربانی سائیٹ سیٹنگز وچ پابندی ہٹاؤ');
insert into i18n_bundles (locale, code, value) values ('pa', 'settings.location.pick-on-map', 'نقشے تے لوکیشن چُݨو');
insert into i18n_bundles (locale, code, value) values ('pa', 'settings.prayer-time-method', 'نماز دے ویلیاں دا طریقہ');
insert into i18n_bundles (locale, code, value) values ('pa', 'settings.time-zone', 'ٹائم زون');
