--liquibase formatted sql
--changeset id:00024 author:edwgiz@zohomail.eu

insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.current-month', 'اوسنۍ میاشت');
insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.event.fajr', 'فجر');
insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.event.sunset', 'غروب');
insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.monthNames[1]', 'محرم');
insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.monthNames[2]', 'صفر');
insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.monthNames[3]', 'ربیع الاول');
insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.monthNames[4]', 'ربیع الثاني');
insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.monthNames[5]', 'جمادی الاول');
insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.monthNames[6]', 'جمادی الثاني');
insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.monthNames[7]', 'رجب');
insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.monthNames[8]', 'شعبان');
insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.monthNames[9]', 'رمضان');
insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.monthNames[10]', 'شوال');
insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.monthNames[11]', 'ذوالقعده');
insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.monthNames[12]', 'ذوالحجه');
insert into i18n_bundles (locale, code, value) values ('ps', 'calendar.monthNames[0]', '');
insert into i18n_bundles (locale, code, value) values ('ps', 'commons.cancel', 'لغوه');
insert into i18n_bundles (locale, code, value) values ('ps', 'commons.change', 'بدلول');
insert into i18n_bundles (locale, code, value) values ('ps', 'commons.forget-custom-location', 'ټاکل شوی ځای هېر کړئ');
insert into i18n_bundles (locale, code, value) values ('ps', 'commons.ok', 'سمه ده');
insert into i18n_bundles (locale, code, value) values ('ps', 'commons.or', 'یا');
insert into i18n_bundles (locale, code, value) values ('ps', 'errors.location-access', 'د ځای په ترلاسه کولو کې تېروتنه:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.head.description', 'د طیب روژې کلیزه: د سنت نبوي سره سم او تایید شویو هجري نېټو پر بنسټ د اسلامي روژې کره مهالوېشونه.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.head.title', 'اسلامي روژې کلیزه');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.ics.calendar.event.hijri-date-label', 'هجري');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.ics.calendar.event.summary', 'روژه');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.ics.calendar.name', 'اسلامي روژه');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.ics.copy-link-label', 'د ګډون لینک کاپي کړئ');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.ics.event-summary', 'روژه');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.ics.hijri-date-label', 'هجري');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.ics.label', 'مهالوېش خپلې کلیزې ته زیات کړئ');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.ics.link-label', 'ICS ډاونلوډ کړئ');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.mcp.copy-link-label', 'د MCP لینک کاپي کړئ');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.mcp.label', 'د مصنوعي ځیرکتیا خپلې وسیلې واکمنې کړئ');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.generic.ics-title', 'د روژې لامل');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.generic.reasons[0].cites[0].id', 'fasting-reason-generic-0');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.generic.reasons[0].cites[0].quote', 'الله تعالی فرمایي: د آدم زوی هر عمل د هغه لپاره دی، پرته له روژې؛ بېشکه روژه زما لپاره ده او زه به یې اجر ورکړم.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.generic.reasons[0].cites[0].references[0].hadith', '1904');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.obligatory.ics-title', 'د واجبي روژې لامل');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.obligatory.reasons[0].cites[1].quote', 'چا چې د رمضان روژه په ایمان او د اجر په امید ونیوله، د هغه تېر ګناهونه وبښل شي.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[1].hadith', '760');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.obligatory.reasons[0].cites[1].references[0].hadith', '38');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.obligatory.reasons[0].cites[0].quote', 'اسلام پر پنځو بنسټونو ولاړ دی: د دې شهادت چې له الله پرته بل معبود نشته او محمد د الله رسول دی، د لمانځه اقامه، د زکات ورکول، د حج ادا کول او د رمضان روژه.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[1].hadith', '16');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.obligatory.reasons[0].cites[0].references[0].hadith', '8');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.obligatory.reasons[0].id', 'fasting-reason-ramadan');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.obligatory.reasons[0].title', 'رمضان');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.obligatory.title', 'واجب');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.ics-title', 'د روژې د حرمت لامل');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].quote', 'د تشریق ورځې د خوړو او څښاک ورځې دي.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[1].cites[0].references[0].hadith', '1141a');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[1].id', 'fasting-reason-tashriq');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[1].title', 'د تشریق ورځې');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].intro', 'ابوعبید (رض) روایت کوي:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].quote', 'ما له عمر (رض) سره د اختر لمانځه وکړ؛ هغه لومړی لمونځ ادا کړ او بیا یې خطبه وکړه. بیا یې وویل: رسول الله صلی الله علیه وسلم د دې دوو ورځو روژه منع کړې ده. د قربان اختر ورځ تاسو د خپلو قربانیو غوښه خورئ، او د فطر اختر ورځ تاسو خپله روژه ماتوئ.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[1].hadith', '1722');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].cites[1].references[0].hadith', '2416');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].intro', 'ابوهریره (رض) روایت کوي چې رسول الله صلی الله علیه وسلم فرمایلي:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].quote', 'دوه روژې منع شوي دي: د فطر اختر ورځ او د قربان اختر ورځ.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[1].hadith', '1138');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].cites[0].references[0].hadith', '1993');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-adha', 'قربان اختر');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].headlines.eid-al-fitr', 'فطر اختر');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].id', 'fasting-reason-eid-days');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.reasons[0].title', 'فطر اختر او قربان اختر');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.prohibiting.title', 'حرام');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.ics-title', 'د نفلي روژې لامل');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[1].cites[0].intro', 'ابوقتاده (رض) روایت کوي چې رسول الله صلی الله علیه وسلم فرمایلي:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[1].cites[0].quote', 'زه له الله څخه امید لرم چې د عرفې ورځې روژه د تېر او راتلونکي کال ګناهونه معاف کړي، او له الله څخه امید لرم چې د عاشورا ورځې روژه د تېر کال ګناهونه معاف کړي.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[1].cites[0].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[1].headlines.arafah', 'د عرفې ورځ');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[1].headlines.ashura', 'د عاشورا ورځ');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[1].id', 'fasting-reason-arafah-or-ashura');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[1].title', 'د عرفې او عاشورا ورځې');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[2].cites[0].intro', 'د نبوي صلی الله علیه وسلم یوې مېرمنې (رض) فرمایلي:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[2].cites[0].quote', 'رسول الله صلی الله علیه وسلم به د ذوالحجې لومړۍ نهه ورځې، د عاشورا ورځ او هره میاشت درې ورځې روژه نیوله.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[1].hadith', '2417');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[2].cites[0].references[0].hadith', '2437');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[2].id', 'fasting-reason-first-9-dhu-al-hijjah');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[2].title', 'د ذوالحجې لومړۍ نهه ورځې');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[1].intro', 'عبدالله بن عمرو بن العاص (رض) روایت کوي چې رسول الله صلی الله علیه وسلم وفرمایلي:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[1].quote', 'تا لپاره دا کافي ده چې هره میاشت درې ورځې روژه ونیسې؛ ځکه چې د هرې نیکۍ اجر لس برابره دی، نو دا د ټول عمر روژه ده.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[1].references[0].hadith', '1975');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[2].intro', 'ابوقتاده (رض) روایت کوي چې رسول الله صلی الله علیه وسلم فرمایلي:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[2].quote', 'هره میاشت درې ورځې روژه او له رمضان څخه تر رمضان، دا د ټول عمر روژه ده.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[2].references[0].hadith', '1162');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[3].intro', 'رسول الله صلی الله علیه وسلم ابوذرها (رض) ته وفرمایلي:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[3].quote', 'چا چې هره میاشت درې ورځې روژه ونیوله، دا د ټول عمر روژه ده.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[3].references[0].hadith', '1708');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[4].intro', 'جریر بن عبدالله (رض) روایت کوي چې نبوي صلی الله علیه وسلم فرمایلي:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[4].quote', 'د هرې میاشتې درې ورځې روژه د ټول عمر روژه ده؛ او روښانه ورځې: دیارلسمه، څوارلسمه او پنځلسمه.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[4].references[0].hadith', '2420');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[5].intro', 'ابوهریره (رض) روایت کوي:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[5].quote', 'زما نږدې ملګري (نبوي صلی الله علیه وسلم) ما ته درې شیان وسپارل: هره میاشت درې ورځې روژه، دوه رکعته ضحی، او د ویده کېدو مخکې وتر.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].collection', 'bukhari');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[5].references[0].hadith', '1981');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[6].intro', 'ابودرداء (رض) روایت کوي:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[6].quote', 'زما ملګري (نبوي صلی الله علیه وسلم) ما ته درې داسې اعمال وسپارل چې زه به یې د هیڅ شي لپاره نه پرېږدم: هره میاشت درې ورځې روژه.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].collection', 'abudawud');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[6].references[0].hadith', '1433');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[0].intro', 'نبوي صلی الله علیه وسلم ابوذرها (رض) ته وفرمایلي:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[0].quote', 'ای ابوذره! که د میاشتې کومه ورځ روژه نیسې، نو دیارلسمه، څوارلسمه او پنځلسمه ورځ روژه ونیسه.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].cites[0].references[0].hadith', '761');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].id', 'fasting-reason-white-days');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[3].title', 'روښانه ورځې');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[1].intro', 'اسامه بن زید (رض) روایت کوي چې رسول الله صلی الله علیه وسلم فرمایلي:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[1].quote', 'دا دوه ورځې دي چې اعمال پکې د رب العلمین حضوري ته وړاندې کیږي، او زه غواړم چې زما اعمال د روژې په حالت کې وړاندې شي.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].collection', 'nasai');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[1].references[0].hadith', '2358');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[2].intro', 'ابوقتاده انصاري (رض) له نبوي صلی الله علیه وسلم څخه د دوشنبې د روژې په اړه پوښتنه وکړه، هغه فرمایلي:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[2].quote', 'دا هغه ورځ ده چې زه پکې پیدا شوی یم، او هغه ورځ ده چې زما بعثت پکې وشو یا راته وحی نازله شوه.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[2].references[0].hadith', '1162b');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[3].intro', 'عایشه (رض) فرمایلي:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[3].quote', 'نبوي صلی الله علیه وسلم د دوشنبې او پنجشنبې د روژې ته ځانګړی پام کاوه.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[3].references[0].hadith', '745');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[0].intro', 'دا خبره ابوهریره (رض) روایت کوي:');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[0].quote', 'اعمال په دوشنبه او پنجشنبه ورځو وړاندې کیږي، او زه غواړم چې زما اعمال د روژې په حالت کې وړاندې شي.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].collection', 'riyadussalihin');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[1].hadith', '1256');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].collection', 'tirmidhi');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].cites[0].references[0].hadith', '747');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].headlines.monday', 'دوشنبه');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].headlines.thursday', 'پنجشنبه');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].id', 'fasting-reason-monday-thursday');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[4].title', 'دوشنبه او پنجشنبه');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[0].cites[1].quote', 'چا چې د رمضان روژه ونیوله او بیا یې د شوال شپږ ورځې روژه ونیوله، دا د ټول عمر روژه ده.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[0].cites[1].references[0].hadith', '1716');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[0].cites[2].quote', 'چا چې د رمضان میاشت روژه ونیوله او بیا یې د شوال شپږ ورځې تعقیب کړې، داسې ده لکه د ټول کال روژه.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].collection', 'muslim');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[0].cites[2].references[0].hadith', '1164');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[0].cites[0].quote', 'چا چې د فطر څخه وروسته شپږ ورځې روژه ونیوله، د کال ثواب یې بشپړ شو؛ ځکه چې د هرې نیکۍ لپاره لس برابره پاداش دی.');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].collection', 'ibnmajah');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[0].cites[0].references[0].hadith', '1715');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[0].id', 'fasting-reason-shawwal');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.reasons[0].title', 'د شوال شپږ ورځې');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reason-groups.voluntary.title', 'نفلي');
insert into i18n_bundles (locale, code, value) values ('ps', 'fasting.reasons-title', 'د روژې لاملونه');
insert into i18n_bundles (locale, code, value) values ('ps', 'footer.attributions.label', 'مننې');
insert into i18n_bundles (locale, code, value) values ('ps', 'footer.contacts.github-ref-description', 'مهرباني وکړئ د ستونزو، د نویو ځانګړتیاوو غوښتنو او ونډې لپاره ګیټ هب (GitHub) وګورئ.');
insert into i18n_bundles (locale, code, value) values ('ps', 'footer.contacts.label', 'اړیکې');
insert into i18n_bundles (locale, code, value) values ('ps', 'hadith-referencing.collections.abudawud', 'سنن ابي داود');
insert into i18n_bundles (locale, code, value) values ('ps', 'hadith-referencing.collections.bukhari', 'صحیح بخاري');
insert into i18n_bundles (locale, code, value) values ('ps', 'hadith-referencing.collections.ibnmajah', 'سنن ابن ماجه');
insert into i18n_bundles (locale, code, value) values ('ps', 'hadith-referencing.collections.muslim', 'صحیح مسلم');
insert into i18n_bundles (locale, code, value) values ('ps', 'hadith-referencing.collections.nasai', 'سنن نسائي');
insert into i18n_bundles (locale, code, value) values ('ps', 'hadith-referencing.collections.riyadussalihin', 'ریاض الصالحین');
insert into i18n_bundles (locale, code, value) values ('ps', 'hadith-referencing.collections.tirmidhi', 'جامع ترمذي');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.AUTOMATIC.methodNames.AUTO_BY_LOCATION', 'د ځای پر بنسټ اتوماتیک');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.AUTOMATIC.name', 'اتوماتیک');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.ALGERIA', 'الجزایر');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.CIL', 'د لیسبون اسلامي ټولنه');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.DIYANET', 'دیانېت (ترکیه)');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.DUBAI', 'دوبۍ، متحده عرب امارات');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.EGAS', 'د مصر د سروې عمومي اداره');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.GULF', 'د خلیج سیمه');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.ISNA', 'د شمالي امریکا اسلامي ټولنه (ISNA)');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.JAKIM', 'جاکیم، مالیزیا');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.KARACHI', 'د اسلامي علومو پوهنتون، کراچۍ');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.KEMENAG', 'د اندونیزیا د دیني چارو وزارت');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.KUWAIT', 'کویټ');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.MOROCCO', 'مراکش');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.MSC', 'د هلال د لیدو کمېټه');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.MUIS', 'د سینګاپور د اسلامي دیني شورا (MUIS)');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.MWL', 'د اسلامي نړۍ ټولنه');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.QATAR', 'قطر');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.SAMR', 'د روسیې د مسلمانانو روحاني اداره');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.SHIA_QUM', 'شیعه اثنا عشریه، قم');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.TEHRAN', 'د جیوفزیک انسټیټیوټ، د تهران پوهنتون');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.TUNISIA', 'تونس');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.UMM_AL_QURA', 'د ام القری پوهنتون، مکه مکرمه');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.methodNames.UOIF', 'د فرانسې د اسلامي سازمانونو اتحادیه (UOIF)');
insert into i18n_bundles (locale, code, value) values ('ps', 'prayer-time-method-groups.STANDARD.name', 'معیاري');
insert into i18n_bundles (locale, code, value) values ('ps', 'settings.location.forget-custom-location', 'ټاکل شوی ځای هېر کړئ');
insert into i18n_bundles (locale, code, value) values ('ps', 'settings.location.label', 'ځای');
insert into i18n_bundles (locale, code, value) values ('ps', 'settings.location.permission.change-in-browser', 'اوسنی ځای وکاروئ');
insert into i18n_bundles (locale, code, value) values ('ps', 'settings.location.permission.grant-reason', 'د فجر او غروب وختونو لپاره');
insert into i18n_bundles (locale, code, value) values ('ps', 'settings.location.permission.revoke-blocking', 'مهرباني وکړئ د سایټ په تنظیماتو کې بندیز لرې کړئ');
insert into i18n_bundles (locale, code, value) values ('ps', 'settings.location.pick-on-map', 'په نقشه کې ځای وټاکئ');
insert into i18n_bundles (locale, code, value) values ('ps', 'settings.prayer-time-method', 'د لمونځ د وختونو طریقه');
insert into i18n_bundles (locale, code, value) values ('ps', 'settings.time-zone', 'د وخت زون');
