package com.github.edwgiz.tayyib.domain.model;

public enum PrayerTimeMethod {

    MUSLIM_WORLD_LEAGUE,
    ISLAMIC_SOCIETY_OF_NORTH_AMERICA,
    EGYPTIAN_GENERAL_AUTHORITY_OF_SURVEY,
    UMM_AL_QURA_UNIVERSITY_MAKKAH,
    UNIVERSITY_OF_ISLAMIC_SCIENCES_KARACHI,
    INSTITUTE_OF_GEOPHYSICS_TEHRAN,
    SHIA_ITHNA_ASHARI_QUM,
    GULF_REGION,
    KUWAIT,
    QATAR,
    MAJLIS_UGAMA_ISLAM_SINGAPORE,
    UNION_ORGANIZATION_ISLAMIC_FRANCE,
    DIYANET_TURKEY,
    SPIRITUAL_ADMINISTRATION_OF_MUSLIMS_OF_RUSSIA,
    MOON_SIGHTING_COMMITTEE,
    DUBAI_UAE,
    JAKIM_MALAYSIA,
    TUNISIA,
    ALGERIA,
    KEMENTERIAN_AGAMA_INDONESIA,
    MOROCCO,
    COMUNIDADE_ISLAMICA_DE_LISBOA;

}
