scalar ID @specifiedBy(url: "https://tools.ietf.org/html/rfc4122")
scalar Long
scalar Upload

type Query {
    findNutrientsByParentId(parentId: ID): [Nutrient!]
    getCalendarCells(input: GetCalendarCellsInput!): GetCalendarCellsResult!
}

type Mutation {
    uploadFdcNutrients(file: Upload!): UploadNutrientResult!
}

type UploadNutrientResult {
    created: Int!,
    skipped: Int!
}

type Nutrient {
    id: ID!
    parent_id: ID!
    name: String!
    description: String!
    links: [NutrientLink!]!
}

type NutrientLink {
    id: ID!
    url: String!
    title: String!
}


input GetCalendarCellsInput {
    millis: Long!,
    timezone: String!,
    hijriMethod: HijriMethod!,
    prayerTimeMethod: PrayerTimeMethod!,
    location: GeoPointInput
}


input GeoPointInput {
    latitude: Float!
    longitude: Float!
}

enum HijriMethod {
    HJCoSA,
    UAQ,
    Diyanet
}

enum PrayerTimeMethod {
    MUSLIM_WORLD_LEAGUE,
    ISLAMIC_SOCIETY_OF_NORTH_AMERICA,
    EGYPTIAN_GENERAL_AUTHORITY_OF_SURVEY,
    UMM_AL_QURA_UNIVERSITY_MAKKAH,
    UNIVERSITY_OF_ISLAMIC_SCIENCES_KARACHI,
    INSTITUTE_OF_GEOPHYSICS_TEHRAN,
    SHIA_ITHNA_ASHARI_QUM,
    GULF_REGION,
    KUWAIT,
    QATAR,
    MAJLIS_UGAMA_ISLAM_SINGAPORE,
    UNION_ORGANIZATION_ISLAMIC_FRANCE,
    DIYANET_TURKEY,
    SPIRITUAL_ADMINISTRATION_OF_MUSLIMS_OF_RUSSIA,
    MOON_SIGHTING_COMMITTEE,
    DUBAI_UAE,
    JAKIM_MALAYSIA,
    TUNISIA,
    ALGERIA,
    KEMENTERIAN_AGAMA_INDONESIA,
    MOROCCO,
    COMUNIDADE_ISLAMICA_DE_LISBOA
}

type GetCalendarCellsResult {
    hijriMonthNames: [StringToStringEntry!]!
    calendarEventReasons: [CalendarEventReason!]!
    currentMonthLabel: String!
    dayOfWeekNames: [String!]!
    days: [CalendarDay!]!
    todayIndex: Int
}

type StringToStringEntry {
    key: String!
    value: String!
}

type CalendarDay {
    gregorian: GregorianCalendarDay!
    hijri: HijriCalendarDay!
    events: [CalendarEvent!]
}

type GregorianCalendarDay {
    isAdjacentMonth: Boolean!,
    dayOfMonth: Int!
}

type HijriCalendarDay {
    dayOfMonth: Int!
    month: Int!
}

type CalendarEvent {
    "The reason title by reason identifier"
    reasonViews: [CalendarEventReasonView!]!
    startMinute: Int
    endMinute: Int
}

type CalendarEventReason {
    id: String!
    reasonGroup: CalendarEventReasonGroup!
}

type CalendarEventReasonView {
    id: String!
    headline: String
}

enum CalendarEventReasonGroup {
    OBLIGATORY_FASTING,
    VOLUNTARY_FASTING,
    PROHIBITING_FASTING,
}
