scalar ID @specifiedBy(url: "https://tools.ietf.org/html/rfc4122")
scalar Long
scalar Upload

type Query {
    findNutrientsByParentId(parentId: ID): [Nutrient!]
    getCalendarCells(millis: Long!, timezoneOffset: Int!, method: HijriMethod!): GetCalendarCellsResult!
}

type Mutation {
    uploadFdcNutrients(file: Upload!): UploadNutrientResult!
}

type UploadNutrientResult {
    created: Int!,
    skipped: Int!
}

type Nutrient {
    id: ID!
    parent_id: ID!
    name: String!
    description: String!
    links: [NutrientLink!]!
}

type NutrientLink {
    id: ID!
    url: String!
    title: String!
}

enum HijriMethod {
    HJCoSA,
    UAQ,
    Diyanet
}

type GetCalendarCellsResult {
    hijriMonthNames: [StringToStringEntry!]!
    tooltips: [StringToStringEntry!]!
    currentMonthLabel: String!
    dayOfWeekNames: [String!]!
    days: [CalendarDay!]!
    todayIndex: Int
}

type StringToStringEntry {
    key: String!
    value: String!
}

type CalendarDay {
    gregorian: GregorianCalendarDay!
    hijri: HijriCalendarDay!
    events: [CalendarEvent!]
}

type GregorianCalendarDay {
    isAdjacentMonth: Boolean!,
    dayOfMonth: Int!
}

type HijriCalendarDay {
    dayOfMonth: Int!
    month: Int!
}

type CalendarEvent {
    reasonId: String!
    reasonType: CalendarEventType!
    tooltip: String
}

enum CalendarEventType {
    OBLIGATORY_FASTING,
    VOLUNTARY_FASTING,
    PROHIBITING_FASTING,
}
